### ISSUE TITLE
Install problem with MySQL on shared host

### ISSUE THREAD

**Issue by petrk94** [redmatrix/hubzilla#1014]
Hello,
I want to host hubzilla on my uberspace shared host account.
Due the host is running on CentOS 6, the MySQL dont can handle UTF8m4. As alternative i have a working MariaDB instance accessible through phpmyadmin. while installing hubzilla I get the page that the SQL file has to be imported manually, this fails in the MySQL database. In MariaDB its working fine and I can finish the installation. But when I try to open the website I get "Apologies but this site is unavailable at the moment. Please try again later.". I had changed the Port to the MariaDB database, but it doesnt work.

I hope you can help.
Thanks

**Comment by zotlabs** [comment]
> Apologies but this site is unavailable at the moment. Please try again later

This always indicates that we could not connect to the DB. Double check or triple check the database connection settings in .htconfig.php

**Comment by petrk94** [comment]
> .htconfig.php

Where I can find it?
I find in the install folder only a htconfig.sample.php file.

Please help

**Comment by git-marijus** [comment]
It is located in the web root folder.

**Comment by petrk94** [comment]
@zotlabs  @git-marijus thanks for your help
now its working, the port number was in the file still 0, thats why it didnt worked.
