### ISSUE TITLE
Usability upload photos when making a post

### ISSUE THREAD

**Issue by akayani** [redmatrix/hubzilla#1018]
You can't load a photo into a post unless you have uploaded the photo already. (Correct me if I'm wrong)

Needs an option to upload a photo within the dialogue that allows a photo to be picked from the library. I'm guessing this is so obvious that it is on a list for future features. (Obviously I just click photos with the control key and open a new tab. Likely a pain if you are doing this on the phone.)

On the dialogue for photo upload the word upload is repeated on 2 buttons. The blue lower button would be better called 'Select' or the top button called 'Add'. **Maybe 'Add' and 'Upload'.** Just to get rid of that initial "upload, upload, what's this" when you first start using the system.

**Comment by zotlabs** [comment]
Use the paper clip "attach" link.

**Comment by akayani** [comment]
I would never have even looked at that for the purpose of adding a photo. Even though the hint is perfectly clear. Thanks for pointing it out, lest I be lost in my ignorance. 

Once I'm used to this I'm going to be useless at making comments on usability. Ignore them as you see fit, I do when constructing websites.

**Comment by zotlabs** [comment]
Share your thoughts and impressions in any event because it isn't always obvious to us where people encounter difficulty.

**Comment by zotlabs** [comment]
I've just changed the hover text associated with these buttons to emphasise their different roles a bit more clearly.
