### ISSUE TITLE
Database update fails

### ISSUE THREAD

**Issue by anmol26s** [redmatrix/hubzilla#1029]
The database update 1197 is failing.
I tried manual update with the error:

`Can't DROP 'diaspora_meta'; check that column/key exists`

**Comment by zotlabs** [comment]
If your item table does not have a diaspora_meta column you can safely ignore this and mark it manually completed in the admin/dbsync panel.

**Comment by anmol26s** [comment]
Ok , I have marked manually completed in the update in admin/dbsync panel.

But now poller.php is giving me:
```
<html>
<head><title>System Unavailable</title></head>
<body>
Apologies but this site is unavailable at the moment. Please try again later.
</body>
```
I am not getting updates from hubzilla but updates from other fedrated networks are working.
I have triple checked my database password.

**Comment by zotlabs** [comment]
That's very unusual. So daemon processes cannot open the db, but web processes can. They all use the same configuration file. My best guess is that the webserver is getting passed an environment variable which is needed to communicate with the db. From cli processes which don't share that environment this is missing. Try running util/config from a shell and see if that gives you any more useful error text.

**Comment by anmol26s** [comment]
> Try running util/config from a shell and see if that gives you any more useful error text.

Its giving me same result.

```
<html>
<head><title>System Unavailable</title></head>
<body>
Apologies but this site is unavailable at the moment. Please try again later.
</body>

```

How can debug further?

**Comment by anmol26s** [comment]
Installing the `sudo apt-get install php-xml` solved the problem. I don't know when it got deleted.
