### ISSUE TITLE
Enhancement request:  plugin to use randomly selected animal icons as default profile picture

### ISSUE THREAD

**Issue by crasch** [redmatrix/hubzilla#1034]
Instead of the same avatar, assign new users who haven't uploaded a profile picture a randomly selected animal icon:

https://commons.wikimedia.org/wiki/Category:Creative_Tail_Round_Animal_Icons#

There's roughly 40 avatars available from this set, Creative Commons  licensed for commercial use:

https://www.creativetail.com/40-free-flat-animal-icons/

Maybe do the same for profile images:

http://ipadwallpapergallery.com/wallpapers/nature/

**Comment by zotlabs** [comment]
There is an addon in dev called cavatar which implements this and shows how to implement this. Cavatar has a very small pixel size (175px) so the resulting quality is poor. It was provided mostly as a demo for those who wish to pursue this kind of thing. Ideally we work with 300px square base images, and anything less will probably be unsuitable for most folks.

**Comment by crasch** [comment]
Awesome, thanks for the pointer.
