### ISSUE TITLE
Bug: embeded youtube video doesn't work

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1035]
I added youtube link to my post (direct link to youtube video without any tags):
![2018-04-02-122255_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38191461-78f9f9d4-3671-11e8-9c46-02f48e52d796.png)
When i click on image i see:
![2018-04-02-122309_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38191475-85b6a668-3671-11e8-98f1-0d4fe727ee77.png)
There is error. And description about this error on Ukrainian language (but i use English or Russian on server and browser). Also javascript is enabled by default in my browser.
There is a link to this post: https://ussr.win/channel/zlax/?f=&mid=7c0987b360da9fe960cb8710c07ac58ce5aa1aa8ec0e983879403d15a86dbcfd@ussr.win&zid=zlax%40ussr.win

Is it server side problem? How to fix this error?

**Comment by zotlabs** [comment]
I'm guessing you are the server admin. It's possible somebody tried to embed this page that was using the Ukranian language and did not have Javascript enabled and Hubzilla cached the result. Currently we cache these entries forever to avoid an expensive network fetch whenever you view your stream. We may require a cache timeout or a way to over-ride this.

**Comment by zlaxy** [comment]
I inspect this embed element:
```
<span class="oembed video"><a href="https://www.youtube.com/watch?v=Ukj6PNlihPA" onclick="this.innerHTML=Base64.decode('PGlmcmFtZSAgc2Nyb2xsaW5nPSJubyIgaGVpZ2h0PSIzOTkiIHdpZHRoPSI0NjUiIHNyYz0iaHR0cHM6Ly91c3NyLndpbi9vZW1iZWQvYUhSMGNITTZMeTkzZDNjdWVXOTFkSFZpWlM1amIyMHZkMkYwWTJnX2RqMVZhMm8yVUU1c2FXaFFRUSIgYWxsb3dmdWxsc2NyZWVuIGZyYW1lYm9yZGVyPSJubyIgPkVtYmVkZGVkIGNvbnRlbnQ8L2lmcmFtZT4='); return false;" style="float:left; margin: 1em; position: relative;">
	<img width="160" height="120" src="https://i.ytimg.com/vi/Ukj6PNlihPA/hqdefault.jpg">
	<div style="position: absolute; top: 0px; left: 0px; width: ; height: ; background: url(https://ussr.win/images/icons/48/play.png) no-repeat center center;"></div>
</a>
<br><br><a href="https://www.youtube.com/watch?v=Ukj6PNlihPA" rel="oembed">Hencoop space ship door</a><br> by zlaxyi on YouTube<br style="clear:left"></span>
```
Decoded Base64 block is:
`<iframe  scrolling="no" height="399" width="465" src="https://ussr.win/oembed/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1Va2o2UE5saWhQQQ" allowfullscreen frameborder="no" >Embedded content</iframe>`

https://ussr.win/oembed/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1Va2o2UE5saWhQQQ - this link send Ukrainian error. Is it cached link by Hubzilla?

Is it possible to add option for encode original (non cached) links to youtube videos in Base64 block?
Or why this /oembed/ links doesn't work properly on my server? Is it possible to trace the cause causing this problem?
Does the PHP code form this page? Could you specify the part of the code that is responsible for this?

Thanks!

**Comment by zlaxy** [comment]
I compared the contents of this embedded link generated on my server and generated on your server (in the video with the song of Miles Davis):
https://ussr.win/oembed/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1Va2o2UE5saWhQQQ :
```
<html><head><base target="_blank" rel="nofollow noopener" /></head><body>
<div id="player"></div><div class="player-unavailable"><h1 class="message">Узнікла памылка.</h1><div class="submessage"><a href="http://www.youtube.com/watch?v=Ukj6PNlihPA">Паспрабуйце паглядзець гэта відэа на дамене www.youtube.com</a> ці ўключыце JavaScript, калі ён выключаны ў вашым браўзеры.</div></div></body></html>
```
https://macgirvin.com/oembed/aHR0cHM6Ly95b3V0dWJlLmNvbS93YXRjaD92PV9ESDQ2UXlLMmN3 :
`<html><head><base target="_blank" rel="nofollow noopener" /></head><body><iframe width="425" height="319" src="https://www.youtube.com/embed/_DH46QyK2cw?feature=oembed" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></body></html>`

If i understand correctly, it is Hubzilla returns the errorpage, because during forming this simple page with embedded code behaves like a browser, but does not allowed Java-script for that.

**Comment by zotlabs** [comment]
So then the question is why this works for other hubzilla sites and not for yours. I think it is a cache problem. The way to find out would be to embed a random Youtube video that you've never seen before. If that works correctly, there is a cache issue. If that doesn't work correctly, it is possibly something misconfigured on your server, but I don't know what it is since this has been working perfectly for a number of years now. 

If it is a cache issue, you can use an SQL editor to 

```
delete * from cache;
```

This table only holds embedded content. so you might see delays the first time you view these embeds but then they should go back to normal speed once they've been refetched.

**Comment by zlaxy** [comment]
Delete everything from cache table solved this problem, thanks!
https://ussr.win/oembed/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1Va2o2UE5saWhQQQ - works fine now
