### ISSUE TITLE
Enhancement request:  allow events more than 5 years in the future

### ISSUE THREAD

**Issue by crasch** [redmatrix/hubzilla#1042]
I tried to enter an event for my 45th birthday party (more than 5 years from now), and the events calendar won't allow me to enter it.  Seems to max out at 5 years out.

**Comment by crasch** [comment]
When type in the date/time directly, and press tab/enter, the field is automatically adjusted to 5 years out (even if I typed in a date that further out). 

Ah, I see what the problem is.  If you don't type explicitly type the hours:minutes, then it autofills five years out.  For example, this is what I see after I type in 2018-08-01 into each field. 

https://imgur.com/a/9Jcf5

**Comment by zotlabs** [comment]
I think that's because tab and enter are trapped by the javascript picker - hence future limited. Just type in the datetime you want and move your pointer to the next field without using tab or enter

**Comment by crasch** [comment]
Okay, thanks!
