### ISSUE TITLE
Chatroom set to be expire messages after a week; all messages removed earlier than that

### ISSUE THREAD

**Issue by crasch** [redmatrix/hubzilla#1043]
I set chatroom messages in my "Hubzilla newbie chat" room to expire after about a week.  However, they seem to have all disappeared well before then.  Here's the chatroom in question: 

https://gerzilla.de/chat/crasch/22

**Comment by git-marijus** [comment]
The expiration for the chat in question is set to 9000 minutes (about 6 days). I did some testing in the mentioned chatroom and the expiration seems to work as expected. The initial testpost was not visible today anymore (after 6days). The post from the day after is still there (after 5 days).

Not sure what could have caused the content to expire before the limit for @crasch

**Comment by catgun** [comment]
I see your chat posts, Marijus.  Thanks for checking.  Perhaps they got deleted during a software upgrade?
