### ISSUE TITLE
Link /pubsites when hub is set to registration by invitation only

### ISSUE THREAD

**Issue by tluther** [redmatrix/hubzilla#1045]
When a hub is set to registration by invitation only, it should provide a link to /pubsites as it does when closed for new registrations.

**Comment by zotlabs** [comment]
Without any further guidance or alternative suggestions I think this has to be marked invalid. We can't redirect the register link and still accept invitation registrations.

**Comment by tluther** [comment]
No, the registration link cannot link to pubsites, that's clear. I meant merely "if invitation-only or no registrantion then show link to pubsites"

**Comment by elvecio** [comment]
I understand what you mean. something similar happened with a friend of mine. He arrived in elsmussols hub opening a channel page, and he could not go on, he did not find directions, nothing. has been stuck in a site that only accepts invitations, but does not indicate the way to get to other sites with the same software. Something is missing to indicate to the newcomer on the site to take the right direction.
