### ISSUE TITLE
Public Stream notifications are displayed for unauthenticated users

### ISSUE THREAD

**Issue by ghost** [redmatrix/hubzilla#1050]
**Steps to reproduce:**
1. Activate "Import Public Streams"
2. Deactivate "Allow anybody on the internet to access the Public streams"
3. Visit the Hubzilla instance without login

**Current behaviour:**
You will see notifications about the public stream.

**Expected behaviour:**
No notifications about the public stream for unauthenticated users.

I would really like to implement the fix for this (should be an easy modificatino in the notifications widget), one more question:
Is it intended when only activating "Site only Public Streams" that I cannot see the "Unseen public activity" setting in my channel settings and that there are no notifications about the public stream?

**Comment by git-marijus** [comment]
The option to only allow authenticated channels to view the public stream was recently introduced and it seems the change is not reflected in the notifications.

> Is it intended when only activating "Site only Public Streams" that I cannot see the "Unseen public activity" setting in my channel settings and that there are no notifications about the public stream?

Nope. This setting was also recently implemented and the "Unseen public activity" setting and notifications should of course be visible in this case.

Thanks for looking into this.

**Comment by zotlabs** [comment]
red f2078b2
