### ISSUE TITLE
can’t follow mastodon accounts

### ISSUE THREAD

**Issue by inredmood** [redmatrix/hubzilla#1074]
Hi,

Most of my attempts to follow some mastodon accounts failed, while it works correctly with all the diaspora’s accounts I tried.

I tried to type accounts like this: foobar@foo.bar
then I tried: [activitypub]foobar@foo.bar
and then: [ostatus]foobar@foo.bar

It worked for only one account so far: framasoft@framapiaf.org
But it didn’t for another one from the same instance: datagueule@framapiaf.org
And it didn’t work either for some accounts of other instances.

I also checked that I had the ActivityPub protocol enabled in my settings.

Do you have any idea that would help ?
Thanks

**Comment by zotlabs** [comment]
The ActivityPub uses urls for profile addresses, not webfinger addresses. So try 

https://framapiaf.org/users/framasoft 
or 
[activitypub]http://framapiaf.org/users/framasoft

You may have actually connected over OStatus to framasoft. I don't remember offhand if Mastodon uses 'users' or 'user' singular in their URL, but I vaguely recall it being plural. And Mastodon allows webfinger but the protocol doesn't so we use full URLs because that's what the protocol requires.

**Comment by BOETDO** [comment]
I just add my comment here but I think, we are looking at a Mastodon problem. I can "connect" to my Mastodon profile using the format Mike described, but I never received any of my posts on Mastodon. Neither can I "follow" my Hubzilla account from Mastodon (nevermind what format of the profile "address". My Hubzilla out-queue shows dozens of entries which apparently can't be delivered... 

```
11 | https://mastodonten.de/inbox | 0
10 | https://mastodon.social/inbox | 0
2 | https://mastodonten.de/users/boet/inbox | 0

```
So I guess, the process is hanging on the Mastodon end of the communicatins.
But - honestly -  I have no clue... just wild guessing.

Might be worth opening an issue on the mastodon git.

**Comment by git-marijus** [comment]
To follow a hubzilla channel back from mastodon you must use the follow mechanism from inside mastodon. The remote follow functionality does not work since mastodon does not allow URLs at this place but only a webfinger address.

**Comment by git-marijus** [comment]
Adding mastodon contacts with webfinger address has been added to the code. This has also fixed the remote follow issue. Closing.

**Comment by inredmood** [comment]
Great ! Thank you very much.
