### ISSUE TITLE
German language issue in dev

### ISSUE THREAD

**Issue by hfroese** [redmatrix/hubzilla#1075]
After last pull this afternoon, there is a German language issue in system notifications:

![20180413-1638](https://user-images.githubusercontent.com/1968490/38741203-aa69b42a-3f39-11e8-8f4a-6787f1883fd7.jpg)

**Comment by git-marijus** [comment]
This is related to the changes for #1070
It requires new translations...

**Comment by HappyPony** [comment]
@git-marijus 
> It requires new translations...

Is it correct, that is need new translations forenglish version of Hubzilla?

= german =
Verstehe ich es richtig, dass Hubzilla noch keine englische Version dieser Benachrichtigungen hat? Bin g'rade unsicher, ob das Verhalten - s. unten -, das ich beobachte auf den Fehler #1075 zurückzuführen ist. 

Und zwar sind englische und deutsche Texte in den Benachrichtigungen gemischt. Wichtig ist dabei m.E. dass ich Englisch als Standardsprache https://hub.libranet.de/lang in Hubzilla (was eigentlich ausreichen sollte), definiert habe. Und im im Browser ist englisch auch als Standardsprache definiert. Genauso wichtig ist, dass ich dieses Verhalten in einem jungfräulichen Firefox-Profil nachvollzogen habe.

Firefox-Version 59.0.2 (64-bit) Hubzilla Version 3.2.2

![language](https://user-images.githubusercontent.com/3226308/38764900-0c1535ea-3fb8-11e8-9d2a-15a44c09c1e1.png)

**Comment by sasiflo** [comment]
No, translation is needed for the german version. What you see seems to be a bug. There should'nt be german translations mixed in when you requested the english version.

**Comment by poVoq** [comment]
By the way: "Cards" is translated to "Karten" in German. Which while technically not incorrect, is confusing has "Karten" is more commonly used for maps. I would suggest to change it to "Kärtchen".

**Comment by git-marijus** [comment]
Notices are a special case. They are saved in the language you used when you received the item. Changing the language later will not translate the notice.
