### ISSUE TITLE
Best Instance for federated support and RSS feeds?

### ISSUE THREAD

**Issue by Danie10** [redmatrix/hubzilla#1077]
Hi, I'm quite new to Hubzilla having been on Diaspora and then Friendica and now Hubzilla. I've tried three instances on Hubzilla but am finding limited support for federation with Diaspora, Mastodon and Twitter (one had Twitter but it was not activated properly).  I also post once and use an RSS feed to replicate posts to the networks I'm active on, and I manage all responses from inside that network.

I see Hubzilla definitely has this capability but I gather why I'm not always finding it in the settings is the instance owner may not have activated everything.

Any suggestions on an instance to try (that is open for registrations) that may have most features enabled and ready to use?  So far I'm really liking what I see and thinkHubzilla will be my new home, if I can just find a feature enabled instance.

**Comment by git-marijus** [comment]
Hubzilla does not federate with twitter. There is only a plugin to crosspost to twitter.
https://hub.vilarejo.pro.br seems to have all the bits you need enabled.

**Comment by Danie10** [comment]
Thanks @git-marijus a very good suggestion. Yes a few extra themes there too and I have the RSS going etc. Think I'll close this then as it is working well.
