### ISSUE TITLE
Can't send comment via network stream

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1081]
When i try to comment message in my network stream (myserver.com/network), comment saves only on my server and going to the queue:
![2018-04-17-161138_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38871634-1618aa82-425a-11e8-9f2e-866dee5e5425.png)
(there: loadaverage - GNU Social, dacha.xmpp - Hubzilla)
Commenting via friends hub works fine.
[there a log during commenting](https://paste.ussr.win/p6c1dfa1l)
Why do the messages get in the queue and do not go any further? How can I fix this?

**Comment by git-marijus** [comment]
If items can't be delivered we put them in the queue and try to deliver them for 3 days. After this period we give up. loadeverage.org and dacha.xmpp.moe both seem down atm. Hence items are in the queue for those sites.

**Comment by zlaxy** [comment]
But both not down, you could check it for yourself:
https://dacha.xmpp.moe/post
https://loadaverage.org/main/salmon/user/124
I inspected the log - and did not even find an attempt to send messages. Can you tell me specifically - what parameters and add-ons should be included for this?
Why does the log do not have messages about trying to connect to other servers?

**Comment by git-marijus** [comment]
They were both down when i wrote my comment. The queue delivery is invoked via the cronjob.

**Comment by XRevan86** [comment]
@git-marijus, [loadaverage.org](loadaverage.org) wasn't down then. 
> loadeverage.org and dacha.xmpp.moe both seem down atm

Could it be the typo as in here?

**Comment by zlaxy** [comment]
@git-marijus thank you for the information, i think i understood what the problem is.
Please, tell me how to clear the queue most quickly?

**Comment by git-marijus** [comment]
> Could it be the typo as in here?
Possibly

@zlaxy no need to intervent. It will take care of itself.

**Comment by zlaxy** [comment]
@git-marijus i need to clear current queue (there is few test comments, which i prefer to delete before crontab start to work correctly). is it possible to do with any script from /util/ folder?
Or do i have to manually delete data from the database for this?

**Comment by git-marijus** [comment]
If you just need to get rid of them, you can truncate the outq table.

**Comment by zlaxy** [comment]
@git-marijus thanks, queues now fly away normally.
Problem was in my crontab entry, it was deafult:
`*/10 * * * *    cd /home/user/public_html; /usr/bin/php Zotlabs/Daemon/Master.php Cron`
but it returns:
```
System Unavailable
Apologies but this site is unavailable at the moment. Please try again later.
```
Because my `/usr/bin/php` is symlink to php7.0. I changed crontab entry to:
`*/10 * * * *    cd /home/user/public_html; /usr/bin/php5 Zotlabs/Daemon/Master.php Cron`
and everything worked well.

**Comment by zlaxy** [comment]
@git-marijus, my configuration:
`/usr/bin/php` is link to `/etc/alternatives/php`, but `/etc/alternatives/php` is link to `/usr/bin/php7.0`.
Running hubzilla scripts directly returns:
```
# util/config
System Unavailable
```
Running hubzilla scripts via php5:
```
# /usr/bin/php5 util/config
config[system][allowed_themes] = redbasic
...
```
 - works fine.
And running hubzilla scripts via php7.0:
```
# /usr/bin/php7.0 util/config
System Unavailable
```
 - fails.

Also i tried various values of `php_path` variable in .htconfig.php, and setting php5 finally:
`App::$config['system']['php_path'] = '/usr/bin/php5';`
With `/usr/bin/php7.0` php7.0 hubzilla scripts doesn't work too on my configuration.

**Comment by git-marijus** [comment]
Do you have a seperate ini file for PHP7? You might need to enable some modules there...

**Comment by zlaxy** [comment]
@git-marijus Yes, i have. What modules may be needed, tell me please.
