### ISSUE TITLE
No invitation code generated

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#109]
When setting the site to invitation only:
````bash
util/config system invitation_only 1
````
The register form is as expected asking for an invitation code, but when you want to sent out invitations with hub.tld/invite, there is no invitation code in there, also not in the resulting email.

**Comment by jeroenpraat** [comment]
So I tried to debug mod/invite.php a bit. If I see it correctly the invitation code is generated [from line 52 to 60](https://github.com/redmatrix/hubzilla/blob/0cb5f009b483ff570ded4570bb45023573531494/mod/invite.php#L53-L60). On [line 134](https://github.com/redmatrix/hubzilla/blob/0cb5f009b483ff570ded4570bb45023573531494/mod/invite.php#L134) the invitation code should be printed with $invite_code.

What goes wrong? 
- It looks like line 53-60 is never processed. 
- When I put this as a test on [line 126](https://github.com/redmatrix/hubzilla/blob/0cb5f009b483ff570ded4570bb45023573531494/mod/invite.php#L126)  (before $o = replace_macros....):
````php
$invite_code = autoname(8) . rand(1000,9999);
			$r = q("INSERT INTO `register` (`hash`,`created`) VALUES ('%s', '%s') ",
				dbesc($code),
				dbesc(datetime_convert())
			);
````
It prints the invitation code (I had to change srand to rand, cause srand didn't work, rand did) and it stores the code in the register table.

- I can now use that code on the register page! But after submitting the register form the page goes blank. Maybe this has to do with my test, I don't know.

So it seems that generating of the invitation code works and the codes are stored in the register table, but the part of the code that should do this, is never executed. Using the invitation code on the register page works, but after submitting the page goes white (what maybe has to do with my test).

Hopefully this can help you @redmatrix.

**Comment by jeroenpraat** [comment]
@redmatrix I absolutely don't want to nag, so sorry if it sounds like that, but is there any change this will be fixed before 1.0? I really like to use this feature for my hub.

**Comment by kenrestivo** [comment]
@jeroenpraat If you want to get more aggressive with this, make a patch with your change, submit a pull request. If @redmatrix doesn't have time to merge it-- and if you've tested it enough to be confident that it doesn't break anything-- then I will.

**Comment by jeroenpraat** [comment]
@kenrestivo But I don't have a patch, cause I'm not a programmer. It is just a bug I like to be solved as a hub admin that likes to use this (unfortunately broken) feature.

**Comment by kenrestivo** [comment]
Just concurring;  that was a legit bug you just fixed: [srand](http://php.net/manual/en/function.srand.php) was not the correct call, it just seeds the rand generator and doesn't actually put out any numbers. [rand](http://php.net/manual/en/function.rand.php) is correct.

So if you're up for doing the fork, fix, test, pull-request dance, someone will merge it in.

**Comment by jeroenpraat** [comment]
Yes, but that doesn't fix the broken feature. The bug can be split in 2 parts:

1. the invitation code is never generated, cause the part of the code where it should be generated is never executed.
2. even when the invitation code is generated and when used on the register page, a white page appears after submitting the registration.

**Comment by kenrestivo** [comment]
I misread your comment then.  I made the srand to rand change in 5217d89, because it's obviously wrong and needed fixed. 

As for the rest of it, I don't know and I don't have time to deal with it at the moment. Maybe git pull and retest?

You're getting quite proficient at debugging. You'l be coding soon enough :)

**Comment by kenrestivo** [comment]
@jeroenpraat  As for the white screen, look in /var/log/apache2/error.log or wherever your system stores log files, and paste in the PHP stack trace. That should nail down exactly what is crashing and why.

**Comment by jeroenpraat** [comment]
@kenrestivo @redmatrix I've come very far, but I'm stuck. I've fixed mod/invite.php (just did a commit), but I'm stuck on include/account.php. I have the following error in php.out:

PHP Fatal error:  Call to undefined function results() in /var/www/hubzilla/include/account.php on line 70

This is the offending part:
````php
		if(! results($r)) {
			$result['message'] .= t('Invitation could not be verified.') . EOL;
		}
````

When I remove this, I can use any invite code and there is no white screen, but that's not what we want. I understand it wants to check if the query gave any results. 

"results" doesn't seem to be a PHP function, so I searched the Internet and I changed it to this:

````php
		if(mysqli_num_rows($r)==0) {
			$result['message'] .= t('Invitation could not be verified.') . EOL;
		}
```` 

This gave no errors, but whatever I do (good or wrong $invite_code), I receive the 'Invitation could not be verified.' message. 

Hopefully someone can help me with this?

**Comment by kenrestivo** [comment]
Looks like you've caught yet another bona-fide bug in the wild! Thanks!

Your fix looks reasonable to me. But  you'd have to look at the actual query to see why it isn't returning anything. Trace level Hubzilla log? Maybe run the query in MySQL directly and see what it comes up with.

This one: 
https://github.com/redmatrix/hubzilla/blob/master/include/account.php#L69

By the way, three backticks (`) not four for syntax hightlighing.  And I find it more useful to include a link to the source rather than quote it, so that people can follow the link and see the context.

**Comment by kenrestivo** [comment]
Also, hint: if the hash searched for in that query, isn't in the database, look around for where it should have been inserted, and try to puzzle out why it didn't (it may be another bug you can spot, you've got a good track record so far).

**Comment by redmatrix** [comment]
results() was a friendica function from years ago. You should just check for 

if(! $r) {
  // nothing was returned from the query
}

**Comment by jeroenpraat** [comment]
@redmatrix That's it! Thank you! Now it works.

The invite code is not removed from the database after it is successfully used, but the question is if we want that, cause I can think of an use case that the invite code is used by more than one person. On the other hand, an invite code is mostly given to one person, like it's their personal code. A hidden config for this will probably be a good idea, so the site admin can decide about the behaviour. But for now I'm happy and close the issue.

Thanks to you too @kenrestivo .

**Comment by redmatrix** [comment]
They may get cleaned up in an unrelated module - iirc there are a couple of places that clean out that table.

**Comment by jeroenpraat** [comment]
Good to know. Thanks.
