### ISSUE TITLE
setting system language is not working

### ISSUE THREAD

**Issue by berezowski** [redmatrix/hubzilla#1103]
https://hub.berezowski.de/photos/hubert/image/701fc4d360b0d1ada0984963969530e0ea53556a59335c376e74bba085fff0c0

**Comment by zotlabs** [comment]
The browser language always has priority. System language is used as a fallback if the preferred browser language(s) isn't(aren't) available.

**Comment by berezowski** [comment]
i figured it out, the language switcher was not enabled by default. '/lang' was the page i was looking for.

Sorry for opening an issue, i got pretty frustrated not being able to switch the language, and not finding anything about that in the documentation.
