### ISSUE TITLE
Setup a scheduled task for the poller - INSTALL.txt

### ISSUE THREAD

**Issue by smth** [redmatrix/hubzilla#1122]
Going through the Hubzilla setup for the first time, I see the below message.

> IMPORTANT: You will need to [manually] setup a scheduled task for the poller.
Please see the file "install/INSTALL.txt".

I refer to `install/INSTALL.txt`, expecting to see an explanation of what this means, and instructions on how to do it. Neither seem to be there.

**Comment by elmussol** [comment]
Section 8 of /yourwebroot/install/INSTALL.txt deals with this.

**Comment by smth** [comment]
OK, so "setup a scheduled task for the poller" == [this](https://github.com/redmatrix/hubzilla/blob/master/install/INSTALL.txt#L222-L242)?

**Comment by elmussol** [comment]
That's it.
