### ISSUE TITLE
Sync non-default profile photo changes to clones

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#113]
At present we sync only the default profile photo to clones if we change the photo.
If we change a non-default profile photo it does not sync with clones.

**Comment by redmatrix** [comment]
It appears we aren't syncing on some change events, but if you make any changes to the profile content (besides the photo), the profile and its photo will be pushed out. So that's a workaround until all the places where any subtle profile changes are made are trapped and sent to build_sync_packet()
