### ISSUE TITLE
Notifier Array key exist

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#114]
PHP Stack trace:
PHP   1. {main}() /var/www/server/include/notifier.php:0
PHP   2. notifier_run() /var/www/server/include/notifier.php:714
PHP   3. array_key_exists() /var/www/server/include/notifier.php:678
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/server/include/notifier.php on line 678

**Comment by redmatrix** [comment]
Should be fixed in b62614b , even though it isn't listed in the commit message.
