### ISSUE TITLE
Unable to play embedded Youtube videoes

### ISSUE THREAD

**Issue by steveh138** [redmatrix/hubzilla#1147]
Embedded Youtube videos are unable to play and display an error asking for Javascript to be enabled in the browser. This can be verified on the Hubzilla demo page. https://demo.hubzilla.org/

To reproduce create a new post with the following content

`[embed]https://www.youtube.com/watch?v=yZeiQT0yDj0[/embed]`

When clicking on the image the video won't play. Instead it displays an error saying that the browser needs javascript enabled. Here is a copy of the text displayed on the demo page which is in German.

Ein Fehler ist aufgetreten.
Schau dir dieses Video auf www.youtube.com an oder aktiviere JavaScript, falls es in deinem Browser deaktiviert sein sollte.

**Comment by steveh138** [comment]
Doing another search I saw there was a closed issue for this. Since this is also happening on the public demo site my assumption is it's a larger issue than clearing the cache, but once I get home from work I'll give this a try.

I do have javascript enabled on all browsers I'm attempting this on.

**Comment by elvecio** [comment]
I don't know  about https://demo.hubzilla.org/
but, in general, you (the hub) need a plugin to make this work
, so you enable or ask the administrator to enable.
https://github.com/redmatrix/hubzilla-addons/tree/master/std_embeds

**Comment by steveh138** [comment]
@elvecio I will check that as well once I get home from work. Thank you! :)

**Comment by steveh138** [comment]
So I did turn on the plugin, but it was after I tried testing a youtube video. Clearing the cache fixed this issue. Thank you for the help.
