### ISSUE TITLE
Directory disappeared - version 2015-11-01.1203H

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#115]
I just pulled 2015-11-01.1203H and now I cannot see any channels on the Directory page, not local nor global.

**Comment by royalterra** [comment]
I found some directory servers no work the server is shut-down like zotid.net try this go to your install folder and execute:
util/config system https://blablanet.com
after look again if now show the directory page

**Comment by git-marijus** [comment]
If you can't wait: util/config system directory_server https://hubzilla.site
or any other dir server of your choice.

If you can wait - it will repair itself...

**Comment by HaakonME** [comment]
Changed to https://blablanet.com - fixed.
