### ISSUE TITLE
Mention issues when markdown post feature enabled

### ISSUE THREAD

**Issue by hfroese** [redmatrix/hubzilla#1166]
Mentions to diaspora don't work anymore:

![20180508-1226](https://user-images.githubusercontent.com/1968490/39777403-c96b0fb2-5303-11e8-81a6-17a9baef48df.jpg)

Looks strange and the link leads to my hubzilla instance

**Comment by git-marijus** [comment]
This only happens if the markdown post feature is enabled.

**Comment by git-marijus** [comment]
It turns out that regarding diaspora it's just this one contact (in the image) that renders that way. Activitypub contacts render wrong too. They look like that: `@{https://mastodon.tld/users/profile}`

**Comment by zotlabs** [comment]
I'll have this sorted in a bit.

**Comment by hfroese** [comment]
Works perfect again. Thanks 👍
