### ISSUE TITLE
Feature request: Exclude some content by tags from public stream

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1169]
Please add possibility to exclude some content by tags from public stream for admins.
It's for nsfw tagged posts in public stream.

**Comment by zlaxy** [comment]
@git-marijus Hello! I tried to do `git cherry-pick 721496f9220fa59059f90d16d3b3fb19337b2f16` but it falsed because conflicts... I'm thinking about switching to dev branch completely on my hub.
Please tell me, is it safe for the database? Could i then switch to master branch without losing data later?

**Comment by zlaxy** [comment]
@git-marijus @zotlabs I switched to dev branch.
I see `Do not import Public stream posts with this text` textfiled in admin menu, but it doesn't work.
After adding some text (`#nsfw` or just `nsfw`) and pressing submit, this textfield is cleared, all my content is deleted.

**Comment by zlaxy** [comment]
@git-marijus @zotlabs With last commits textfiled `Do not import Public stream posts with this text` in admin menu works fine, it saves results:
![2018-05-20-094937_1280x800_scrot](https://user-images.githubusercontent.com/19224533/40276475-e00bdaf8-5c13-11e8-9654-87d7acdf42ef.png)
But this functionality doesn't work at all, NSFW posts doesn't excludes from public stream:
![2018-05-20-095152_1280x800_scrot](https://user-images.githubusercontent.com/19224533/40276473-dc15e560-5c13-11e8-8b5d-46191a647a68.png)

**Comment by zotlabs** [comment]
This post looks as if it came from Diaspora. Make sure you pull updates to hubzilla-addons as well as hubzilla as those posts are filtered within the Diaspora protocol plugin. 

Also if you enable 'safe mode' on your /directory page you will be spared the adult tags on your pubstream page (in the 'Trending' widget). I believe this is the default condition.

**Comment by zotlabs** [comment]
I've just tested and the filter is working perfectly on my system for messages originating on zot and Diaspora. I have not yet tested OStatus and ActivityPub but I see no reason why they shouldn't work as well; and these posts are obviously coming from Diaspora. It's clear there is something wrong but I can't figure out what it is. For me the feature is working perfectly.

**Comment by zotlabs** [comment]
Just curious - you updated the addons but did you also change branch to 'dev' in the addons directory? I'm thinking that the addons might still be on master branch which could potentially be the reason why it is working for me but not for you.

**Comment by zlaxy** [comment]
Thanks, it was my issue - i didn't change branch to 'dev' in the addons directory... Now i do it, and it looks fine. Already 15 minutes are not imported new nsfw-posts, looks like everything fine with this issue. But trending cloud highlights these tags because of old posts highlights these tags:
![2018-05-22-095336_1280x800_scrot](https://user-images.githubusercontent.com/19224533/40346702-52c64fa4-5da6-11e8-94ea-70afd4610b50.png)
Is it possible to quickly clear all imported stream posts in order to start forming this cloud from the very beginning?

ps Also with dev branch of addons there cavatars in public stream now, it's great. Thanks again!

**Comment by zlaxy** [comment]
About clear all imported stream posts: https://github.com/redmatrix/hubzilla/issues/1208#issuecomment-394154998

Excluding some content by tags from public stream feature works fine in dev branch now. Thanks!
