### ISSUE TITLE
Feature request: sticky "New Network Activity" area

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1189]
It's very annoying after open new comment in big thread - have to return to the very top of the page to see other activities.
![2018-05-23-202828_1280x800_scrot](https://user-images.githubusercontent.com/19224533/40441646-4d38e8ba-5eca-11e8-9211-d04d8f9173a1.png)
I suggest to "stick" this area in default theme, or better - make this feature customizable in Display Settings menu.
Now for my custom theme, i implemented it through adding:
```
#notifications {
    position: fixed;
}
```
to `/css/style.css` of the theme.

**Comment by git-marijus** [comment]
Not sure if i understand that request right.
In general the whole notifications area is sticky. If you don't see that, that is probably a bug...
What browser and theme are you using?

**Comment by git-marijus** [comment]
I see there are some custom changes at your site. That is probably the reason why it does not work as intended.

**Comment by zlaxy** [comment]
@git-marijus Thank you for pointing out, it was my mistake, i forgot to rename .js file in the custom theme, because of this the script did not work, but there were no errors in the console... After renaming everything works fine.
