### ISSUE TITLE
reduce disk usage for MySQL

### ISSUE THREAD

**Issue by prolibre** [redmatrix/hubzilla#1192]
Hello,

I read in FAQ : "_If I recall there's a separate config for expiring purely "public content" that is imported/shared from other sites via **/public** or **the "discover" tab**. These I wouldn't keep around for more than about a week._" (https://github.com/redmatrix/hubzilla/wiki/Frequently-Asked-Questions#how-do-i-reduce-disk-usage-for-mysql-database-in-hubzilla)

is that possible? if so how?

thanks

**Comment by prolibre** [comment]
thanks @zotlabs, and good :-) 

But you confirm me that this parameter is different from "Expiration period in days for imported (grid/network) content" in admin / site? (which I set for 30 days)

**Comment by zotlabs** [comment]
They are different settings, but partially inter-related. The site expiration applies to everything - including the public stream; but you can set the public stream expiration to something less and expire it at a faster rate. This is complicated to explain so I think eventually we'll find a simpler mechanism, but that's how it works today.

**Comment by prolibre** [comment]
@zotlabs Thank you very much
