### ISSUE TITLE
Access denied for user

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/hubzilla#12]
mama@zeuza:/media/Disco160/www/hubzilla.ml$ cd /media/Disco160/www/hubzilla.ml; php include/poller.php
PHP Warning:  mysqli::mysqli(): (42000/1044): Access denied for user 'hubzillaml'@'%' to database 'hubzillaml' in /media/Disco160/www/hubzilla.ml/include/dba/dba_mysqli.php on line 11
mama@zeuza:/media/Disco160/www/hubzilla.ml$ PHP Warning:  mysqli::mysqli(): (42000/1044): Access denied for user 'hubzillaml'@'%' to database 'hubzillaml' in /media/Disco160/www/hubzilla.ml/include/dba/dba_mysqli.php on line 11
PHP Warning:  mysqli::mysqli(): (42000/1044): Access denied for user 'hubzillaml'@'%' to database 'hubzillaml' in /media/Disco160/www/hubzilla.ml/include/dba/dba_mysqli.php on line 11
PHP Warning:  mysqli::mysqli(): (42000/1044): Access denied for user 'hubzillaml'@'%' to database 'hubzillaml' in /media/Disco160/www/hubzilla.ml/include/dba/dba_mysqli.php on line 11

**Comment by redmatrix** [comment]
Permissions to database objects are defined in and enforced by the database.
