### ISSUE TITLE
Feature request: public stream manual cleaning

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1208]
I set `util/config system.sys_expire_days 1`, also set `Expiration period in days for imported (grid/network) content` and `Do not expire any posts which have comments less than this many days ago` to 1. But my old public stream posts continue to accumulate... I check cron and tried run `Zotlabs/Daemon/Master.php Cron` manually - but old public stream items was not reduced.
I ask on forum and matrix chat - it was recommended to check `Master::Summon(array('Cron_daily'));` and `Master::Summon(array('Expire'));` through the `logger`. But unfortunately i still do not have the opportunity to do similar searches in the coming weeks.

So i ask to add feature for cleaning database from unimportant public stream items (not related to the hub). It would be better if it will a function of one of the scripts in the `util/` directory, to be able to use this function at the server level, for example, if the allocated space limit for the virtual host is exceeded.

Thank you in advance.

**Comment by zotlabs** [comment]
If you ran for quite a while before turning on expiration, it's possible that expire is using up all the memory available and terminating. We limit this to 5000 items at a time to work under these memory issues, but you may have less memory available to PHP than we did our initial test with. 

You can set 

util/config system.expire_limit 1000

which will only expire 1000 items at a time. 

You can run the process any time using

php Zotlabs/Daemon/Master.php Expire

from a command line. It normally takes 10-15 seconds to run before returning the command prompt. If it runs for more than 5 minutes, it's likely that memory was exhausted and you may need to reduce the limit of items processed at one time. You can perfomr this manual step and even put it in a shell script if you wish to automate it. Once the backlog has caught up, it should return instantly when you run it.

**Comment by zlaxy** [comment]
@zotlabs Thank you for answer, Mike. I tried to do `Master.php Expire` with 500-1000 items (it takes ~10-40 seconds), and check database - table `item` has not decreased by one element... So i tried to run it with all log level, it's result:
```
2018-06-01T12:34:01Z:LOG_DEBUG::Master.php:26:Release: Master: release: Array
(
    [0] => Expire
)

2018-06-01T12:34:01Z:LOG_INFO::Expire.php:35:run: expire: start
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:40:run: site_expire: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: zlax interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: leaks801 interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: monmorancy interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: ruchika interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: sfadsfdsfasf interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: fidankazan interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: leonrony interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: asddsa interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: janis interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: janis6986 interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: testforum interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:67:run: Expire: cccp interval: 1
2018-06-01T12:34:01Z:LOG_INFO::Expire.php:86:run: Expire: sys interval: 1
2018-06-01T12:34:09Z:LOG_INFO::items.php:3658:delete_item_lowlevel: item: 113478 stage: 0 force: 
2018-06-01T12:34:09Z:LOG_INFO::items.php:3658:delete_item_lowlevel: item: 113479 stage: 0 force: 
2018-06-01T12:34:09Z:LOG_INFO::items.php:3658:delete_item_lowlevel: item: 113497 stage: 0 force: 

...

2018-06-01T12:34:51Z:LOG_INFO::items.php:3658:delete_item_lowlevel: item: 114546 stage: 0 force: 
2018-06-01T12:34:51Z:LOG_INFO::items.php:3658:delete_item_lowlevel: item: 114547 stage: 0 force: 
2018-06-01T12:34:51Z:LOG_INFO::items.php:3658:delete_item_lowlevel: item: 114548 stage: 0 force: 
2018-06-01T12:34:51Z:LOG_INFO::Expire.php:91:run: Expire: sys: done
```

I also noticed the items that came to my hub at this time, they all had the following:

```
2018-06-01T12:33:58Z:LOG_INFO:5puiqtcb6fk3208copiskt18t4:items.php:1091:encode_item: encode_item: Array
(
    [type] => activity
    [encoding] => zot
    [id] => 185728

...

    [edited] => 2018-06-01 12:33:40
    [expires] => 0000-00-00 00:00:00
    [commented] => 2018-06-01 12:33:40

```
or
```
2018-06-01T12:33:58Z:LOG_INFO:5puiqtcb6fk3208copiskt18t4:items.php:1901:item_store: item_store: Array
(
    [aid] => 0
    [uid] => 1

...

    [revision] => 0
    [expires] => 0001-01-01 00:00:00
    [commented] => 2018-06-01 12:33:58
```
`[expires] => 0000-00-00 00:00:00` during item_encode and `[expires] => 0001-01-01 00:00:00` during item_store

So i check this table in db itself...and all elements from first to last id has `0001-01-01 00:00:00` value in the `expires` column.

Related parameters of my configuration:
```
# util/config
config[system][db_version] = 1215
config[system][last_expire_day] = 1
config[feature][content_expire] = 1
config[system][active_expire_days] = 1
config[system][sys_expire_days] = 1
config[system][expire_limit] = 800
```

In the `item` table a have 185,555 objects now, and last ID is 185907... Last week i use dev branch.

It seems that for some reason, the parameter `expires` is not set and does not change. What could be the reason?

**Comment by zotlabs** [comment]
Don't worry about the item_expires field - that is for member-initiated expiration of their own posts.

> 2018-06-01T12:34:51Z:LOG_INFO::items.php:3658:delete_item_lowlevel: item: 114546 stage: 0 force

All such items were marked deleted and are now inaccessible. The data content has been nulled. They will be physically removed from the database automatically in about a month. We don't currently have a way to distinguish deleted items that require staging and notification of downstream recipients from those that do not, so we perform the final cleanup the same way for both.

**Comment by zlaxy** [comment]
@zotlabs 

> Don't worry about the item_expires field - that is for member-initiated expiration of their own posts.

I got it.

> All such items were marked deleted and are now inaccessible.

I tried to execute `Master.php Expire` with cycle, after ~100th iteration every step takes less than 1sec. I try to check pubstream - yes, there is no more posts older than 1 day. Thanks, this is solution for part of my problem.
...but database still too large for me (just item table more than 2GB).

> The data content has been nulled. They will be physically removed from the database automatically in about a month.

How this process could be forced to execute?

At the moment, my Hubzilla virtual host has used the allocated limit, and at such rate, the free space in my server will end sooner than a month later. But i do not want to disable the public stream to save space (i plan in a few weeks to announce this hub among my friends, it looks good when the main page shows the public stream from different networks for not logged visitors).

I would like to write a simple cron script that clears deleted records from the database in case the allocated space for the virtual host is exaggerated.
If no such function for physically removing of deleted items is provided, will it be safe to do this at the level of the sql-query with deleting all the rows with `item_deleted == 1`?
(i will not do this regularly, but only in the critical case if the free space ends)

**Comment by zotlabs** [comment]
In an emergency you can delete any item with item_pending_delete = 1

We only keep these longer so that deletes will propagate to feed readers that might poll infrequently.

**Comment by zlaxy** [comment]
@zotlabs Thank you for your help, as a result, i managed to free up my free space and clean database...
It was some iterations of:
`php Zotlabs/Daemon/Master.php Expire`
And after that some iterations  of mysql queries:
`DELETE FROM item WHERE item_deleted = 1 LIMIT 10000;`
and finally:
`OPTIMIZE TABLE item;`

Mike, please, indicate the difference between `item_deleted` and `item_pending_remove`? When does one become another?
