### ISSUE TITLE
Removing specific text from Diaspora post

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#128]
On posts from Diaspora I sometimes receive 'View full size' below large photographs. This is not working, because it gives an empty ZRL:
````
[zrl=]view full size[/zrl]
```` 
It is also not translated to the members language. Anyhow I tried to remove this unneeded string a while ago in include/bb2diaspora.php like this (line 444):
````php
$Text = preg_replace("/\[zrl\=\].*?\[\/zrl\]/is", "", $Text);
````
But now I see it happen again. So I'm lost here. What am I doing wrong?

**Comment by redmatrix** [comment]
include/network.php:scale_external_images()

**Comment by jeroenpraat** [comment]
Yes, I looked there first, but didn't wanted to fiddle with that, because it only seems Diaspora related. These strings (added below) also see okay with me.

````php
$s = str_replace($mtch[0],'[' . $tag . '=' . $new_width . 'x' . $new_height. ']' . $scaled . '[/' . $tag . ']'
							. "\n" . (($include_link) 
								? '[zrl=' . $mtch[2] . ']' . t('view full size') . '[/zrl]' . "\n"
								: ''),$s);
````

**Comment by jeroenpraat** [comment]
And "t('view full size')" is only translated (in Diaspora posts) to the hub's default language and not to the member's language.

**Comment by jeroenpraat** [comment]
Doesn't occur any more AFAIK.
