### ISSUE TITLE
New connections requests don't arrive on other channel

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#145]
*Only tested on hubzilla.nl*

When a member connects to another channel (on the same hub, not tested from hub to hub) , manually (using follow field on connection page) or via that another channel's profile page, the connection request never arrives on that another channel. It never receives a notification and it never arrives on that other connection page under new or all connections.

I tested this with existing and new created channels, bit public forum and public social channels (also from forum to forum, and social to social). I tested it with different channels from one account and I tested it with another newly created account. I have a debug log when trying to connect from my default channel to a forum channel named debugforumbug@hubzilla.nl. Please tell me what you want to know from the log. I can also send it to you @redmatrix personally (it's only 42,6kB).

This is what I did step by step:

1. Created public forum channel B using account X.
2. Connect to channel B using the follow field on the connection page of (social) channel A of account X.
3. Switched to the channel B.
4. \* Clicked on the connections page. Nothing was there. Waited a few minutes nothing there. Waited after the poller run, still nothing.
5. Switched back to channel A.
6. Clicked on the connections page. Channel B is there, but when checking the permissions it is clear that channel A is not (automatically) approved by  channel B.

*Note: When creating channel B as a public social channel there was also no connection request in the nav-bar or via email.

**Comment by jeroenpraat** [comment]
Well, you never believe it. The connection requests arrived a few hours later. That's another issue. So I will close this one.

**Comment by kenrestivo** [comment]
I suspect it might be an API issue. If so, merging this might fix:
https://github.com/redmatrix/hubzilla/pull/144

**Comment by redmatrix** [comment]
The API isn't involved in connection requests

**Comment by redmatrix** [comment]
Couldn't duplicate here -  before applying @kenrestivo API fix. Created a new channel, connected to an existing channel, switched to the existing channel and had a connection request waiting when I got there. Elapsed time, 3 seconds.

**Comment by jeroenpraat** [comment]
Please see #150
