### ISSUE TITLE
Duplicate Post 

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#146]
I observe now few days no only in my channel also in other hubs
A single Post  become duplicate some times more of 2 .
No reason for that or possible Lag with the directories . I can confirm that because around 11 to 1 am UK time the error become more constant and the traffic more slow .
My server have 8 GB Ram and no look have much stress I already check other domains in the seam Apache server . But the HUB or Hubzilla Domain become really more slow in that times .
Possible we need to decide what domains become directory servers because small Hubs setup in very small VPS can't hold high traffic request in pick time.

**Comment by royalterra** [comment]
I observe the error reproduce when there some lag of communication with and other server notifications.
You can click exactly one time but the post show 2 or more times. Others Network have a safety check . if you make a post and you go to post seam text again you get a message you have already posted.
I think the best is just that a safety check of content of last post and if is similar popup a message

**Comment by redmatrix** [comment]
This happens very often with one or two people. Might be a touchy mouse button (this has happened to me before and replacing the mouse solved the problem). I've added a new feature to suppress posts/comments with the same content in less than two minutes. It is enabled by default. If you wish to turn it off visit the extra features page in your settings. 

Also worth mentioning is that it's possibly (though less likely) this could happen as a result of plugin connectors looping. (post from hubzilla to another service which is configured to post to hubzilla).
