### ISSUE TITLE
@mention+ posts to forum walls disappear after editing

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#157]
When posting a wall-to-wall post from a normal channel to a forum channel with @mention+, it is received normal and displayed on the forum's channel page/wall. But when edited by the sender* the post eventually disappears from the forum's channel page/wall. The post is not removed from the senders channel page/wall.

When checking that particular post in the item table in the DB,  item_wall is before editing 1 and after editing 0.

I tried hard to find anomalies in the debug log, but could not find something.

*Note:  From the senders channel or grid, not as the sender on the forum channel > it than gives a top-right-notification that the item can't be edited.

**Comment by redmatrix** [comment]
I think this should be sorted now.

**Comment by jeroenpraat** [comment]
Perfect! Also the issue after *note. Thanks again Master Mike!
