### ISSUE TITLE
Twitter plugin configuration incomplete

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#162]
The Twitter plugin looks like it needs some attention. The configuration for the API keys looks like it was intended to be in the UI, but it's not there, it's only available from the command line.

**Comment by royalterra** [comment]
The Plugin also pull Profile Images with not https from twitter and make the HUB insecure

**Comment by redmatrix** [comment]
This was fixed a couple of days ago

**Comment by kenrestivo** [comment]
It looks like it was, thanks! I'll ask the guys with Twitter/Quitter accounts to retest.

**Comment by kenrestivo** [comment]
I'm moving this to the hubzilla-addons repo, which is where it probably should live, so https://github.com/redmatrix/hubzilla-addons/issues/5

I looked through the code for hubzilla-addons and didn't see any changes to it. I also retested. There still seems not to be any way for admins to add the API key through the UI.
