### ISSUE TITLE
Add sort order to photo album widget

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#163]
Says Mike
```
The sort order (which got edited out) is another example of a ten minute job for somebody with really basic code skills.
```
If there were a "newbie" tag in the project issues on github, this could be tagged with it.

**Comment by kenrestivo** [comment]
I know nothing about photo  albums, but know enough PHP and enough Hubzilla to have been able to trace this down to probably here:
https://github.com/redmatrix/hubzilla/blob/93e5449c0843494c49ae799fa044299ca5cdeb6d/include/widgets.php#L687

Following that trail leads here:

https://github.com/redmatrix/hubzilla/blob/93e5449c0843494c49ae799fa044299ca5cdeb6d/include/photos.php#L465

And, finally, it seems the list of albums comes from here:
https://github.com/redmatrix/hubzilla/blob/93e5449c0843494c49ae799fa044299ca5cdeb6d/include/photos.php#L425

If you're trying to sort them, learning some SQL would let you edit that SELECT query to perhaps sort them. If you're trying to sort the pictures in the album, I don't know where in Hubzilla that's done.

If you already know javascript, PHP is not to hard to learn. SQL is a different beast, but its basics not too hard to learn either.

**Comment by DeadSuperHero** [comment]
Good insights - I don't really do too much beyond HTML/CSS/Commanche at the
moment, but maybe it's time to crack out a good beginner's PHP book.
