### ISSUE TITLE
New users confused by ratings screen after adding a connection.

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#167]
After adding a new connection, users are bewildered by the ratings screen.

Enhancement might be adding a new connection to be an ajax action that doesn't change pages at all.

This could use more user testing.

**Comment by kenrestivo** [comment]
@git-marijus  Intends to take on the connections screens after he's done with events.

**Comment by VSChawathe** [comment]
When I was confused all I wished for was a small tooltip anywhere with 140 character twitter like explanation, because leaving to default 0 for good friend's channel felt awkward.

**Comment by kenrestivo** [comment]
f4e1b2123aed39e3f863ee327b27cb0e7f17520c probably fixes this, but haven't looked yet.

**Comment by royalterra** [comment]
I am more with @kerenstivo simple add user and not change page if a user like to change certain permission for one individual user can look later in users list. And ask provide rattling just connect look not very nice

**Comment by kenrestivo** [comment]
This looks good; thanks @git-marijus for your work. I'm closing this.
