### ISSUE TITLE
Delete button on connections is hidden

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#168]
When editing a connection, the delete button is hidden in a tiny pulldown at the top of the page.

One possible enhancement would be to have a Delete button in the main connections scren next to the Edit button, or to make the Delete more prominent somewhere else on the edit page.

**Comment by git-marijus** [comment]
refurbish the connections page next on my todolist... busy with events atm.

**Comment by kenrestivo** [comment]
Thanks for all you're doing on the events!

**Comment by git-marijus** [comment]
fixed in e2b79c34bc0c1dc5f48295c1cca7261e8cb648fb
