### ISSUE TITLE
Can't connect to mysql through socket, but .htconfig.php is 127.0.0.1

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#174]
```
PHP Warning:  mysqli::mysqli(): (HY000/2002): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /home/src/hubzilla/include/dba/dba_mysqli.php on line 11
PHP Stack trace:
PHP   1. {main}() /home/src/hubzilla/include/deliver.php:0
PHP   2. deliver_run() /home/src/hubzilla/include/deliver.php:176
PHP   3. cli_startup() /home/src/hubzilla/include/deliver.php:9
PHP   4. dba_factory() /home/src/hubzilla/include/cli_startup.php:22
PHP   5. dba_driver->__construct() /home/src/hubzilla/include/dba/dba_driver.php:37
PHP   6. dba_mysqli->connect() /home/src/hubzilla/include/dba/dba_driver.php:117
PHP   7. mysqli->mysqli() /home/src/hubzilla/include/dba/dba_mysqli.php:11
```
but .htconfig.php is:

```php
$db_host = '127.0.0.1';
$db_port = '3306';
$db_user = 'hubzilla';
```

I don't know if this isi causing 404 errors on API calls (maybe because boot.php or something very early on is failing to run due to socket error, thus the whole application is unavailable), but the two might be related.

NB: this is being prompted by heavy load during bulk migrator importer testing.  I'm not sure I could come up with a reproducible test case, but I could try.

**Comment by kenrestivo** [comment]
Also, I'm seeing these too, which are puzzling:

```
PHP Fatal error:  Call to undefined function mysql_connect() in /home/src/hubzilla/include/dba/dba_mysql.php on line 9
PHP Stack trace:
PHP   1. {main}() /home/src/hubzilla/include/deliver.php:0
PHP   2. deliver_run() /home/src/hubzilla/include/deliver.php:176
PHP   3. cli_startup() /home/src/hubzilla/include/deliver.php:9
PHP   4. dba_factory() /home/src/hubzilla/include/cli_startup.php:22
PHP   5. dba_driver->__construct() /home/src/hubzilla/include/dba/dba_driver.php:41
PHP   6. dba_mysql->connect() /home/src/hubzilla/include/dba/dba_driver.php:117
```

**Comment by royalterra** [comment]
uhm look your host is 127.0.0.1       localhost and in my.cnf max number of connections make UP
install mysqltuner is also for centos and so on 
apt-get install mysqltuner
execute mysqltuner and you can see your MYSQL errors and what you need to make UP

I see previously some errors with HUbzilla in MySQL but all disappear using MariaDb . You can simple use apt-get remove for remove your MYSQL (NOT USE --Purge or you will lost your databases) 
Make a copy of my.cnf and remove the Original and Install MariaDb

**Comment by kenrestivo** [comment]
Nevermind, pilot error. File was not saved due to permissions error. Ignore the noise.

**Comment by kenrestivo** [comment]
Ropening this. Indeed the settings are correct. It's possible that mysqli is ignoring 127.0.0.1 and insisting on using local socket instead. If this is the case, fixing this might be worthwhile.

**Comment by kenrestivo** [comment]
Chasing down those line numbers, it seems that mysqli is seeing the $port as null! Thus it thinks it must use sockets. I suspect this is a PHP typecasting problem.

**Comment by royalterra** [comment]
There we are first check sockets :+1: 
In root:
 php -i | fgrep 'mysql.default_socket'

Need to return something like that 
mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock
pdo_mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock

In root terminal execute:
mysql -u root -p -h 127.0.0.1   
they will ask your root mysql password if connect go exit write "quit"

if not connect is a problem in your file my.cnf or /etc/hosts loook there if show 127 .0.0.1 and also to localhost pointing inside /etc/hosts

If connect and you can get 127.0.0.1 The problem usually with php the usual is a problem is your MySQL user host permissions . Simple make sure what ever mysql user you want to use have access to 127.0.0.1 and localhost

You can easy look all that with not command line with webmin anyway.

**Comment by kenrestivo** [comment]
Added to hopefully reduce the noise:

php -i does report
```
mysqli.default_port => 3306 => 3306
```

The lines listed  clearly are executing because either the test for $port is incorrect (maybe it should be is_null()), or for some other reason. Perhaps someone who knows more PHP than I do could actually help fix this bug.

**Comment by royalterra** [comment]
you can show anything in your php.ini any mysql port you like can be setup there  php -i not probe your mysql user connect to localhost or 127.0.0.1:3306

**Comment by kenrestivo** [comment]
Solution was port in .htconfig.php must be an integer not a string. Manually editing that file is frought with danger. However, mysql is still crashing and behaving badly, so this wasn't actually the problem. Closing this in an attempt to shake off the noise.
