### ISSUE TITLE
Only show public forums on /directory not working

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#177]
Toggling 'Public Forums Only' on /directory doesn't do anything. The page does not change. Hubzilla.nl is in secondary directory mode. So I also tried it with hubzilla.site and it had the same issue. 

This is in the logs when switching to 'Public Forums Only':

````
2015-11-19 23:02:09:fbe0o5u9p5o7bqgij7tc35lgv7 directory.php:132:directory_content: mod_directory: URL = https://hubzilla.nl/dirsearch
2015-11-19 23:02:09:fbe0o5u9p5o7bqgij7tc35lgv7 directory.php:183:directory_content: mod_directory: query: https://hubzilla.nl/dirsearch?f=&kw=50&safe=0&pubforums=1&order=date
````

**Comment by royalterra** [comment]
I have also similar issues in one installation and when you show user in this directory only some time show all some time half and other time show none

**Comment by royalterra** [comment]
I go to add something more for that I open a Feature for remove Directory page from no Online Users .
https://mydomain.com/directory
Directory Link in the Login page or Registration Page is scan and attack many times from crawlers and people with Chinese Russian and USA Ips 

i am wondering if they can make any Mysql damages

**Comment by redmatrix** [comment]
@royalterra  Admin -> Site -> Block Public

Anyway, fixed. This affects hubzilla directory servers which were still using an obsolete redmatrix flag in the publicforum query.

**Comment by jeroenpraat** [comment]
Fixed. Thanks Mike.

Now I see some of 4 my forums that don't have a forum flag, but I will check that tomorrow. 2AM here.
