### ISSUE TITLE
Checking for DNS records for IP addresses?

### ISSUE THREAD

**Issue by pztrn** [redmatrix/hubzilla#184]
While trying to install Hubzilla I've encounter this error:

```
Database Connect failed: Cannot locate DNS info for database server '192.168.3.2'
```

So, installer checks for DNS record for thing that actually is an IP address?

**Comment by kenrestivo** [comment]
It does. It's here, it's a bug. https://github.com/redmatrix/hubzilla/blob/master/include/dba/dba_driver.php#L141

**Comment by kenrestivo** [comment]
@pztrn Can you verify that this has been fixed now? If so, can you close the issue? Thanks.
