### ISSUE TITLE
channel RSS feeds do not recognize categories

### ISSUE THREAD

**Issue by AFlowOfCode** [redmatrix/hubzilla#189]
The following URL will display all posts in a channel tagged (or "categorized") as eg featured : 

https://hub.spaz.org/channel/spaz?f=&cat=featured

However the RSS will not sort by category.

https://hub.spaz.org/feed/spaz?f=&cat=featured - This displays the entire RSS feed of the channel, when it should only display a feed of the specified category. There should be a mechanism to sort the feed by categories.

It appears that nothing beyond /feed/channel is recognized regardless of content. 
https://hub.spaz.org/feed/spaz/featured
https://hub.spaz.org/feed/spaz/featured/lskjdfljsef
https://hub.spaz.org/feed/spaz/sjdfhlkaehfl
All display the entire RSS feed of the channel.

**Comment by kenrestivo** [comment]
Confirmed, fixed, thanks!
