### ISSUE TITLE
Table dreport issues. Need Attention? 

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#192]
Table dreport crash in last upgrade after some time and the number of queue messages increases with servers using http

**Comment by redmatrix** [comment]
Can't duplicate - everything is normal here; however "last upgrade" is somewhat ambiguous. What is the git revision tag?

**Comment by royalterra** [comment]
I can't see now I delete the logs . And the git no repair that time I simple  remove git and overwrite and make a new pull. Faster and easy.
The Cron make the git pull automatically wit user www-data and never fail until know . Basically I think that table hold many records some more of 2 weeks old 2015-11-01 to a server example no exist https://redmatrix.me  what is waste of resources

**Comment by royalterra** [comment]
This can be a new issue: 
Really the other day I read something in the HUB about no streaming resources like videos for no make a economical cost in Bandwidth to small HUB admins . Ok that is very nice but by example I will like to possible streaming anything more when I not have extra charges for more bandwidth and I will like to not keep records more of  2 weeks old in my dreport row because I believe is a waste of resources.

Possible can be 2 options in Admin GUI:
1.- How long you like to keep all the data in the dreport table
2.- If you like simple show Videos ... us a link in your web or simple you like streaming and not care about bandwidth.

A extra information in Install.txt will be good for people not get surprises 

That I think will make happy to everyone

**Comment by redmatrix** [comment]
redmatrix.me just expired (a couple of weeks ago) and was taken offline. We do not mark a site as "dead" until 30 days beyond the last time of successful communication. You can manually mark this one dead in the database - it isn't coming back; but we have had a few instances where sites had prolonged cert issues or database corruption which took 2-3 weeks to get sorted out. Hence we give them a reasonable grace period before we declare them to be dead. 

> How long you like to keep all the data in the dreport table

util/config system expire_deliver_reports 14

will set the dreport expiration to two weeks. I've just added this to the hidden_configs doc and will check it in within the next day or two.

**Comment by royalterra** [comment]
Ok thanks change like that
