### ISSUE TITLE
Local directory Broken 

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#203]
hi i really think the problem start with people fork or import external channels to my server and after become a clone the other server shout down. At the end now half of the public channels not show up and new channels and groups also not show up
I already check the database and look ok with not error now where is the problem or how I solve that?

I check more you make a group and after delete the group make after with the seam user a channel and the delete group still is in the Database

**Comment by redmatrix** [comment]
Groups cannot be deleted. It's a security/privacy issue. They can only be abandoned.
