### ISSUE TITLE
Photo uploaded with restricted perms (from /photos) end up visible for everybody

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#21]
Have not investigated further yet...

**Comment by git-marijus** [comment]
Have not investigated further yet...

**Comment by redmatrix** [comment]
We will have to sync the photo, item and attach permissions when setting/changing any one of them. I only got part way on this. I'll put it on my list of things to sort out.

**Comment by redmatrix** [comment]
I think this should be sorted now.

**Comment by git-marijus** [comment]
Uploading from /photos seems fixed. When uploading from /cloud the image in /cloud has default perms but in /photos it is visible to everybody...

**Comment by git-marijus** [comment]
fixed
