### ISSUE TITLE
Improvement "Use hreflang for language"

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#211]
In Hubzilla you can setup the site language but please can you add to the "hreflang" for language and code in the pages . That is very useful for the crawlers get Hubzilla with the language you have setup.

1.- People can find more easy a HUB with the own language in any crawler like google yahoo etc

**Comment by redmatrix** [comment]
Please clarify. We use the browser language by default. The site language is only used when the browser does not specify a language, or the browser language is not available as a translation.

**Comment by kenrestivo** [comment]
This sounds like an SEO thing. Maybe OP is asking for metadata, tags, language, for more Googleability.

**Comment by redmatrix** [comment]
Google is somewhat specific about when to use this and our usage doesn't really fit their model.

https://support.google.com/webmasters/answer/189077?hl=en

**Comment by royalterra** [comment]
There we are possible here is more clear http://www.w3schools.com/tags/att_a_hreflang.asp
And is not a question of Google is a question for more of the crawlers.
I can easy include that in the first page and setup again with every upgrade but yes @kenrestivo is a question of SEO and that is not only of google. if the crawler get the  info in the first page example login you not need to border any more.

And by example you have a geographic domain more of the crawler will make target to the designation of that domain if the domain is .uk and your hubzilla node is Spanish language that is no matter  they will advert your web for UK . And you get in a contradiction.

Hubzilla need to improve SEO and modify templates or files go to be overwrite in the next pull is a job every time.  I think really for Hubzilla grow up in numbers we need a good SEO and Hubzilla Server administrator have the possibility to target users according to a location or language. Use  hreflang help to that more if they not got the geographic domain and they have a .something still they have the opportunity of target users in a location with a specific language .
In google I can setup my generic domain example Spain . Ok I not need more but example in Spain you can Speak Catalan, Gallego and Spanish. There we are by example google will target my web for all Spain when possible I am only interest in the region of Catalunya speak Catalan. And that will not change because only my web have the language Catalan you need to add a little extra more.

Still I think in also missing meta tags like site description : In meta HUbzilla sites if you google UP is 
Name of Site 
Description: {2}{3} {4} · Register · Login · Login · Remote authentication · Login · Remote authentication. Welcome to SITENAME. Email. Password. Remember me.

That really @redmatrix no sell a hubzilla hub at all .

Ok I understand your point about Hubzilla Multilanguage but possible can be add us hidden configuration the "hreflang" for user like to setup that and make something for users can post the meta tag description and any crawler get the description of  the site. 

Meta tag description not need to be in the user pages but the normal is to be in the Login or Registration page where any crawler get easy

**Comment by royalterra** [comment]
Ok @redmatrix I got a idea : 
1.- Add Login Link to form now only say Password Reset , Register
2.- create a folder example home with a index.php showing only the Login form not top Frames with a "include" using the css of the theme selected 
3.- Administrator  like is now can select the home folder us home page of the HUB
4.- Any admin can easy edit the file index.php in folder home and add any metatags like site name description keyworks robots follow or unfollow etc

Possible is a good idea setup a example for any one only change the nam, keyworkds, description etc

**Comment by royalterra** [comment]
I make a small Plugin for solve this issue I will release in the next 2 or 3 days after I see how Google and the rest get the meta tags  . The only need is the admin change the Site Name, Description and words in the plugin according to his site . That will make HUbzilla more SEO friendly

**Comment by royalterra** [comment]
@redmatrix You can check now in my web with the browser show source . 

I make for easy for any one the plugin .
in .htconfig.php The user can setup:
1.-  Site description , 
2.- Site keywords
2.- hrflang if hi like to be target by language 
3.- Robots follow not follow or what ever like the admin

That I think solve any issues of SEO with respect to Metatags

**Comment by royalterra** [comment]
@redmatrix This Plugin https://github.com/royalterra/release I make solve this issue please consider to include in the Plugin List if you consider necessary

**Comment by royalterra** [comment]
The plugin change dynamically the metatag description in HOME, LOGIN REGISTER< DIRECTORY and PUBHUB if not you will get the seam description in every single page include public users.
Like that you make specific the description you like. Hreflang can be setup if you like or not us wish of the admin
