### ISSUE TITLE
Change install.txt - Pull Improvements

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#214]
I think Mod Rui2 can be a good option to add in the Install.txt of Hubzilla 
apt-get install libapache2-mod-ruid2

Mod Ruid2 doesn't need to kill Apache2 children after one request. . It makes use of kernel capabilities and after receiving a new request suids again. Hubzilla open and close many children and this module is really perfect for improve the performance.
Server Admin will get more resources and normals user will win in speed .

**Comment by royalterra** [comment]
Add Script for tune Apache2 with a Hubzilla installation possible need some extra variables depending of your mod_prefork.conf  but checking the first days apache2 errors you can get more closed numbers 
https://github.com/royalterra/apache2tune

That solve the question of @kenrestivo about mod prefork  and help people to configure the own installations for work perfect with apache2

**Comment by kenrestivo** [comment]
This looks really useful!

```
Total memory 1991
Free memory 244
Amount of virtual memory being used 0
Largest Apache Thread size 18
Amount of memory taking up by MySQL 96
Virtual memory is ok
Total Free Memory 244
MaxClients should be around 13
MinSpareServers should be around 3
MaxSpareServers should be around 6
```

You should add a link to this tool into the documentation, and make a pull request.

**Comment by royalterra** [comment]
Hi Thanks @kenrestivo I add to the INSTALL.txt at the end possible @redmatrix like to check my Pull resquest

**Comment by royalterra** [comment]
OK now that is merge thanks @kenrestivo for the test . 
I will improve that script with time . This thread will be close now
