### ISSUE TITLE
Proposal Create Robots.txt 

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#218]
After I see google spamming my Apache AH00687: Negotiation: discovered file(s) matching request: /var/www/mydomain/mod/profile (None could be negotiated). 

I think is a good idea to make the File Robots.txt for disallow crawler requests to folders. I already add the folder "mod" 
Any more folders or ideas to the proposal?

**Comment by redmatrix** [comment]
You cannot access our internal system folders and their contents unless you over-ride the system configuration. The bigger question is what is running on your webserver that is leaking your internal path structure to the outside world? Hubzilla does not do this.

**Comment by royalterra** [comment]
@redmatrix I am not running nothing extra is a clean copy from github and I not have idea why google get that url I become surprise to .
Today I not see more logs after I setup a robots.txt
