### ISSUE TITLE
Errors after Git Pull

### ISSUE THREAD

**Issue by FreeEagles** [redmatrix/hubzilla#221]
After last git pull I got several errors I check the database and look ok. Any Ideas Thanks
[Wed Dec 16 01:58:21.636392 2015] [:error] [pid 25681] [client 213.136.81.241:51693] PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /var/www/include/zot.php on line 4148
[Wed Dec 16 01:58:21.636951 2015] [:error] [pid 25681] [client 213.136.81.241:51693] PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /var/www/include/zot.php on line 4148
PHP Fatal error:  Call to undefined function update_queue_item() in /var/www/include/deliver.php on line 160

Anyone have idea what is all that Cron stop working if I execute say
PHP Fatal error:  Call to undefined function update_queue_item() in /var/www/include/queue.php on line 136

**Comment by redmatrix** [comment]
should be fixed

**Comment by FreeEagles** [comment]
Yes that is working . You the best Thanks :+1:
