### ISSUE TITLE
Unable to configure profile fields in the database

### ISSUE THREAD

**Issue by navigium** [redmatrix/hubzilla#229]
I'm really not sure whether I'm too stupid to figure out how it works or whether a bug. I tried to change the profile fields that are shown on the profile edit page. When I added the settings to the .htconfig.php file with 

    $a->config['system']['profile_fields_basic'] = array('name','pdesc','chandesc','homepage','hometown','about');
    $a->config['system']['profile_fields_advanced'] = array('interest','music','book','film');

it worked flawlessly. If I try to add the same configuration in the database, it fails. I tried the following variations in the syntax:

     ./util/config system profile_fields_advanced name, pdesc, chandec
     ./util/config system profile_fields_advanced "'name', 'pdesc', 'chandec'"
     ./util/config system profile_fields_advanced "array('name', 'pdesc', 'chandec')"

Since I'm not really a PHP programmer I ran out of ideas here. Whenever I set the configuration to anything except "" it removed all the fields except the first two.

**Comment by redmatrix** [comment]
util/config operates on strings only and currently lacks array support. You can enter the desired configuration into your .htconfig.php file as a php array as a workaround.

**Comment by redmatrix** [comment]
example:

    $a->config['system']['profile_fields_advanced'] = array('name','pdesc','chandesc');

**Comment by git-marijus** [comment]
This is probably fixed with 548bf884a4b34a4881f3188e54c592597f755dc9
