### ISSUE TITLE
baseurl without https - browser complains about mixed content

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#24]
The browser warns about mixed content and insecure connection even when the visible URL is https://domain/

Page source shows baseurl to be without https, only http, which then propagates to several elements, but not all.

Suggested solution: append "s" to "http".

**Comment by HaakonME** [comment]
Right, I think I found it - during setup -http:// is the default suggestion rather than https:// . I assume I can do util/config system baseurl https://domain/ to fix it?

**Comment by redmatrix** [comment]
Yes - on your first access it will go through and try to correct everything. Just let it run.

**Comment by HaakonME** [comment]
Thanks, I should be okay now. As an aside, I am fiddling with OpenShift, which upon each "git push openshift HEAD" and restart of all gears deletes all files unless they are stored in the special OPENSHIFT_DATA_DIR for the app. This means it deletes .htconfig.php each time too, which prompts a new setup where https can be applied. An aside to the aside - this explains why files visible in a channel's cloud are not working after each git push - they are not really in the directory store anymore, the visible file names are just pulled from the database, but the actual files these links point to are deleted. The solution is to link store to the OPENSHIFT_DATA_DIR. I hope to have a script doing the motions as time allows, adding the symlinks as needed for preserving data and adding cron configuration ala OpenShift.
