### ISSUE TITLE
Posting to Not HUB or Domain

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#240]
Hi I not upgrade any more from last release 2 or 3 days but looking the queue 
I observe I have a entry   1	/users/	0
users is not any DOMAIN and I not have idea where that coming from just show up in the queue

**Comment by redmatrix** [comment]
The platform is designed to connect community websites together. It is quite normal for hubs to communicate with each other. It is impossible to determine from this bug report if the message in the queue is normal or abnormal. I'd recommend examining the queued message if you are concerned - and report the message type and destination and why you believe it is a problem.
