### ISSUE TITLE
Website / Documentation: most prominent call to action button leads to zero information

### ISSUE THREAD

**Issue by COLABORATI** [redmatrix/hubzilla#254]
One of the two most prominent buttons on the hubzilla.org website is a call to action: 
`Run Your Own Hub` 

But the URL of that button only links to the main github repo, which has absolutely ZERO information about how to run your own hub. This is a great strategy to discourage about 99% of people interested in this project.

If you are interested in getting people involved, then please change this and provide very easy ways to install / use / test this software. I did not find this project ready-to-go on vagrantcloud, e.g. - this would be a good start. Also please offer packages for at least the most used webserver operating systems, so that people can just apt-get install hubzilla. 

I take the role of being that guy to point you at this incredible elephant in the room that you might not see because you are deep into details, not realizing how you are shooting your project by sending most of the interested visitors away by putting a great example of a big frustrate-me-button on the most prominent place of your website.

**Comment by jeroenpraat** [comment]
There is a directory 'install' with a file 'install.txt', but you are right it is not in your face. I added a link in the README file (that one is displayed on the front page on Github), so that is a first step. 

You are welcome to give us more advice or even step in.

**Comment by COLABORATI** [comment]
What is the current state of install automation?
Is anybody workig on / do exist ready-to-go virtual machines, vagrant boxes, distro packages, ansible playbooks, shell-scripts, whatever?

**Comment by jeroenpraat** [comment]
There are two automation scripts currently available. Hopefully more will follow. Just take a look in the repo, you will find them (hint ^\..*)

**Comment by jeroenpraat** [comment]
Oh and Mike, our main developer has posted today something about this on is Hubzilla channel: https://macgirvin.com/channel/mike/&f=&mid=328972f1198ad2f782d5cbdccd433241535d298c1e3888cf1e71c25aa5030f9b@macgirvin.com
