### ISSUE TITLE
Feature: More Admins and Moderators

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#256]
Feature resquest for possible have and other Admin with restricted permission for possible not delete the first admin and Feature Request for have example Moderators can block , approve or delete users

**Comment by redmatrix** [comment]
Moderation is already supported. 

Delegated site administration is also possible but this feature is intentionally un-exposed in any UI or documentation; as the delegate does not have restricted permission but becomes a full administrator.  So I would change the scope of this feature request to "Reduce permissions for delegated administration".

**Comment by royalterra** [comment]
Hi @redmatrix the other day I make a second admin I think I believe remember add in the user mysql role the value 4096 that user become to full admin and show up correctly both in the json file.  Yes you are right reduce permission can be more correct
