### ISSUE TITLE
Missing "$db_type = '1';" in .htconfig.php file after a postgreSQL installation

### ISSUE THREAD

**Issue by blankoworld** [redmatrix/hubzilla#259]
Hi,

Using Hubzilla with postgreSQL/php5-fpm/nginx, I get a curious behaviour after installation:

  * I receive a page on which it explain me that I have to install a cron and register me
  * I launch the register link: blank page

To install Hubzilla, I tried several times to connect to DB, I first have wrong port, then wrong database password, etc. But I finally achieve the installation.

Here is some info:

```bash
lsb_release -a
```

gives:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```
I'm on git branch with commit fc54f54b989570e2767a53c3c72875255b0dc95f.

I don't use SSL on nginx.

After having add this line in .htconfig.php, I could anew display a non-blank page and continue the Hubzilla experience :smile:: 

```php
$db_type = '1';
```

**Comment by redmatrix** [comment]
I'm guessing this may be the result of installing in a language other than English (?) 
specifically something besides "en". It appears many of our international config templates (including en-gb and en-au) are missing the postgres/db_type bit. In any event I believe this is now fixed.

**Comment by blankoworld** [comment]
Yes I forget to say it: I install this software in a french environment.

Should I attempt to reinstall it with your last commit to see if it's OK now ?

**Comment by redmatrix** [comment]
I think you confirmed the problem and I'm fairly confident of the fix. Re-installing regenerates your personal channel identity. This is fairly easy to backup and "clone" onto a new installation but it adds complication. Enjoy Hubzilla. I can verify the fix on a throw-away site so there's no need to mess with yours now that you have it working.

**Comment by blankoworld** [comment]
Now it's OK with last changes ;).
So I close this issue.
