### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by coevolving** [redmatrix/hubzilla#262]
Should there be a clarification/amendment to copyright when using Hubzilla?

There seems to me to be licensing in two domains:  (i) the software source code; and (ii) the authored content.

On (i) the software source code, the license seems pretty straightforward at https://github.com/redmatrix/hubzilla/blob/master/LICENSE.  It's an [MIT License](https://opensource.org/licenses/MIT).

On (ii) the authored content, there's a distinction between public information and private information described at https://hubzilla.site/help/Privacy.  The private information is ... well ... private, and therefore  normal copyright should apply, i.e. privileges to further reproduction and/or derivations are granted by the copyright holder, and require contacting him / her / the organization.  

However, on public information, the mechanics are a little different.  Hubzilla is clear that "Content you provide (status posts, photos, files, etc.) belongs to you".  This means copyright should be in force, as usual.

If we look to the license for federated wiki at https://github.com/fedwiki/wiki-client/blob/master/LICENSE.txt, there's an additional clause (beyond the MIT license) that: 

> All files located in the pages directory are licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.  
> CC BY-SA 4.0 : http://creativecommons.org/licenses/by-sa/4.0/

Incidentally, this extra licensing term doesn't appear on the server side, see https://github.com/fedwiki/wiki/blob/master/LICENSE.txt.

The federated wiki encourages resharing of content by making all of the authored content Creative Commons BY-SA.  It's not possible to make part of a wiki site non-public, so the optional behaviour (done by Ward Cunningham) is to have a wiki site on a private server and/or behind a firewall, and then replicate out (i.e. fork the content) when it's ready to be public.

Q1:  Should Hubzilla adopt a similar CC BY-SA license on the public content?

Q2:  If I'm to host a site for a community who explicitly wants to contribute in the CC way, does it make sense to have the CC BY-SA license somewhere on the edit page, so that the author is explicit about his or her intentions in contributing the written content?  At minimum, could/should this become something added in the footer?  The best way for the world would be CC on public content, but if that's not the default, there should be an option to set that.

**Comment by redmatrix** [comment]
Content licensing is a huge can of worms - as we are able to federate with content providers that provide content on different terms. We cannot enforce attribution. The project software is also available to both open and closed communities, so we also cannot provide a blanket license for the network. Hubzilla as a software provider does not dictate policies per se, we generally only provide means for site owners to implement policy decisions appropriate to their communities. 

I would suggest that this is the type of thing which should be handled by a plugin that sites which need to be bound by such legal constructs can install. What the project would need to provide support for this this is a text field attached to all communications where the associated license terms can be transferred with those communications; and we would also need a convenient way to display the terms for any specific message before quoting or forwarding it. This does not exist currently.

We may not easily be able to provide any relief for dis-ambiguating the terms on  "forwards of forwarded content" where two authors have contributed to the content and have conflicting licensing terms. I'm merely suggesting here that any solution is likely to be complex and will have "edge cases" which cannot be easily resolved (such as federating with other content providers that do not have the ability to attach license details or that provide conflicting licenses to "all content on their network" such as GNU-social). So this will take some time working with people that have different needs; to arrive at the best solution to fit the majority of use cases. I'll start by providing the core support for attaching licensing information to posts and work towards a long term solution. This may take up to a couple of months before a viable solution exists. If your needs are immediate, you will likely require a plugin to physically attach the terms as a visible footer to all posts/comments from your site. This is not a complex plugin and can be assembled in an hour or two.

**Comment by coevolving** [comment]
@redmatrix Thanks for your response.  Your solution of ...
> a plugin that sites which need to be bound by such legal constructs can install. 

... is reasonable.  
Further addition of ...
> a text field attached to all communications where the associated license terms can be transferred with those communications;

... could be more than is necessary.  

Copyright is, unfortunately, pervasive in our society.   I'm working with a community where the ideal would be assignment of copyright for derivative creative use, so that subsequent copiers and/or derivers don't have the bureaucratic step of having to go back to the original author for permission.

I see less issue with the "forwards of forwarded content" with Hubzilla, as attribution seems to be well supported in two ways:  (i) a comment is linked directly with the original post that is attributed, and (ii) the "link to source" also retains an attribution.  Of course, there's no solution for anyone just copying and pasting without using those Hubzilla features, so we can just hope that people will continue to maintain threads.  

The CC-BY-SA is probably the most reasonable license on public content for technology of this kind.  If an author doesn't subscribe to that, then he or she really should be posting in a private channel.  As an example, judging commercial versus non-commercial reuse across a network of hubs would add a lot of complications to replicating content.  

Thanks for surfacing GNU-social.  Looking at a few groups from http://www.skilledtests.com/wiki/List_of_federated_GNU_social_groups , I notice some variety  (e.g. Fresh Federati Network is CC-BY, Oracle.SkilledTests preserves copyright ).

**Comment by redmatrix** [comment]
I've added a new plugin/addon called 'msgfooter' which may suffice for your short term needs while I consult with others and figure out if there's a better or general way of doing this.

Once the plugin is installed and enabled it provides a configuration entry on the admin page where you can set text to be appended to all outgoing posts/comments from this site. This is not documented but the text should be written in bbcode. I would suggest something like 

    This post is licensed [url=http://creativecommons.org/licenses/by-sa/4.0/]CC-BY-SA-4[/url].

but this is under your control. The text is inserted after basic content filtering so including 'raw HTML' which includes angle brackets and/or quotes and double quotes could produce unexpected and undesired results.

**Comment by coevolving** [comment]
@redmatrix Thanks.  I'm working with the organization on a plan for a pilot installation.

**Comment by redmatrix** [comment]
Just an update on this issue - we added support for "item_meta" data recently and this allows a more comprehensive copyright plugin to be implemented; whereby one could show an icon or &copy; link in the post or post_actions menu and pull up the associated copyright text on demand when clicked. Nobody is working on this plugin at present, but my original intent was to provide a better mechanism to implement this than the somewhat obtrusive message footer.
