### ISSUE TITLE
Proposal Change Registration system 

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#264]
I observe in some popular HUBS people start a registration process get verify but when get to the point create a channel they abort or not continue· Possible the lag of understanding how works Hubzilla is the point for not accomplish the user registration. Can be a Option if Admin can allow in his HUB automatic channel creation.

1.- Admin Select if User will register us normal like is now or simple after the user have setup the Username and Password one initial channel will be automatically setup.

2.- New user with the new option after registration in the first login they will be redirect to the Own Page like your Grid or latest network post

**Comment by redmatrix** [comment]
This was implemented over a week ago.
