### ISSUE TITLE
PHP Warning:  DOMNode::cloneNode()

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#268]
That issue is new and from the moment is duplicate in HUBS with the actual Hubzilla version and HUBS with versions before Christmas is really strain because is the first time I see that 

PHP Warning:  DOMNode::cloneNode(): ID fnref:5 already defined in /var/www/include/html2bbcode.php  on line 67
PHP Stack trace:
PHP   1. {main}() /var/www//include/importdoc.php:0 
PHP   2. importdoc_run() /var/www/include/importdoc.php:19 
PHP   3. update_docs_dir() /var/www/include/importdoc.php:15 
PHP   4. store_doc_file() /var/www/include/importdoc.php:36 
PHP   5. html2plain() /var/www//mod/help.php:111 
PHP   6. node2bbcode() /var/www//include/html2plain.php:128 
PHP   7. node2bbcodesub() /var/www//include/html2bbcode.php:13 
PHP   8. DOMNode->cloneNode() /var/www/include/html2bbcode.php:67 
PHP Warning:  DOMNode::cloneNode(): ID fnref:1 already defined in /var/www/include/html2bbcode.php  on line 67
This issue become in seam time in 3 domains after Cron execute  /usr/bin/php include/poller.php

**Comment by redmatrix** [comment]
You are importing content from a malformed RSS feed. If you are interested in figuring out what feed this is and how it is malformed and find workarounds for it you are welcome to do so. You could also contact the feed provider and ask them to fix their feed. I will caution you that there are millions of malformed feeds. Some of them fail in spectacular ways and we do not have enough developers or time to work around all of them. At a project level, this is a 'wontfix'. As a workaround you can disable or remove that particular feed or just ignore the warnings.

**Comment by royalterra** [comment]
hi thanks i will look around and see how is making the error if I see again and if not I will ignore the warning
