### ISSUE TITLE
Diaspora now checks against "author_signature" in relayed comments as well

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla#269]
In the current Diaspora versions a potential security problem was closed. Until now relayed comments and relayed likes were only checked against the "parent_author_signature", not the "author_signature". (Although Diaspora always sent both)

Newer versions now do the additional check against both signatures. In Friendica this lead to the problem that comments hadn't reached their target anymore when they were relayed by us. I can imagine that Hubzilla could have the same problem. At Friendica we activated the existing functionality that was filling the "sign" table and did some small changes. After this it began to work again.

**Comment by redmatrix** [comment]
This functionality has been enabled all along however it was discovered that we performed a double encoding on the author signature, which resulted in verification issues. This should be fixed in 411abdf8a and has been backported to redmatrix.
