### ISSUE TITLE
Data garbled and data loss - two problems with private messages from RedMatrix hub

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#27]
ZotMor was updated to latest Hubzilla code today, I do not know if the following problems have anything to do with this.

The problems: I wrote some private messages at Parlementum.net and this became a correspondence at that RedMatrix hub. Upon login to my newly updated Hubzilla hub ZotMor at https://zotmor.rhcloud.com/ , I noticed notifications for private messages and clicked to see the messages. These were obviously messages I had read before at Parlementum.net and transferred from that RedMatrix hub to the Hubzilla hub ZotMor. However, the private message titles are garbled - perhaps an some character set issue, but more seriously, the message content was completely gone.

**Comment by redmatrix** [comment]
The content is still there, but was obfuscated using different technology than we are currently using and cannot be decoded using the technology we are currently using. The exact technology used depends on when the messages were transferred. If we know that or have a sample one might be able to put together a custom function to unscramble just those messages. I tried a number of formats before settling on one that didn't take a second or two per message to unscamble, which makes loading the message list page painful. The technology has stabilised and any messages created now on either system should display correctly on the other.

**Comment by HaakonME** [comment]
Right, no worries for these messages in particular - they were already read. Parlementum.net is at present at {"version":"2015-08-17.1127R","version_tag":"2.7","commit":"75fbf21","url":"https:\/\/parlementum.net" , which may or may not be the version in use at the time of transfer. I can check with Parlementum. The current version at ZotMor is {"version":"2015-08-18.1128H","version_tag":null,"commit":"","url":"https:\/\/zot-mor.rhcloud.com". 

It had been some days since my last Hubzilla update at ZotMor, so if the problem is on that end, then I need to learn how I can use git log to find out what the last version I had was before I pulled from upstream.

**Comment by redmatrix** [comment]
There are two options. You can 

a) delete them and start fresh
b) figure it out

Should you choose b) :

If the contents begin with a json array they are likely AES256 encrypted with the site public key and can be decrypted with the site private key. This would probably involve messages which arrived before May 19th.

If they are something else, from May 19th, you would have to go back to those checkins related to mail_obfuscation on May 19th and try each one until you see something.

If they were between May 19th and August 9, you may be able to read them by pulling commit 8ce48148, I believe there is just a mismatch between mail_flags & MAIL _OBSCURED and the mail_obscured table column which was added back in May. If one of these is set but not the other, set the other and you may be able to read them.

**Comment by HaakonME** [comment]
I will go with a) in this instance.
