### ISSUE TITLE
openssl_verify php warning

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#272]
I receive this in php.out every 5-30 min:

````[02-Feb-2016 18:45:20 Europe/Amsterdam] PHP Warning:  openssl_verify(): supplied key param cannot be coerced into a public key in /var/www/hubzilla/include/crypto.php on line 23````

I checked it in old php.out logs (long live logrotate) and it seemed it was at least in there on January 17 (the oldest log I have).

**Comment by jeroenpraat** [comment]
This is still an issue. What can be the problem?

**Comment by redmatrix** [comment]
This was happening with Thomas' sites at one point but basically you've either got an empty key or a bad key from somewhere. You might have to put a backtrace call into this function to find out what arguments are being passed and how you got here - e.g.  where the errant key might have come from.

**Comment by jeroenpraat** [comment]
That sounds very complicated. Is it not possible that this is because of other hubs with unvalid certificates? If so, is it not possible to block all other hubs with unvalid or no certificates. Or this is probably unrelated?

**Comment by jeroenpraat** [comment]
I've put the logger in there. I already got some results when $verify = 0. Let me run this for a day and see of if there is a patron.

**Comment by redmatrix** [comment]
It's coming from beardyunixer@beardyunixer.com. The sitekey is mangled - as the linefeeds have been converted to a literal '\n' and all the slashes are converted to '\/'. All we can do is log the error and carry on. Can't really communicate with that site under the circumstances site but that was probably intended.

**Comment by jeroenpraat** [comment]
I'll also checked the logs and I have errors from beardyunixer.com too, but also from deadsuperhero.com. Both hubs are generating these two openssl_verify errors. The first error a bit more than the second error:

openssl_verify: error:0906D06C:PEM routines:PEM_read_bio:no start line

openssl_verify: error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01


I am also wondering if it is related to the [poller.php output with PHP Notices I receive](https://github.com/redmatrix/hubzilla/commit/b101a8f6fb3fd3ec0d5466ba1bb7bc9dc9480fba#comments).

**Comment by jeroenpraat** [comment]
Fixed and I didn't receive the PHP notices via cron mail either. So that was indeed related (or there must be a coincidence).
