### ISSUE TITLE
Email SMTP PHP configuration feature resquest

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#277]
I observe if you have one email setup correctly with one IP . Hubzilla only send emails with the primary IP of the server and yo have only one Option is setup all the Hubs domains in that IP or email not go out. Can be a good feature if admin can setup email configuration in the admin section. That is also good for small hubs normally the hosting have block email with apache for avoid spam and suer can use any google or any other account they like for the HUb send mails

**Comment by royalterra** [comment]
I find in Hubzilla a class use by WordPress, Drupal, 1CRM, SugarCRM, Yii, Joomla! https://github.com/PHPMailer/PHPMailer possible can be nice include for the admin user the mail server they like and not relay in php-smtp

**Comment by Cacasapo** [comment]
I'm having issues with mail and DMARC using Hubzilla on a shared server and WHM 56. Apparently, the DSO handler causes some mail sent via PHP not to be signed. 
The answer would be having Hubzilla include an option for configuring SMTP parameters for outbound mail, which is what I believe you've asked for, Royal.

I'm surprised there's not more noise about this feature.

**Comment by royalterra** [comment]
Hi @Cacasapo not one look take interest in this feature . I have the seam issue with dmarc .

**Comment by Cacasapo** [comment]
I managed to get e-mail delivered by editing include/network.php.
Commenting out  ` $sender_email = 'noreply' . '@' . $hostname;`  and replacing it with ` $sender_email = user@server.hostname.com;`

This is on a Cpanel server with SPF, DKIM and DMARC properly configured.

**Comment by royalterra** [comment]
Uhm @Cacasapo you have change the user for teh user setup in your server . I have also issues other domains servers complaint about the noreply also when I create that user the problem is we need email authentication in the admin GUI 

The second issue is at the end of email is not the legend for opt out of emails and people can start reporting SPAM before they login again and remove the mail options front the control panel.

A option like other social networks for click in a link in the email and go directly to the email options in the control panel will be the perfect solution
