### ISSUE TITLE
Directory Mode Error Reporting

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#279]
From the day the domain blablanet.es is register and HUB install nothing is change 
$a->config['system']['directory_mode']  = DIRECTORY_MODE_SECONDARY;
But in last Git Pull is reporter is acting us DIRECTORY_MODE_NORMAL
How is that Possible? The only Possible is $a->config['system']['directory_mode']  = DIRECTORY_MODE_SECONDARY; is not working properly and that directive no works

**Comment by royalterra** [comment]
That is ridiculous  http://hubchart.hubzilla.it/hub.jsp?hubFqdn=blablanet.co.il also report directory mode Main Directory and is in .htconfig.php setup from first day us cache directory aslso now few month there and with only 2 users @redmatrix really you can't say now is a problem of a Individual Hub really something here is not clear

**Comment by redmatrix** [comment]
You may have it set to secondary in the config file - but this is over-written by what is in the database. You may have "accidentally" set this manually with 

util/config system directory_mode 1

and this over-rides your config file. It should be set to 2 for a secondary server. 

In any event your site is reporting to the outside world that it is DIRECTORY_MODE_PRIMARY and there is only one primary directory allowed per realm. So if we encounter a site with that setting in the RED_GLOBAL realm (other than zothub.com) we ignore it completely and change it to something safe.

**Comment by royalterra** [comment]
Test Directory Mode in 2 domains one .es have a lot configs but co.il have only few addons activate from first day nothing do there 
blablanet.es# util/config system directory_mode
config[system][directory_mode] = 2
blablanet.co.il# util/config system directory_mode
config[system][directory_mode] = 2

Both show UP us secondary Server can you tell me please where I need to look ?
Mysql say:  system	directory_server	https://zothub.com

**Comment by redmatrix** [comment]
Here is what your site reports. 

https://blablanet.es/siteinfo.json

**Comment by royalterra** [comment]
Ok @redmatrix I agree there say Directory Mode Primary now look https://hubzilla.site/siteinfo.json

SAY directory_mode":"DIRECTORY_MODE_PRIMARY",
https://hubzilla.zottel.net/siteinfo.json
SAY directory_mode":"DIRECTORY_MODE_PRIMARY",
https://hub.pixelbits.de/siteinfo.json
SAY directory_mode":"DIRECTORY_MODE_PRIMARY",
https://my.federated.social/siteinfo.json
SAY NOTHING BUT IS IN THE LIST Page not found.
https://hubzilla.nl/siteinfo.json
SAY directory_mode":"DIRECTORY_MODE_PRIMARY",

@redmatrix really I am missing something ? All say DIRECTORY MODE PRIMARY like me but I am sure I have setup secondary  I am sure util/config system directory_mode return 2 
Can we consider all that one BUG

**Comment by redmatrix** [comment]
#fixed

**Comment by royalterra** [comment]
Ok Thanks test and working I imagine that solve the seam issue before Christmas I make the Pull request #282 for include again blablanet.es 

Request ~281 can be close nothing to do here  . I imagine we can close this issue if not one have something more to say?
