### ISSUE TITLE
Hubzilla addons undetected in a fresh installation

### ISSUE THREAD

**Issue by csolisr** [redmatrix/hubzilla#284]
Currently, [my instance](https://social.azkware.net) is not detecting the bundled addons (as it can be seen [here](https://social.azkware.net/siteinfo&JS=1)). On the `settings/featured` section, where the addons are controlled, I'm greeted by a message that says "No feature settings configured". Why are the addons disabled? Is there some configuration required to enable them by default?

**Comment by jeroenpraat** [comment]
Did you follow the installation instructions for the addons in the installation documentation? https://github.com/redmatrix/hubzilla/blob/master/install/INSTALL.txt#L131

**Comment by redmatrix** [comment]
Once they have been physically installed on the server, the hub adminsitrator needs to enable any which are desired for this site at admin/plugins . Then the addon settings and configuration for those plugins are available to site members.

**Comment by csolisr** [comment]
@jeroenpraat: Been there, done that. Though I still can't figure out where is the admin site (it's not available in the installation folder nor at https://social.azkware.net/admin ).

**Comment by jeroenpraat** [comment]
Are you sure your account is an admin account? If not follow this: https://github.com/redmatrix/hubzilla/blob/master/install/INSTALL.txt#L191

**Comment by csolisr** [comment]
For some reason my user was not set as the admin by default, I had to manually set the permissions in the database. But after that, the admin page was finally open for business. Thanks for your help!

**Comment by jeroenpraat** [comment]
You're welcome. Good luck with your Hubzilla hub,
