### ISSUE TITLE
Translations: multiple plurals

### ISSUE THREAD

**Issue by dotevo** [redmatrix/hubzilla#288]
Hi,

I've started translating the hubzilla on Transifex (to Polish language) but I found an issue.
Example:
https://github.com/redmatrix/hubzilla/blob/master/include/datetime.php#L272

We have "year", "years".
It is easy to translate "year" into "rok" but I need a number for "years".
1 year - 1 rok
2 years - 2 lata
3 years - 3 lata
5 years - 5 lat 
...

Please check this http://stackoverflow.com/questions/12121515/multiple-plural-forms-in-gettext

GETTEXT files works fine with polish language, but not here and in many Hubzilla source code places

BR,
Adam

**Comment by redmatrix** [comment]
The stackoverflow question and responses are correct and we should be able to accommodate this usage. I'm not certain how the plural form is entered into transifex (this may be provided for you automatically).  We translate that to a plural form function which takes an array. 
The trick is in the translations to provide a three element array.

msgid "%d Comment"
msgid_plural "%d Comments"
msgstr[0] "%d Komentarz"
msgstr[1] "%d Komentarze"
msgstr[2] "%d Komentarzy"

I'm not a translator so perhaps one of our folks who does translations can provide a bit more insight. We have a tt() function which translates strings with the appropriate plural form. I think the biggest question in my mind is if the datetime function you referenced is actually using tt(). If not, this is a bug which needs to be corrected. [Edit: I've just checked and indeed this is a bug. So I suggest working on other strings until we get this one sorted out.]

**Comment by dotevo** [comment]
I know that 0 A.D. uses Transifex and their translations look good. Example: https://github.com/0ad/0ad/blob/master/binaries/data/mods/public/l10n/pl.public-gui-other.po

And they use gettext context too. I think that is also missing in Hubzilla but not connected with plural forms.

**Comment by dotevo** [comment]
I also found "Likes" and "Dislikes". I'm sure but if it is a text under the post like "5 Likes" than those words need more plural forms.

**Comment by redmatrix** [comment]
There are a few instances of these strings in the code. The context labelled 'noun' has plural forms and I believe the one we use in "5 likes".
