### ISSUE TITLE
.homeinstall script is broken

### ISSUE THREAD

**Issue by anaqreon** [redmatrix/hubzilla#294]
Installing a hub using the .homeinstall/hubzilla-setup.sh script results in a white screen after the script completes. I think the source of the problem is that the .htconfig.php file that is generated is completely empty for some reason, but I don't know why.

Hubzilla version 2016-02-17.1312H

**Comment by einervonvielen** [comment]
in homeinstall.sh, function "install_hubzilla" is


    touch .htconfig.php
    chmod ou+w .htconfig.php

Have you tried to manually run these steps? Hmm???

**Comment by anaqreon** [comment]
This issue has been resolved.
