### ISSUE TITLE
Upcoming changes in the Diaspora protocol

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla#295]
There will be changes in the Diaspora protocol in upcoming versions of Diaspora. The changes should make the protocol more flexible. See discussion here: https://github.com/SuperTux88/diaspora_federation/issues/26#issuecomment-186961840

**Comment by redmatrix** [comment]
There are several related issues in the mentioned repository issues list. I believe we are now well-positioned to handle these changes on the inbound side, but still need to implement a few things on the outbound side once the new protocol starts being generally supported in the wild.
