### ISSUE TITLE
 PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /var/www/hubzilla/include/config.php on line 295

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#319]
Find this repeated over and over again in my php.out file, since a few days:

```
[09-Mar-2016 20:14:35 Europe/Amsterdam] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /var/www/hubzilla/include/config.php on line 295
[09-Mar-2016 20:23:36 Europe/Amsterdam] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /var/www/hubzilla/include/config.php on line 295
[09-Mar-2016 20:23:49 Europe/Amsterdam] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /var/www/hubzilla/include/config.php on line 295
[09-Mar-2016 20:27:37 Europe/Amsterdam] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /var/www/hubzilla/include/config.php on line 295
[09-Mar-2016 20:27:41 Europe/Amsterdam] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /var/www/hubzilla/include/config.php on line 295
```

**Comment by jeroenpraat** [comment]
Thanks

**Comment by jeroenpraat** [comment]
This doesn't seem to be resolved. I thought it was, but when I check the logs, I see it started the 10th in the early (UTC) morning again.

**Comment by waitman** [comment]
can we please change network.php, noisy logs
thanks,

..
[26-Mar-2016 00:00:31 America/Los_Angeles] PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in /www/zilla/hubzilla/include/network.php on line 1147
[26-Mar-2016 00:00:31 America/Los_Angeles] PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in /www/zilla/hubzilla/include/network.php on line 1149
[26-Mar-2016 00:00:31 America/Los_Angeles] PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in /www/zilla/hubzilla/include/network.php on line 1151

/www/zilla/hubzilla/include/network.php

        if (is_array($x))
        {
                if(array_key_exists('address',$x))
                        $address = $x['address'];
                if(array_key_exists('location',$x))
                        $location = $x['location'];
                if(array_key_exists('nickname',$x))
                        $nickname = $x['nickname'];
        }

**Comment by jeroenpraat** [comment]
Unfortunaly still not solved :-(

`[29-Mar-2016 19:44:40 Europe/Amsterdam] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /var/www/hubzilla/include/config.php on line 295
`

**Comment by redmatrix** [comment]
The referenced fix is for part 2 (waitman's comment).  The first fix solved the occurrence of the initial report on my sites for my data and configuration and installed plugins. I have not seen any other occurrences. If somebody wanted to track down an occurrence which is triggered by something in their own site configuration or usage patterns, it would probably require a backtrace statement in the referenced function if the uid is not an integer or is zero and find out where in the code this errant setting is being made. Then we can figure out what to do about it.

**Comment by waitman** [comment]
sorry, i might have posted the issue on the wrong page. 

array_key_exists is in the following files:
```
#grep -l -r array_key_exists
library/OAuth1.php
library/HTMLPurifier/Context.php
library/HTMLPurifier/PropertyList.php
library/oauth2-php/lib/OAuth2.inc
library/intl/src/Formatter/NumberFormatter.php
library/Smarty/libs/sysplugins/smarty_internal_method_gettemplatevars.php
library/Smarty/libs/sysplugins/smarty_internal_debug.php
library/Smarty/libs/sysplugins/smarty_internal_compilebase.php
library/Smarty/libs/sysplugins/smarty_internal_compile_if.php
library/Smarty/libs/sysplugins/smarty_internal_compile_while.php
library/Smarty/libs/plugins/function.html_select_time.php
library/Smarty/libs/plugins/function.html_select_date.php
library/Mobile_Detect/Mobile_Detect.php
library/jqupload/server/php/UploadHandler.php
library/blueimp_upload/server/php/UploadHandler.php
library/oauth.php
Zotlabs/Web/HttpMeta.php
Zotlabs/Zot/Receiver.php
Zotlabs/Zot/Auth.php
vendor/sabre/vobject/lib/Sabre/VObject/Splitter/ICalendar.php
vendor/sabre/dav/bin/migrateto17.php
vendor/sabre/dav/lib/Sabre/DAV/Browser/GuessContentType.php
vendor/sabre/dav/lib/Sabre/CardDAV/Plugin.php
vendor/sabre/dav/lib/Sabre/CardDAV/Card.php
vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php
vendor/sabre/dav/lib/Sabre/CalDAV/SharingPlugin.php
vendor/sabre/dav/lib/Sabre/CalDAV/CalendarObject.php
include/ConversationObject.php
include/smarty.php
include/ItemObject.php
include/attach.php
include/socgraph.php
include/template_processor.php
include/enotify.php
include/chat.php
include/zot.php
include/text.php
include/oembed.php
include/account.php
include/config.php
include/apps.php
include/conversation.php
include/import.php
include/event.php
include/permissions.php
include/plugin.php
include/api.php
include/crypto.php
include/probe.php
include/deliver.php
include/network.php
include/photos.php
include/identity.php
include/notifier.php
include/widgets.php
include/follow.php
include/dir_fns.php
include/api.php.txt
include/bb2diaspora.php
include/items.php
include/comanche.php
include/photo/photo_driver.php
include/Contact.php
extend/addon/hzaddons/jappixmini/jappix/php/gettext.php
extend/addon/hzaddons/redphotos/redphotohelper.php
extend/addon/hzaddons/gnusoc/gnusoc.php
extend/addon/hzaddons/diaspora/diaspora.php
extend/addon/hzaddons/superblock/superblock.php
extend/addon/hzaddons/js_upload/js_upload.php
boot.php
index.php
mod/rbmark.php
mod/mitem.php
mod/wall_attach.php
mod/events.php
mod/update_home.php
mod/dirsearch.php
mod/rpost.php
mod/menu.php
mod/import.php
mod/admin.php
mod/profiles.php
mod/item.php
mod/post.php
mod/ratings.php
mod/thing.php
mod/connect.php
mod/update_public.php
mod/linkinfo.php
mod/sslify.php
mod/mood.php
mod/photos.php
mod/settings.php
mod/import_items.php
mod/update_network.php
mod/directory.php
mod/poke.php
.openshift/action_hooks/deploy
```
i can take a look to see if there are similar issues.

**Comment by redmatrix** [comment]
What we need to find is what function is calling set_pconfig without a valid uid/channel_id (I'm guessing the value in this case is 'false' which is what local_channel() returns if you aren't logged in). The only way to do this easily is to do a backtrace in set_pconfig if the uid is something other than a positive integer. Once we've found out where this function is being called with an invalid uid we can figure out how to fix it. array_key_exists is not the problem. 

if(! intval($uid)) {
    logger('set_pconfig called without a uid.',LOGGER_NORMAL,LOG_ERR);
          if(version_compare(PHP_VERSION, '5.4.0') >= 0) {
            $stack = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
            if($stack) {
                foreach($stack as $s) {
                    logger('stack: ' . basename($s['file']) . ':' . $s['line'] . ':' . $s['function'] . '()',LOGGER_DEBUG,LOG_ERR);
                }
            }
        }
}

**Comment by jeroenpraat** [comment]
Do  I need to put that code starting with if(! intval($uid)) somewhere @redmatrix ?

**Comment by redmatrix** [comment]
It's all done - but you really should look at your logifle occasionally for 'stack:' reports from set_pconfig so we can find the source of the problem. It doesn't occur on my site so there's nothing for me to find.

**Comment by jeroenpraat** [comment]
Ok, thanks. I will keep an eye on it. Closing for now.
