### ISSUE TITLE
BUg can't delete or remove extra Channel

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#320]
Issue:
1.- Create and other channel Feeds 
2.- try to delete channel 
3.- Write password and click in delete 
4.- Channel is not delete 

I believe is a issue with the new change password feature . First the new extra channel not recognize the main password from the user . Change the password and write again setup the password for the extra channel but delete the channel with password not work . And not messages of Error Show Up

**Comment by redmatrix** [comment]
Channel deletion is denied if the account password has been changed in the last 24 hours. This is a security measure and is reported in a console message. We may not need this security feature now that we ask for the original password to change it. I've just tried deleting a channel from an account that did not change their password in the previous 24 hours and it works fine. If you have changed the account password in the previous 24 hours it will fail.

**Comment by royalterra** [comment]
@redmatrix yesterday I login in my phone and I go to the channel and delete the channel before 24 Hours look only you need a difference browser and you not need to wait 24Hours . Today I create and other channel and delete and look to works only issue I can see not delete the cookies and the Icon Home not show nothing, Only Register works in the browser and Logout is like you are login on .

**Comment by royalterra** [comment]
I look again in this a good solution is after delete a channel redirect automatic to url "LOGIN"

**Comment by royalterra** [comment]
I also observe I am 100% sure I am in the new channel and after click delete take very long time and the primary channel and the new channel are delete in ones . I not mind because I can recover a nightly backup but is surprising bot channels are delete

**Comment by royalterra** [comment]
No repeat issue again close ticket
