### ISSUE TITLE
Delete Messages from INbox and Inbox Slow

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#325]
I have tons of messages people send me privately Open the Inbox become slow when  the rest of the web look run faster. Is any system to delete all the messages from Inbox faster? Delete messages one by one is take me ages

**Comment by redmatrix** [comment]
I assume you've tried 'Delete Conversation' (?) which of course deletes an entire conversation as opposed to individual messages.

**Comment by royalterra** [comment]
Yes is correct possible is because conversations is load showing all the people you have talk and is possible have hundred of links go down a option can be for not make a load is hide that with a single link like is Inbox OutBox and only when you clock in conversations will show all the list. I can't repeat the issue in a server is activate HHVM  but if I left Apache in his own with phpX us normal need to be the load slow considerable open the Private Email
