### ISSUE TITLE
All content of all channels marked as adult when not logged in

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#33]
When visiting a channel (e.g. https://hubzilla.nl/channel/rms) on my new hub when not logged in*, all content is marked with 'Possible adult content - Click to open/close'. This is true for cloned channels and newly created channels (e.g. https://hubzilla.nl/channel/testing). Toggling 'Adult Content' in channel settings (that is by default 'off') has no effect at all.

* not logged in means also not remotely authenticated.

**Comment by redmatrix** [comment]
There was an obscure config someplace that makes all your channels adult/censored and doesn't let you over-ride it. I'll have to try and find it; though I also notice the nsfw addon is using the old xchan_flag fields to determine that it's an adult channel and that needs to be fixed.

**Comment by redmatrix** [comment]
Should be fixed - pull hubzilla-addons

**Comment by jeroenpraat** [comment]
Works! Thanks Mike.
