### ISSUE TITLE
Archived connections are not visible in ACL selector

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#330]
The thing is we still try to send posts if they are archived. This might be an security flaw in certain situations.

Either we should not attempt to send messages to archived connections or we keep sending them but than also show them in the acl selector.

In the latter case the fix is to remove `and abook_archived = 0` from the query in mod/acl.php on line 96

**Comment by redmatrix** [comment]
The technical description of the archived flag is that we won't waste resources *polling* these connections. They do sometimes get archived in error and direct delivery is still performed until either the hubloc or site is marked dead. So I'm going with option 2. Will check it in shortly.

**Comment by git-marijus** [comment]
I agree with option 2
