### ISSUE TITLE
"xzy wrote the following post x minutes ago" doesn't make sense for posts

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla#331]
When someone forwards a post then the a heading is generated in the format:

```xzy wrote the following post x minutes ago```

Especially when the post is send to other systems then the relative time value doesn't make any sense. It only make sense when viewed locally because the time value can be rendered just when viewing it.

**Comment by redmatrix** [comment]
As noted a year ago - ideally a timeago.js compatible span/div which will render as a date string on pages which don't have timeago and will update automatically on pages with timeago.

include/bbcode.php:247

   /** @FIXME - this should really be a wall-item-ago so it will get updated on the client */
    $reldate = (($posted) ? relative_date($posted) : '');
