### ISSUE TITLE
users can't upload pictures

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#350]
3 hubs stop upload pictures with not reason any ideas?
Thanks 
2016-04-20 23:08:54:LOG_INFO:7466ea921ebf08502d31cae017a05207:attach.php:1419:find_folder_hash_by_attach_hash: attach_hash: 8be3cf69d6cedf4aa61d523020fcbf56bdd39357c633918ca1125e8fb99a109e
2016-04-20 23:08:54:LOG_INFO:7466ea921ebf08502d31cae017a05207:photos.php:147:photo_upload: photo_upload: unable to process image
2016-04-20 23:08:54:LOG_INFO:7466ea921ebf08502d31cae017a05207:zot.php:2940:build_sync_packet: build_sync_packet

**Comment by anaqreon** [comment]
I cannot reproduce the problem in either

* Version 2016-04-21.1373H+540800d, Tag: 1.4.2
* Version 2016-04-14.1366H+a29c037, Tag: 1.4

I can upload files in both Files and Photos apps.

**Comment by royalterra** [comment]
Is only show Up with few USERS but that cost me one Admin left Hubzilla and reinstall other software. 29 users already gone :-1: 
Anyway the problem is when you go to upload a picture in a post the picture go in a folder name actualmonth/year example 04-2016 or something like that .
Now if the user like to upload the picture look Hubzilla can't find that folder and abort upload . I try in photos Upload and the seam problem with certain users. I try in Upload Photos change the folder name for other folder and NOW YES that use can Upload Pictures in the NEW FOLDER but the problem continue in UPLOAD INSIDE POST.
Like I say is only in certain users have that problem and only few keys HUBS the problem is also in users have CLONES in other HUBS 
I can think one is a problem relate to clones or some one got any new idea to hack webdav and delete folders

**Comment by royalterra** [comment]
I can look is also affected my user but yes I can see UPLOAD THE PICTURES but not show the link in the post  2016-04 The POST keep in BLANK like nothing is UPLOAD

**Comment by anaqreon** [comment]
I just attempted a photo upload using the post editor "attach" button. The photo uploaded and was successfully displayed when I used the "preview post" feature.

Version 2016-04-21.1373H+540800d, Tag: 1.4.2

**Comment by royalterra** [comment]
OK Now I got a SOLUTION but that NOT SOLVE WHY IS THIS ISSUE AND WHAT TO DO FOR NOT HAPPENS AGAIN. I am really upset with loss one HUB because people no trust the system. Possible can be good make a WIKI of ISSUES and how to SOLVE if any give me acces to the WIKI I will like to start posting issues and solutions

Solution Temporally because we not have idea why is this problem is:
1.- Go to the URL of the HUB/Cloud  
2.- Delete The Folder of the actual month/year 
3.- Go to Post and Upload a Picture now works 

That solution make you will loss all the pictures of the actual Month

**Comment by anaqreon** [comment]
You still haven't mentioned the hub version. If this is a production hub where you want to minimize bugs, I recommend you keep it at a tagged release. Currently this is 1.4.

You probably know this already, but for the sake of other readers: Only experimental, development hubs should be running on the dev branch, and anything on master branch past a tagged release should be considered beta and not suited for production hubs.

**Comment by royalterra** [comment]
2016-04-21.1373H - 1165

**Comment by royalterra** [comment]
Possible will be good a option in ADMIN to deactivate webdav , clon or import profiles. I believe the admin need to have the freedom how to secure or deactivate services can compromise the HUB

**Comment by redmatrix** [comment]
> Possible will be good a option in ADMIN to deactivate webdav , clon or import profiles. I believe the admin need to have the freedom how to secure or deactivate services can compromise the HUB 

We're working on that. By "we" I mean **I'm** working on that, along with a thousand other things. You can always rename a module file to prevent that module from running. By version 2.0 I'm hoping to have a site features list to let you pick what features you want to enable on the hub. 

What I've tried here is to go to Settings and change my default folder to one that doesn't exist, and then upload a photo into a post. That worked just fine for me. The new folder was created and the photo was uploaded into it. So we don't have the important information to re-create this bug. 

> anything on master branch past a tagged release should be considered beta and not suited for production hubs

I disagree with this. Anything past a tagged release includes bug fixes which have been specifically applied to master (but not including any dev code which is being developed and tested for the next release). The current master should now be the most stable and up-to-date code for production.

**Comment by anaqreon** [comment]
Then what is the point in tagging releases?

**Comment by redmatrix** [comment]
> Then what is the point in tagging releases?

That is a complex issue which belongs in another topic.

Anyway for completeness I also uploaded a photo into a post into an existing folder. This also went without incident and the photo was uploaded as it should have been. I then tried again with a new folder that didn't exist and it also worked. So it appears the issue may be dependent on some configuration that is unique to the server/hub.

If one (e.g. a server administrator in this case) is able to re-create an issue reliably, one (e.g. a server administrator) should be able to debug it and find out why - and fix it and share the fix so that it doesn't occur in the future and the community benefits from the improvements. This is in fact the basis of open source software.

**Comment by royalterra** [comment]
I not have idea why become that bug and I look all the logs when produce but the problem possible is long time ago before. About the releases  I upgrade the hub looking for a solution but upgrade release not make changes. And overwrite hubzilla with a new git pull also to make changes.
What users and hubs have the issue: Is only reproduce in certain users of a HUBS (ADMINS) in the rest of users work fine  for what I believe is not a miss configuration of the HUB. My idea is some one got a system to hack webdav and target the admins accounts and damage the folder links.

**Comment by Rocksteady18** [comment]
this is a huge problem for me, I can't upload any pics, hubzilla is up to date.  How can I fix it?

**Comment by redmatrix** [comment]
Do the photos get uploaded to your Files area? If not, check that the 'store' directory is writeable by the webserver. We have an addon called 'upload_limits' which you can install and if you visit /upload_limits on your site it will report if you are encountering configuration memory limits. 

If the photos are uploaded to the file area but don't make it to the photo albums, it is likely a limit of the total memory available to PHP on the system. 

Otherwise there aren't any current issues with photos that I'm aware of.

**Comment by royalterra** [comment]
The problem in someone can be upload limit other issue can be round user permission
chown -R www-data:www-data /var/www/yourhubzilla
No work that?
Ok go to photos and delete the actual folder with the date that solve the problem for me 
After go and make one post and upload a picture in the post that will recreate the folder and upload the picture

**Comment by Rocksteady18** [comment]
Woohoo, you both gave me great clues and now she works like magic!  I did

    ps -ef | grep httpd | grep -v grep

Which showed me that apache is calling with daemon, not www-data as I assumed as well.  I changed ownership and now it works like a charm.  Hope this helps someone.  Amazing software guys, thanks!
