### ISSUE TITLE
bbcode autocomplete is not loaded when using /rpost

### ISSUE THREAD

**Issue by anaqreon** [redmatrix/hubzilla#357]
Not sure how many people use the /rpost page to create posts, but the JavaScript that supports the autocomplete must not be loading there.

**Comment by git-marijus** [comment]
works for me in myhub.com/rpost

**Comment by anaqreon** [comment]
I was running **Version 2016-04-15.1367H+ce34c40**, Tag: 1.4. Now I'm running **Version 2016-04-26.1378H+563e82f** and it works.
