### ISSUE TITLE
White screen when applying profile photo's to channels

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#36]
I don't know if this is the same issue as issue #7, but I can't apply any photo to any channel (new and imported/cloned). It's uploaded to the photo storage, but when I want to apply it from there (/profile_photo/use/....) or from /profile_photo I get a white screen.

**Comment by jeroenpraat** [comment]
In the channel, xchan and profile tables the profile image is pointing to https://hubzilla.nl/photo/profile/l/22 or https://hubzilla.nl/photo/profile/m/22. That's my default hub avatar, but I uploaded something similar to my well known avatar.

**Comment by jeroenpraat** [comment]
Has it maybe to do with this commit? https://github.com/redmatrix/hubzilla/commit/6cc60ba477c1634b2ba6d78495d35cbf306988e1

**Comment by jeroenpraat** [comment]
More info from php.out (please note that redmatrix.nl on the same VPS doesn't give these errors):

```
[08-Sep-2015 23:34:29 Europe/Amsterdam] PHP Fatal error:  Uncaught exception 'ImagickException' with message 'no decode delegate for this image format `' @ error/blob.c/BlobToImage/358' in /var/www/hubzilla/include/photo/photo_imagick.php:34
Stack trace:
#0 /var/www/hubzilla/include/photo/photo_imagick.php(34): Imagick->readimageblob('store/jeroenpra...')
#1 /var/www/hubzilla/include/photo/photo_driver.php(71): photo_imagick->load('store/jeroenpra...', 'image/png')
#2 /var/www/hubzilla/include/photo/photo_driver.php(13): photo_driver->__construct('store/jeroenpra...', 'image/png')
#3 /var/www/hubzilla/mod/profile_photo.php(345): photo_factory('store/jeroenpra...', 'image/png')
#4 /var/www/hubzilla/index.php(339): profile_photo_content(Object(App))
#5 {main}
  thrown in /var/www/hubzilla/include/photo/photo_imagick.php on line 34
```

**Comment by bashrc** [comment]
I think I'm also seeing this. I can upload a photo, but if I try to apply it as a profile photo then I just see a blank screen and the new image doesn't take effect.

**Comment by redmatrix** [comment]
Was this before or after applying the above referenced patch? 

https://github.com/redmatrix/hubzilla/commit/e8d431c2f641221712cce974eced27d600c168c1

**Comment by jeroenpraat** [comment]
@redmatrix This is now partly solved. I can now set a new profile photo via the photo album (profile_photo/use/....), but still not via profile_photo. It gives the same errors in php.out.

**Comment by redmatrix** [comment]
I've managed to get a bit further.

**Comment by bashrc** [comment]
After a git pull it duly works. Thanks.

**Comment by jeroenpraat** [comment]
Great, works now completely!
