### ISSUE TITLE
Improve UI for viewing (dis)likes

### ISSUE THREAD

**Issue by anaqreon** [redmatrix/hubzilla#367]
A very minor change could provide usability improvement if anybody wants to tackle it. It's basically the list of "likes" (and dislikes, and attending, agree, etc.). If you click the button you get up to the first ten channels that reacted. If there were more than that, you need to click through to a second popup to display them all. I'd recommend we get rid of the first popup and just go straight to the second. It was useful in our older UI where you would see a hovertip with the first ten and got the rest of you clicked, but we don't do that any more and in any case hovertips aren't mobile friendly.

**Comment by git-marijus** [comment]
I'd suggest to automatically open the modal only if there are more than 10 likes and leave it as is if there are less...
Having a modal popping up for e.g. two likes seems a bit overkilll...
