### ISSUE TITLE
Module/Pubstream is not working

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#373]
What it says... Have not investigated further yet...

**Comment by redmatrix** [comment]
Check admin->site->Import Public Streams and also admin->security->Block Public; both of which will turn this into a blank (but themed) page. We may need a message that the public stream functionality is not enabled on this site.

**Comment by git-marijus** [comment]
They are both set right... I suspect an issue with $load and $update...

**Comment by git-marijus** [comment]
Ha! Thanks...
