### ISSUE TITLE
Version numbering dev

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#384]
The most stable release (master) is now 1.6.3.. The development branch says 1.7. This is confusing, because it doesn't mention 'dev' in the release name. I already saw some hubs reporting that they have 1.7 (like on Hubchart). People will think that these hubs are running the most recent stable release and that hubs running 1.6.3 do not have the most recent stable release. 

To avoid this I suggest changing 1.7 to 1.7.dev, dev.1.7 or any other name to avoid the above described issue.

**Comment by git-marijus** [comment]
We should spread the news that (like in many other open source projects) odd second digit stands for development version and even second digit stands for stable version.

**Comment by jeroenpraat** [comment]
Do we? 

Personally I find that confusing too. We should somehow make clear that it's the development branch.

**Comment by git-marijus** [comment]
You might have missed this thread: https://macgirvin.com/display/4f40cb74b2e7d4b77207f9b6713579d5fb04000af4ac19512887635937c243b0
