### ISSUE TITLE
Unintentional change of my theme schema when I visit a profile page

### ISSUE THREAD

**Issue by mjfriaza** [redmatrix/hubzilla#390]
A possible bug? This happens: my theme scheme is focus, but when I visit the profile of a connection, whose scheme is black, mine automatically switches to black too. To return to focus, I have to go my display settings and change it again :-(... Any idea?

**Comment by jeroenpraat** [comment]
Did you also tried my profile?

**Comment by jeroenpraat** [comment]
Can you also visit the Hubzilla.nl admin channel with the blue schema?

**Comment by jeroenpraat** [comment]
I found the problem. It is actually in my themes. Those are themes that set redbasic schema's more easily ([repo here](https://github.com/jeroenpraat/hubzilla-themes)).

Maybe @redmatrix can help me?

I have in the theme files style.php and theme.php this line at the bottom:
`set_pconfig(local_channel(), 'redbasic', 'schema', 'simple_white_on_black');`

I did this, because every time the member went to another page in his Hubzilla environment, the schema switched back to the default (focus). To solve this I had to put this line here, so the correct schema is every time written to the database . I know this is a very ugly hack and now it even seems it has some unwanted side effects. So my question is if there's a better way to solve this?

**Comment by mjfriaza** [comment]
> Did you also tried my profile?

> Can you also visit the Hubzilla.nl admin channel with the blue schema?

Yes to both. No problems  with these channels.

**Comment by redmatrix** [comment]
In boot.php:current_theme():L1902 appears to be a solution, but I question whether it is a universal solution as it requires App::$profile_uid (this is only set on personal pages and not on system pages). So basically this solution uses your own theme when viewing any personal page on your site. I've never tested this incidentally. 

I would suggest that current_theme() is the place you want to fix this, but be aware that lots of theme setting hacks have been applied by previous travelers to this code and as a result it is a tangled mess. One would be doing everybody a favour by fixing this mess and giving it a logical flow that achieves all the desired results.

**Comment by jeroenpraat** [comment]
Thanks for replying @redmatrix . I have for now disabled my theme repo and modified the theme configs of those few channels using those thmes. When I have more time, I will try to fix it with the info you gave me. 

Closing bug, cause it's not a core issue.

**Comment by jeroenpraat** [comment]
@redmatrix Sorry to disturb you with this, but I'm try to understand how to get this working.

I removed the line `set_pconfig(local_channel(), 'redbasic', 'schema', 'schema-name');` in style.php (in a derived theme) but it still changes the viewers schema unintentionally. 

Where do I have to look for in my derived themes? Or is this now somehow possible in core?

**Comment by jeroenpraat** [comment]
@redmatrix Do you have time to help me with this question? ^^^^^^

**Comment by redmatrix** [comment]
All of the theme handling functions now take theme:schema. Set your theme to e.g. redbasic:dark 

Currently you would need to do this in the database (channel.channel_theme), but if it all works correctly I would recommend modifying the theme setting page to do this when setting the theme

**Comment by jeroenpraat** [comment]
OK, so I understand that I don't need a derived theme anymore to accomplish this, but the Theme settings page need to be changed somehow. Isn't it easier to move the schema selector just below the theme selector?

**Comment by jeroenpraat** [comment]
This is not a good place to discuss this. I will try something first and come back to you if I have questions.
