### ISSUE TITLE
edit post with quotes in title, quotes turned into escaped html entities

### ISSUE THREAD

**Issue by redmatrix** [redmatrix/hubzilla#391]
Per Waitman

https://hub.zilla.tech/display/b7a66aeeb2fbb67208ebfbf4fc5ad152a6898d9bb8e078633e5dbea6e334d95d@hub.zilla.tech

**Comment by mjfriaza** [comment]
I published a post test and everything is OK.

**Comment by mjfriaza** [comment]
Stop! When editing the post, the problem returns.
