### ISSUE TITLE
Plugin repo GUI in admin/plugins page does not link new plugins when updating

### ISSUE THREAD

**Issue by anaqreon** [redmatrix/hubzilla#392]
Plugins are only linked to /addon when a new repo is installed. The update button needs to symlink new and delete old plugins after the update is pulled.

**Comment by anaqreon** [comment]
Symlinks new plugins but does not delete stale /addon links:

https://github.com/redmatrix/hubzilla/pull/394

**Comment by redmatrix** [comment]
Two very minor feature requests - 

- put repository management in a collapsible section by default
- add a bit of vertical whitespace between repositories in the display, they seem a bit scrunched

**Comment by anaqreon** [comment]
https://github.com/redmatrix/hubzilla/pull/395
