### ISSUE TITLE
500 Error when posting status update

### ISSUE THREAD

**Issue by DeadSuperHero** [redmatrix/hubzilla#398]
I'm not entirely sure whether this is applicable to an update to Hubzilla itself, or whether it is because I performed a server upgrade earlier today. Regardless, I have an unusual issue:

Any time that I try to post a new update, this happens:

![image](https://cloud.githubusercontent.com/assets/401560/15412748/a9914940-1def-11e6-8b99-2c0169443cf3.png)

I seem to get directed to zothost.tld/item, with a 500 error. The status itself does indeed appear to post on my hub, but it doesn't seem to federate out or cross-post.

Would anyone have some tips on things that I should try checking on my server?

**Comment by redmatrix** [comment]
Create a PHP log if you don't have one already. Instructions are at the end of .htconfig.php - check it after you get the 500. I'm guessing that there may be a missing php module after the upgrade.

**Comment by DeadSuperHero** [comment]
Thanks for that. 

> PHP Fatal error:  Call to undefined function mcrypt_decrypt() in /srv/deadsuperhero.com/hubzilla/include/crypto.php on line 64

I looked into the matter, it appears that the main issue is in having mcrypt disabled and my universe repository turned off. After reinstalling it, re-enabling the extension in PHP, and restarting nginx, it appears that the problem still persists, although this time with a new error:

> PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /srv/deadsuperhero.com/hubizlla/addon/diaspora/diaspora.php on line 126

I'm not quite sure what needs to happen here, but I still seem to be getting the same problem as before.

**Comment by redmatrix** [comment]
> PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /hubizlla/addon/diaspora/diaspora.php on line 126

This was fixed a week or so ago and the fix was backported to the master branch so should clear up on a git pull.

**Comment by DeadSuperHero** [comment]
Hm, I seem to be on the latest master branch as it is. Is there anything I should try from my end?

**Comment by redmatrix** [comment]
See if the line in question (diaspora.php:126) looks like this:

  if(! array_key_exists('item_wall',$arr['target_item']))
        return;

In the buggy version it used $arr['item'] instead of $arr['target_item'].

**Comment by DeadSuperHero** [comment]
I've fixed it; it appears that the main issue was some php5 libraries were removed when upgrading versions of Ubuntu. Sorry for the annoyance, but thank you for the help! :)
