### ISSUE TITLE
installation with nginx fails with htaccess error

### ISSUE THREAD

**Issue by Razlo** [redmatrix/hubzilla#401]
I have installed hubzilla in a Debian 8 machine with MariaDB and nginx server. I read that "some folks have managed to use nginx", so I used the provided config here https://github.com/redmatrix/hubzilla/blob/master/install/sample-nginx.conf

However, the installation wizard fails with this error:
```
Url rewrite in .htaccess is not working. Check your server configuration.Test: array ( 'return_code' => 200, 'success' => true, 'header' => 'HTTP/1.1 200 OK Server: nginx/1.6.2 Date: Sun, 22 May 2016 19:11:12 GMT Content-Type: text/html; charset=UTF-8 Transfer-Encoding: chunked Connection: keep-alive Set-Cookie: PHPSESSID=8ntcab6r82dkudg42dqs208qj5; path=/ Expires: Thu, 19 Nov 1981 08:52:00 GMT Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0 Pragma: no-cache ', 'body' => 'ok
Fatal error: Call to a member function close() on null in /var/www/hubzilla/boot.php on line 1659
', )
```
I don't know how to solve it, as nginx doesn't have such a thing as .htaccess files. Moreover, if Hubzilla wants to be compatible with other web-servers, we should rethink this check.

By the moment, how can I work around this?
Thank you!

**Comment by anaqreon** [comment]
I haven't considered the specific details of your problem, but you might find the nginx config I made for the YunoHost Hubzilla package helpful: https://github.com/YunoHost-Apps/hubzilla-yunohost/blob/master/conf/nginx.conf#L24

**Comment by redmatrix** [comment]
The actual error here is the $db-close call, which shouldn't be called during installation (before you've told hubzilla how to open the database). This bug was in the repositories for only a couple of days before it was found and fixed. I believe all should work well if you update your sources.

**Comment by Razlo** [comment]
Thank you! a simple git pull worked for me :)
