### ISSUE TITLE
Ratings from accounts that no longer exist

### ISSUE THREAD

**Issue by mjfriaza** [redmatrix/hubzilla#406]
Hi to all!
I have 2 ratings from accounts that no longer exist hermesgabriel@blablanet.es and un@lastauth.com How you can delete? You can be considered a bug?

**Comment by git-marijus** [comment]
Mike wrote:
> It's a bug, but there is no easy solution because ratings are stored in the directory and the directory is mirrored. So if we remove it from one directory it will still be there. You kind of have to remove it from all directories and we don't have a mechanism to do this.
> 
> The other peculiar thing about ratings is that by design they can only be changed by the creator by sending a signed packet to the directory - which then mirrors it to other directories, who all verify the signed packet. This way we ensure there's no hanky-panky or ballot-stuffing.
> 
> So I don't have a good answer at the moment.
