### ISSUE TITLE
Notifier does not forward items with "item_hidden" set to 1

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#409]
This is a quite recent change in /Zotlabs/Daemon/Notifier line 281
It breaks file activities since by design they have item_hidden set to not show up in the stream.

**Comment by git-marijus** [comment]
The issue was fixed in a10f5e9e06a03789af8f08481409f0ac95059fed
Leaving it open since we might want a more appropriate fix for this...

**Comment by redmatrix** [comment]
commit 0ef2622 potentially makes the item_notshown flag useful as an alternative to item_hidden. A potential problem is dealing with prior versions where this flag was not supported. I might suggest starting to use item_notshown (in addition to item_hidden) and providing a (hard-wired or documented) time-to-live in the Notifier code where we allow file activities with item_hidden. 

Jan.1 2017 support for older zot protocol clients will go away, so this might also be a convenient end-of-life for item_hidden on file activities unless you can think of any better solutions.
