### ISSUE TITLE
Titles of Apps are not translated

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#421]
In the past (I don't know exactly when) the titles of Apps where translated. Like 'Language' to 'Taal' in Dutch. Those are not translated anymore, so they only show in English.

Of course you can edit the apps and rename them to your native language, but I don't  think that this desirable.

**Comment by redmatrix** [comment]
https://github.com/redmatrix/hubzilla/commit/476116a972c0f8b8ade495de557b8fc8d3097964

**Comment by jeroenpraat** [comment]
Thanks!
