### ISSUE TITLE
Shutting down Mysql Connection

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#423]
Possible is the reason of the other ticket about photos Upload but is possible to send the server mysql connection away when search engines or anyone use external links 
Example: `https://XXXXXX.by/images/search?p=3&text=%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D1%8B%D0%B5%20%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8&img_url=http%3A%2F%2Fapi.ning.com%2Ffiles%2FpHhBdYiNnuKDjk1xR6jgLXRXRW9IamiZlmgjYtg41-8QS81Ay7s2QDF9r6DoX-3kGdOyd4pW*Q3gb9FQO6DRkAe*LaPMoxCP%2FTechnologyandtalkfusion.jpg&pos=116&rpt=simage`
That link of one image upload for a Hubzilla User produce
mysqli::query(): MySQL server has gone away /var/www/xxx/include/dba/dba_mysqli.php on line 28
and the error
mysqli::query(): MySQL server has gone away /var/www/xxx/include/dba/dba_mysqli.php on line 28

That is a serious issue

**Comment by redmatrix** [comment]
image uploads are from files on the local file system, not urls. I'm not following from this description what sql query is getting this url and how this url is related to image uploads.

**Comment by royalterra** [comment]
Ok I have a image domain.xxx/photos/userXXX/image/83a26d5bd4a4580feeb5baa8c0e5f95471a925de6c1be8a8537bde043be39e25
Now I make a external link longer of that and I start sending only few resquest to that image. SQL Connection will shut down 
WHy?

**Comment by royalterra** [comment]
The true I imagine this situation before happens I know is possible specially using Jpg or png files linked of any system to the database also when they are store us files .
Last week I notice no only try of force brute logins because we not have a captcha anywhere also try to access to private folders of Hubzilla and seam scam in all Hubs front the seam Ips . No resort anyway the person is waste the time .
And some other HUBS 2 for be specific try to proxy to my HHVM or php FPM front the moment I use sockets and no ports try to  hacking like that is also a waste of time.

HHVM increase the security of HUbzilla and really go faster I can't see any incompatible code or php errors more in the last development versions. I already tested more of 6 months and all look works perfect in Debian and Ubuntu I will pull a how to in the repository if is accepted  .
Hubzilla with php7 show me some complaints but look running ok

Anyway about the pictures I will  scan the logs daily and see if I can find why exactly mysql start dropping the connection but I believe the database table become corrupt and is for that the folder with the month and date stop working 
Delete the folder and upload a new picture recreate the folder solve  that problem temporally

**Comment by royalterra** [comment]
This problem is not repeat again with Hubzilla Version 1.8 I consider for that the problem solve and only affecting to versions <1.4=1.4
I will close for that this Ticket
