### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#427]
Hi I try to upgrade one of the HUBS to the last version using php5.6 but I got 
PHP Warning:  Invalid argument supplied for foreach() in /data/var/www/mydomain/include/group.php on line 283
Any idea how to solve the issue actually users login in and automatic is log out 
Thanks

**Comment by redmatrix** [comment]
Update 1172 was either not applied, or it was applied and you've attempted to load an earlier (1.6.x) version.

If you have updated to either dev or 1.8RC, you should probably check all the DB updates from 1168 upward and ensure they were applied. Once these have been applied, you won't be able to go back to an earlier version.

**Comment by royalterra** [comment]
Hi Thanks I try before to change to branch 1.8 . I not remember the version I have before but is a very old one I got restore a Mysql backup  and overwrite git pull changes to 1.6.6
That make a working HUB again
Thanks for the advice
