### ISSUE TITLE
WSOD after upgrade to 1.8

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#428]
White screen of death after upgrading master to 1.8. PHP error in poller output. 

Poller output:

PHP Parse error:  syntax error, unexpected '<<' (T_SL) in /var/www/hubzilla/boot.php on line 1747

**Comment by redmatrix** [comment]
Should be fixed.

**Comment by jeroenpraat** [comment]
Yes. Thanks
