### ISSUE TITLE
Hubzilla Upgrade

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#430]
Hi I not have idea if I lose any comments in Hubzilla . But I have few hubs version 1.4 I try to make git pull and fail upgrade to the latest version. I try git merge SHA  using different commits and only one hub go true .

is any system to Upgrade easy front old versions??

Thanks

**Comment by redmatrix** [comment]
There were a number of DB updates in the new release. These should have been applied automatically, but in particular there was a change to the item table, and this often causes trouble for people with limited memory. 

Please look at install/update.php and verify that updates 1168 through 1175 were applied. /admin/dbsync may be useful in this case, but we've found that when there's trouble it's best to examine the updates individually and verify that they occurred rather than use the automated tools to try to recover.

**Comment by royalterra** [comment]
Ok Thanks for the help. In my case I not believe is a problem of lag of mysql ram. Anyway your advice give me a idea and  I solve now one possible can help to the rest of people:

First:
git fetch all

Second I will Update Fully version not by SHA
Here people can see https://github.com/redmatrix/hubzilla/releases all the Hubzilla Releases
I start in my case for the full version 1.4 if any one not do before click in the link near the zip link is like one -o- 
and you will see a long hash code in the right after commit : in thast case is a29c0371f1f3cceb9a9af3a62e5ed67886869c40
now I do: git merge a29c0371f1f3cceb9a9af3a62e5ed67886869c40
See the web is UP and running login in the admin activate redbasic theme deactivate all the plugins
go in root and delete all the extra themes front DeadSuperhero remove hubzilla addons 
all that I do because after will complaint some time of plugin files pkwik smilebutton and some one more Need to look in Apache or Nginx logs just in case any one get a blank page and remove the folders manually front addons folder example pwik with rm -R pwik or what ever is call

Now Next stage is easy seam of before go to releases and get the hash for version 1.6 
and make git merge hash 

Test all is working and backup files and database just in case have a starting point 
Again  seam of before go to releases and get the hash for version 1.8
and make git merge hash 

will show possible a blank page for any reason I find PHP Parse error:  syntax error, unexpected '<<' (T_SL) in line 1747 in file boot.php I delete the 3 lines is rubish and not code and now is working order

Install the themes you like install hubzilla addons

**Comment by royalterra** [comment]
Ok Now I just Upgrade 4 but using
git fetch --all
Activate redbasic theme
Deactivate all the plugins
Use git merge with release for version 1.4 
after make chown -R www-data:www-data /yourhubzillaFolder in case you have different apache or ngix user use what ever you are 

Jump again with git merge release to version 1.6
chown the files
Test all is fine make a normal git pull
Now all need to works . Possible this system will solve some of the troubles people have for upgrade Hubzilla front olders versions

**Comment by redmatrix** [comment]
util/safemode on          # disable all plugins (but save the current plugin state to a file)
    util/udall                       # update all repositories, core, themes, addons, etc.
    [if this works then]
    util/safemode off          # re-enable your plugins from the saved plugin list

**Comment by royalterra** [comment]
Thanks @redmatrix that make process more faster and easy.
git pull directly front old versions to the last fail . But git merge 1,4  test and 1.6 and after git pull solve the problem.

**Comment by royalterra** [comment]
That is the easy way with not fails for any one Upgrade to version 1.8 front older versions already tested in many HUBS 



` git fetch --all
Deactivate all your plugins and change to theme redbasic
Root mode:
git merge a29c0371f1f3cceb9a9af3a62e5ed67886869c40
That will jump to latest version 1.4 Check in Admin is working any apache issues check logs or chown your files to apache2 or NGIX example chown -R www-data:www-data /var/www/myhubzilla.domain
Next: 
git merge ac1ec996847235152b61e681ae39d976d3177d4b
Seam of before check ADMIN in the hub and see all working 
Next make a simple **git pull** like always you do before for upgrade now you are in version 1.8
update all your addons and themes with util/update_addon_repo addonName
Themes with util/update_theme_repo ThemeName
Activate your plugins etc Run us Normal next Upgrade use git pull 
`
Time to do the Upgrade less of 5 minutes / Secure and not fails or errors in the Database please backup your files and database before start play with this Upgrade front older versions

**Comment by Treer** [comment]
I had some issues upgrading from 1.6.6 to 1.8 which weren't fixed by clearing the cache but were fixed by deleting all the cookies for the site.

More specifically, every time I clicked on "Channel home", it would draw the channel screen as if I were not logged in, with missing icons and the nav menu at the left offerring me the option to log in, though it still included private posts in the channel - soo some parts of it still thought I was logged in.

**Comment by royalterra** [comment]
Upgrade front 1.6 to 1.8 work fine easy with git pull some issues have some people have I believe solve now with the 1.8.1 please make git pull again
