### ISSUE TITLE
White screen since Monday. Caused by plugin chess?

### ISSUE THREAD

**Issue by einervonvielen** [redmatrix/hubzilla#432]
Since Monday (or Sunday?) I have a white screen (https://digitalesparadies.de) probably after nightly automatic git pull of the master including plugins chess, ownmap and themes (deadsuperhero).

I see an error for git pull of plugin chess in extend/addon/chess
The repository is https://gitlab.com/zot/hubzilla-chess.git
I see an error telling something of untracked working tree files that would be overwritten by a merge.
And - The git pull (of chess) wants a user name now. (Is this new?) I can not remember that a user name was necessary when I installed and pulled it.

I tried to remove the plugins but do not know how to do it from the terminal. I can only find install and update but no script to remove a plugin. (I would use the admin GUI but that is not available because of the white screen.)

Any ideas?

**Comment by redmatrix** [comment]
cd /your/website
unlink addon/chess

**Comment by einervonvielen** [comment]
Worked.
MANY Thanks.
