### ISSUE TITLE
Hubzilla webpages are no longer able to contain stylesheets

### ISSUE THREAD

**Issue by Treer** [redmatrix/hubzilla#447]
If I install the [Hubzilla Project Page](https://gitlab.com/zot/hubzilla-webpage), either manually or via the Hubsites plugin, I end up with a page that's missing its stylesheet.

Specifically, the `hubzilla-project-css` block is empty, and I can't manually edit its content into the block because the editor strips out the `<style>` tags and everything inside them (it looks like this is happening in text.php where `z_input_filter()` invokes `purify_html()`). 

Extra details that probably aren't needed:
* [The content the `hubzilla-project-css` block is supposed to contain](https://gitlab.com/zot/hubzilla-webpage/blob/master/blocks/hubzilla-project-css/hubzilla-project-css.html)
*  the `hubzilla-project-css` block's minetype [is `text/html`](https://gitlab.com/zot/hubzilla-webpage/blob/master/blocks/hubzilla-project-css/block.json)
* You don't need to muck around with hubzilla-project-css - just try creating a block that contains content inside `<style>` tags.

I assume Hubzilla webpages used to be able to include stylesheets because hubs like hubzilla.nl look like they use the Hubzilla Project Page. However I don't know how it used to work, and I don't know what changed, so I'm not sure what the proper approach to fixing it is.

It's been the case since at least 1.6

**Comment by anaqreon** [comment]
The channel owning the block element must have "AllowCode" enabled by the admin ([baseurl]/admin/channels/).

**Comment by Treer** [comment]
In this case, the channel owning the block element *was* the admin channel, but yes - I have confirmed that clicking "Allow Code" on the admin channel allows me to set stylesheet blocks.

I don't know how others will discover it - greping for "allow code" suggests it's currently undocumented, but that's a lesser issue - thanks, for my hub the problem is solved.

**Comment by git-marijus** [comment]
>I don't know how others will discover it

Allow code is a permission that the admin can grant to selected channels he trusts...

Everything else would be a security nightmare...

**Comment by Treer** [comment]
>  >    I don't know how others will discover it

> Allow code is a permission that the admin can grant to selected channels he trusts...
> Everything else would be a security nightmare...

I didn't mean it was a bad feature or should be removed - it makes sense, I was switching to discussion of making the requirement more visible. I'll take it to the discussion happening on Hubzilla now.
