### ISSUE TITLE
PHP warning if mardown syntax *something* is used in a list

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#457]
`PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'Markdownify' does not have a method 'flushStacked_ul' in /library/markdownify/markdownify.php on line 392" while reading response header from upstream...`

**Comment by redmatrix** [comment]
It appears there has been  at least some continued development of Markdownify and the referenced section of code no longer exists therein. We should probably upgrade our distro. It is now installable via composer as well, though the calling sequence appears also to have changed slightly. So this is a "modest" dev task.  

https://github.com/Elephant418/Markdownify

**Comment by zotlabs** [comment]
Thanks to @dawnbreak we have an updated markdownify in dev if this issue can be easily reproduced
