### ISSUE TITLE
Endless loop in gprobe.php?

### ISSUE THREAD

**Issue by zzottel** [redmatrix/hubzilla#47]
I just imported a channel from zottel.red to hubzilla.zottel.net. It lead to a lot of load on the server, as it seems all imported posts/comments are delivered again?

Anyway, after the load had cooled down, there were three apache processes and two php processes left that took as much CPU as they could. Don't really know about Apache, but for the PHP processes I found the following:

- Both are running as user www-data, i.e. must have been started by Apache (cron would be a different user).
- Both are running include/gprobe.php 

So there seems to be the possibility for an endless loop there, though definitely not always. A few test calls with existing and non-existing channel addresses didn't show anything strange, and I can't see anything in the code that could produce an endless loop?

EDIT: I don't know if those gprobe processes had anything to do with the import, nor if they were run by one of the RedMatrix instances on my server or by the Hubzilla instance.

**Comment by jeroenpraat** [comment]
@zzottel  Is this still an issue? If so, please close this issue.

**Comment by zzottel** [comment]
No, I don't think it's still an issue. I'll close it, I think it had to do with more Apache processes trying to get a connection to the database than database connections allowed.

BTW, I do review my bug reports from time to time, but admittedly didn't find time to for a long time now. I'll keep the other one open right now, because it will take some research to even remember what it was about ("as discussed on the grid" :-/ ), and "my" Friday evening is not the time to do that. ;-)
