### ISSUE TITLE
When I click on a Like on my profile, I do not see the author

### ISSUE THREAD

**Issue by mjfriaza** [redmatrix/hubzilla#474]
When I click on a Like on my profile, I do not see the author. Only occurs with multiple profiles. It shows the 'edit profile' menu instead when you click on the like icon. 

![instantanea28](https://cloud.githubusercontent.com/assets/6825241/17364501/c32ae24a-5980-11e6-9d1b-2c1ab1555262.png)

**Comment by jeroenpraat** [comment]
Also fixed. Thanks Mike!
