### ISSUE TITLE
Feed width reduced on PC

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#49]
Just pulled and pushed, and the wall feed's width is very reduced and looks odd on a PC, not on mobile.

**Comment by git-marijus** [comment]
The content is now centered by default and has a width of 790px iirc.
You can change those settings in custom theme settings...

**Comment by HaakonME** [comment]
Wall items are now 422px on my Pinky, not 790px. Why not responsive any more?

**Comment by git-marijus** [comment]
you might want to set it to left aligned in custom theme settings...

**Comment by git-marijus** [comment]
just curious... what screen resolution has your Pinky?

**Comment by jeroenpraat** [comment]
The dark schema has the classic 1024px content width.

**Comment by HaakonME** [comment]
Pinky has a screen resolution of 1024x600 pixels. 

This issue is actually even worse, because Hubzilla is supposed to be an improvement on content creation, but try create a web page with an editor set to 422px. :-/

**Comment by git-marijus** [comment]
settings > display settings > custom theme settings > left align page content > yes
As suggested in my first and second comment...

Does this help your issue or not?

**Comment by HaakonME** [comment]
Yes, it does - thank you! Wish: default. :-)

**Comment by git-marijus** [comment]
I might be able to fix that for you... We can possibly kick out right aside a little earlier...
just a second...

**Comment by git-marijus** [comment]
you can pull now...
