### ISSUE TITLE
Can't connect to RedMatrix channels

### ISSUE THREAD

**Issue by zzottel** [redmatrix/hubzilla#5]
Is that expected at the current state?

If not:

RedMatrix isn't saving my Hubzilla hub to the hubloc table (might as well be a current RedMatrix bug).

zot_gethub() says it doesn't find the hub, then it runs successfully through zot_register_hub() and import_xchan() (the xchan is also added to the xchan table), and that's it. No errors logged.

Next time, zot_gethub() still doesn't find the hub.

**Comment by redmatrix** [comment]
Fixed in hubzilla [master dad4ac6] incorrect value for hubloc_deleted in zot_get_hublocs() query
