### ISSUE TITLE
embedded zcard is not hyperlinked

### ISSUE THREAD

**Issue by zotlabs** [redmatrix/hubzilla#500]
If a zcard is embedded in a post, clicking on it does nothing. It should be hyperlinked to the target channel home. This is complicated because the zcard is a hybrid structure with positional overlays. A possible solution would involve a separate link on the cover photo and profile photo; ignoring the textual elements.

**Comment by zotlabs** [comment]
Turns out to require more than a simple 'a' tag.  This is usually presented inside an iframe so the link also opens inside the iframe. This is less than ideal. If one tries 'target="blank"' (or some other target) this also gets filtered by HTML purifier and appears to be a deprecated HTML construct. I've tried to add link targets to the purifier allowed list but the html-purifier doco is a bit of a contorted mess and my initial efforts were unsuccessful. Leaving this issue open for now.

**Comment by git-marijus** [comment]
Would this possibly solve the issue: http://stackoverflow.com/questions/1037839/how-to-force-link-from-iframe-to-be-opened-in-the-parent-window#tab-top

**Comment by zotlabs** [comment]
Thanks - that works. I was a bit concerned that this might force youtube to also open in another window, but it works correctly. So thanks again. (Haven't tried soundcloud or vimeo but youtube is the 1600 kilo elephant in the room, so as long as that works I think we can live with it).
