### ISSUE TITLE
Bug in notifications

### ISSUE THREAD

**Issue by mjfriaza** [redmatrix/hubzilla#509]
There is a bug that affects notifications. When I put a like in a post, I have a notification such as "Rafa has commented the post of Rafa", being Rafa the author of the post. Specifically, it happens me with giacotoktan@cats-pm and rafapoverello1977@lastauth.com. The two members are in a hub with Hubzilla dev branch, while mine is in the stable branch. Could that explain the error?

**Comment by elvecio** [comment]
cats.pm is not in DEV -> https://cats.pm/siteinfo .

**Comment by mjfriaza** [comment]
Now it happens with more members. It also affects the comments: I comment a post and the notification says that the author of the post is the author of my comment ....
