### ISSUE TITLE
temp_table.id error upon mail creation

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#528]
```SQL
SELECT * FROM ( SELECT * FROM mail WHERE channel_id = 3 ORDER BY created DESC  LIMIT 1 OFFSET 0 ) AS temp_table GROUP BY parent_mid ORDER BY created DESC; returned false
ERROR:  column "temp_table.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT * FROM ( SELECT * FROM mail WHERE channel_id = 3 ORDE...
               ^
```

**Comment by zotlabs** [comment]
@git-marijus could you have a look at this one? It's in the query for the combined mailbox view, and I'm thinking we could possibly simplify it to look more like the inbox or outbox queries and avoid the group by entirely.

There's some discussion of this error at http://stackoverflow.com/questions/19601948/must-appear-in-the-group-by-clause-or-be-used-in-an-aggregate-function, but I'm honestly having a difficult time getting my head around how to accomplish their recommendation in our query.

As a worst case scenario, possibly remove the combined mailbox view and default to inbox. I'm hoping we don't have to do that; just considering all options.

**Comment by git-marijus** [comment]
Besides that this is ugly and makes no sense it could possibly fix the issue...
In include/message.php change line 302 to:

`$sql = "SELECT id, convid, conv_guid, mail_flags, from_xchan, to_xchan, account_id, channel_id, title, body, sig, attach, mid, max(parent_mid), mail_deleted, mail_replied, mail_isreply, mail_seen, mail_recalled, mail_obscured, created, expires FROM ( SELECT * FROM mail WHERE channel_id = $local_channel ORDER BY created DESC $limit ) AS temp_table GROUP BY parent_mid ORDER BY created DESC";`

Cant test here...

**Comment by git-marijus** [comment]
On the long term we should probably use conv table to get this infos... We don't currently save incoming message there though iirc... Would need to dive deeper into this again... Looks like some work that Thomas started at some point but didn't really finish?
This will make some breaking changes though i guess...

**Comment by git-marijus** [comment]
Otherwise i don't know how to easily get the latest message of a thread...
