### ISSUE TITLE
Voting tools not showing

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#53]
Voting feature is enabled. I can select voting during post creation, but after I submitted the post the voting tools are not showing. When I edit the post, the voting icon is deselected again. Selecting it and resubmitting the post does not help.

When I look up the post in the item table, I see the item_consensus is not set (defaulting to 0). When I manually set it to 1, the voting tools become visible on my hub.

@tuscanhobbit experencied the same issue this morning (EU time).

**Comment by redmatrix** [comment]
Unable to reproduce.

**Comment by jeroenpraat** [comment]
Thanks
