### ISSUE TITLE
Master.php

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/hubzilla#532]
hubzilla/Zotlabs/Daemon/Master.php

`require_once('include/cli_startup.php');`

that file is.

[![imagebin](http://upimage.mamalibre.com.ar/up/2212473ac05600f39ce62ac350b1f883.jpg)](http://upimage.mamalibre.com.ar/#2212473ac05600f39ce62ac350b1f883.jpg)

high CPU usage

**Comment by zotlabs** [comment]
Importdoc merely indexes our help files so they can be searched. If it's running for 4 hours there's something very very wrong. 

Externals pulls public content from at most 3 sites. 

An issue I see here is that you're running both include/externals.php (which no longer exists) and the daemon version Zotlabs/Daemon/Externals.php

so your installation is probably buggered somehow. This shouldn't be possible if you updated using git. 

In any event, these are all 'scheduled tasks' which run in the background to process the queue and update various tables. You should be able to kill them and start fresh on the next scheduled cron run without any serious side effects.
