### ISSUE TITLE
New profile image fail

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#533]
Any idea why?

IP-address - - [25/Sep/2016:11:56:06 -0400] "GET /view/css/mod_profile_photo.css?v=1.13.3 HTTP/1.1" 304 - "https://zot-mor.rhcloud.com/profile_photo" "Mozilla/5.0 (Android; Mobile; rv:22.0) Gecko/22.0 Firefox/22.0"
[Sun Sep 25 11:56:06 2016] [error] [client 127.6.95.1] PHP Warning:  fopen(store/haakon/735c5b2a0b2f8e9390a3433ad392158edd25912a38da70eee0a89f6aa43c14f4/53dec96d4d390b67b8bf5adc7defb078bba326677e7e5319148b5900c3df4aa3): failed to open stream: No such file or directory in /var/lib/openshift/55999305e0b8cd838f000053/app-root/runtime/repo/Zotlabs/Storage/File.php on line 258, referer: https://zot-mor.rhcloud.com/view/theme/redbasic/php/style.pcss?f=&puid=7&v=1.13.3

**Comment by git-marijus** [comment]
This issue seems to have fixed itself... Closing
