### ISSUE TITLE
image-0.jpg is on disk, but is not available to Hubzilla

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#534]
image-0.jpg images are stored in store, available on disk and through webdav, but are not available to Hubzilla. I first discovered this 11 days ago when I included image-0 images in my portfolio challenge 15 days ago, and again today when I tried to change my profile photo. The new profile photo was uploaded, but is not read. I suspect something happened somewhere between 15 and 11 days ago.

**Comment by zotlabs** [comment]
I can't duplicate so this may be site specific. You might first try a smaller photo and see if size is an issue.

**Comment by git-marijus** [comment]
I am pretty sure this is an issue with your hub @HaakonME.
Maybe os storage permissions?

**Comment by git-marijus** [comment]
This seems to have fixed itself... Closing
