### ISSUE TITLE
Path to nginx and lighttpd sample config files -- error in INSTALL.txt

### ISSUE THREAD

**Issue by arunisaac** [redmatrix/hubzilla#536]
In line 77, install/INSTALL.txt says sample config files for nginx and lighttpd are in doc/install. But, they actually are in install/sample-nginx.conf and install/sample-lighttpd.conf respectively.

**Comment by zotlabs** [comment]
They used to be in doc/install, but were moved because it made more sense to keep them with the rest of the install related stuff. I've updated the text. Thanks.

**Comment by arunisaac** [comment]
Yeah, I thought so. Thank you! :-)
