### ISSUE TITLE
Special characters in database user password

### ISSUE THREAD

**Issue by arunisaac** [redmatrix/hubzilla#537]
During the initial installation, when I specified "4,BaR~!<q^m9" as the password, I was unable to connect to the database. I got an "Access denied to dbuser@localhost - DB not connected" error. On changing to a password with only alphanumeric characters, the installation proceeded normally.

Is this behavior normal and to be expected?

I am running mariadb 10.1.17 and php 7.0.10

**Comment by zotlabs** [comment]
The angle char was escaped as an XSS defense; though it is probably not needed on the setup screen. Should be fixed in current dev.

**Comment by arunisaac** [comment]
I have finished my installation using an alphanumeric password. I haven't verified whether this bug has been fixed in the dev branch. But, if you are reasonably confident, do feel free to close this issue. Thanks.

**Comment by zotlabs** [comment]
I'm very confident. Still I'll leave this open for say a month so that we know it hasn't actually been tested and we really should do this.

**Comment by zotlabs** [comment]
Glad I checked - there was still an issue. Now tested and confirmed working.
