### ISSUE TITLE
File-Sync not working between Clones

### ISSUE THREAD

**Issue by sasiflo** [redmatrix/hubzilla#538]
I encountered problems when syncing files between my clones. I have 3 hubs on dev with a channel and 2 clones. On my primary I uploded a bunch of files to a folder. I created this folder before on the primary for permission settings.

When I upload a file it is shown on the primary and all clones. Folders and Files seem to be correctly synced. But it is only correctly saved at the hub where I uploaded it. The synced files are only created as a HTML-page that looks like the page I got when not logged in. The shown metadata (size) is correct at all hubs.

Hubs are all on dev:f9f1b16.

I provide some debugging log in a moment.

**Comment by sasiflo** [comment]
**Some findings:**
- It does not matter if I upload via cloud interface or webdav.
- It does not matter if I upload on primary or clones.
- File type and file size does not matter, tried 30kB and 1,3MB files.
- The file is correct on the hub where I uploaded it.
- The HMTL file in store contains the baseurl of the hub where I uploaded the file on the other hubs. 
- It does not matter how many clones. Created a new account and a new channel and cloned it, but no success.

**Comment by sasiflo** [comment]
I have now some logs.

yinc.de is the hub with the primary. yanc.de is the hub with the clone. I uploaded a zip-file to the folder /cloud/hubzilla_test1_channel1 via web-browser. The sync creates the ressource on the clone side, but content is wrong.

[yanc.de-content.txt](https://github.com/redmatrix/hubzilla/files/500454/yanc.de-content.txt)

[yanc.de-hubzilla.log.txt](https://github.com/redmatrix/hubzilla/files/500455/yanc.de-hubzilla.log.txt)
[yinc.de-hubzilla.log.txt](https://github.com/redmatrix/hubzilla/files/500456/yinc.de-hubzilla.log.txt)

**Comment by sasiflo** [comment]
Commit 095e2bf0b39fdf18217b15f5f743e32e2a49d587 "file clone sync issue, 1. channel permission import had no uid, 2. mod_getfile was sending attach['data'] instead of attach['content']" is applied on both hubs.

**Comment by zotlabs** [comment]
It seems there was a privacy issue. I only tested with public photos.

**Comment by sasiflo** [comment]
I rechecked after commit 3727bea29acb79f66c15b155133ef3bb98d93d49. No success. I added the logs for that try. Content is the same HTML as before.

Interesting detail: On the sending side (yinc.de-hubzilla_2.log.txt) at 2016-09-30 08:42:41 I see an error Getfile.php:69:post: attach_by_hash failed: Berechtigung verweigert. --> (Access denied) But where?

[yinc.de-hubzilla_2.log.txt](https://github.com/redmatrix/hubzilla/files/502555/yinc.de-hubzilla_2.log.txt)
[yanc.de-hubzilla_2.log.txt](https://github.com/redmatrix/hubzilla/files/502558/yanc.de-hubzilla_2.log.txt)

**Comment by sasiflo** [comment]
OH! It is really a privacy issue!

I checked uploading with the most public setting for this channel: all my connections. And then it got synced correctly to the clone!

But changing the privacy setting is not synced after that.

**Comment by sasiflo** [comment]
Sync works when all permissions are public in a folder hierarchy and the file itself. Under all other circumstences it fails.

**Comment by sasiflo** [comment]
Great work! First checks were successfully. Restricted file (with and without folder) worked! Unrestricted file worked also.

**Comment by sasiflo** [comment]
Access rigth modifications are not synced. (not yet implemented?)

**Comment by sasiflo** [comment]
Syncing after upload over webdav works, too. But one small issue is, that file size is not correctly shown, it's 0 bytes. This happens only when uploading with webdeav!

**Comment by sasiflo** [comment]
Permission changes don't get through to the clones. The permission I set when uploading is correctly synced.

**Comment by sasiflo** [comment]
The sync notification from side where changes happens (yinc.de) seem to be incomplete, so that the syncing side (yanc.de) could not get the right attach thingy. Shouldn't there be something in the [attach] part?

Changed side (yinc.de):
```
016-10-03 15:43:57:LOG_INFO:vv7bq4kebvh2oguknuj59ladm4:zot.php:2943:build_sync_packet: build_sync_packet
2016-10-03 15:43:57:LOG_DEBUG:vv7bq4kebvh2oguknuj59ladm4:zot.php:2946:build_sync_packet: packet: Array
(
    [file] => Array
        (
            [0] => Array
                (
                    [fetch_url] => https://yinc.de/getfile
                    [original_channel] => hubzilla_test1_channel1
                    [attach] => Array
                        (
                        )

                )

        )

)
```

Syncing side (yanc.de):
```
2016-10-03 15:43:58:LOG_DEBUG:i2uc3scq3quept3dgq8830sqt3:zot.php:1317:zot_import: Channel sync received: Array
(
    [file] => Array
        (
            [0] => Array
                (
                    [fetch_url] => https://yinc.de/getfile
                    [original_channel] => hubzilla_test1_channel1
                    [attach] => Array
                        (
                        )

                )

        )
...```

[yinc.de-hubzilla_changefile_1.log.txt](https://github.com/redmatrix/hubzilla/files/506636/yinc.de-hubzilla_changefile_1.log.txt)
[yanc.de-hubzilla_changefile_1.log.txt](https://github.com/redmatrix/hubzilla/files/506638/yanc.de-hubzilla_changefile_1.log.txt)

**Comment by git-marijus** [comment]
@sasiflo is this issue resolved?
