### ISSUE TITLE
Improvement for admin : A tool for admin to change a password of a user.

### ISSUE THREAD

**Issue by chris1315** [redmatrix/hubzilla#541]
In admin/accounts/ we have list of account. If a user lost their password and ask the admin to change it. It would be nice for the admin to have an option : change the password.

Additionaly option for creation of a new user (Like friendica)

An option to send a message to one user or many users (Important information)

**Comment by Gadget-Guru** [comment]
The first feature request is already working in the dev branch. Just visit /admin/accounts and select any of the accounts.

FYI, it's a good practice to create a seperate issue for each feature request.

**Comment by chris1315** [comment]
Yes it works on 1.14. We have to click on the email adress.  I don't know how to make this issue done
