### ISSUE TITLE
initial state of message permissions window is wrong

### ISSUE THREAD

**Issue by dwatney** [redmatrix/hubzilla#549]
When I post a message, the permission settings button has a locked icon and the preview shows a private message icon. This is normal, given my settings. But, if I click on the permission settings button, it comes up saying this message is Public. The initial state of that menu is wrong. I have to choose something else and then Public again for it to become a public message.

**Comment by elvecio** [comment]
Plz,
What channel type you've created? (and settings)

What hubzilla version?

**Comment by dwatney** [comment]
I'm running v1.14.1

My Channel permissions category is custom. In Channel Permission Limits,
"Can view my channel stream and posts" is set to allow "anyone on
internet". The default ACL is set to "Use my default audience setting
for the type of object published". A lot seems to have changed since I
last looked at these settings. "Use my default audience setting for the
type of object published"  implies that I set those default audiences
somewhere, but I don't see where, unless it is the settings in the
Channel Permission Limits. But, in that case, it seems like my posts
would all be public and I wouldn't be seeing the lock icon.

In the past, I remember setting things so that anyone could see things,
but the default permissions for new posts were set to only be visible by
approved connections. If I wanted to make a post public, I would have to
change it at post time. Until very recently (1.14 or 1.14.1), that had
been working as expected.

**Comment by git-marijus** [comment]
I tried to rebuild your situation:
> My Channel permissions category is custom. In Channel Permission Limits, "Can view my channel stream and posts" is set to allow "anyone on internet". The default ACL is set to "Use my default audience setting for the type of object published".

When i go to create a post the initial lock setting is unlocked. The preview has no lock.
When clicking the lock in the editor the setting says "Public".
This is because "Can view my channel stream and posts" is set to allow "anyone on internet". 

I can't actually reproduce your issue that the initial lock setting in the editoe with this setup is "locked".

Can you provide some more info?
Might be an issue with the browser or caching.

**Comment by dwatney** [comment]
I just tried it on a completely different computer and browser
      and got the same thing. Maybe there is something about my
      permissions which doesn't like some change in 1.14.1. I'll try to
      figure out how the new UI works and recreate my permissions to see
      what happens.
    
    
    On 10/17/2016 5:09 PM, git-marijus
      wrote:
    
    
      I tried to rebuild your situation:
      
        My Channel permissions category is custom. In Channel
          Permission Limits, "Can view my channel stream and posts" is
          set to allow "anyone on internet". The default ACL is set to
          "Use my default audience setting for the type of object
          published".
      
      When i go to create a post the initial lock setting is
        unlocked. The preview has no lock.
        When clicking the lock in the editor the setting says "Public".
        This is because "Can view my channel stream and posts" is set to
        allow "anyone on internet". 
      I can't actually reproduce your issue that the initial lock
        setting in the editoe with this setup is "locked".
      Can you provide some more info?
        Might be an issue with the browser or caching.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/redmatrix/hubzilla","title":"redmatrix/hubzilla","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/redmatrix/hubzilla"}},"updates":{"snippets":[{"icon":"PERSON","message":"@git-marijus in #549: I tried to rebuild your situation:\r\n\u003e My Channel permissions category is custom. In Channel Permission Limits, \"Can view my channel stream and posts\" is set to allow \"anyone on internet\". The default ACL is set to \"Use my default audience setting for the type of object published\".\r\n\r\nWhen i go to create a post the initial lock setting is unlocked. The preview has no lock.\r\nWhen clicking the lock in the editor the setting says \"Public\".\r\nThis is because \"Can view my channel stream and posts\" is set to allow \"anyone on internet\". \r\n\r\nI can't actually reproduce your issue that the initial lock setting in the editoe with this setup is \"locked\".\r\n\r\nCan you provide some more info?\r\nMight be an issue with the browser or caching.\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/redmatrix/hubzilla/issues/549#issuecomment-254334910"}}}

**Comment by dwatney** [comment]
I have my whole "Anyone" issue figured out now (see support forum). 
I can explain better what is going on now that I have reset everything (and understand it).
I set my permissions category to Mostly Public, to set myself to a known state. Then, I set myself to Custom and set my Default ACL to Friends (the privacy group formerly named Anyone). If I go post a message and click on permission settings (which shows a locked icon), it opens with Public, not Friends. If I want it to be public, I have to select something else and then select Public again.

Now, maybe this is part of the problem or a different problem, but after I set my Default ACL to Friends, if I click Submit and then open up Default ACL again, it is back to default audience settings, not Friends.

**Comment by elvecio** [comment]
> - if I click Submit and then open up Default ACL again, it is back to default audience settings, not Friends.-

Not normal, I tested right now, and what happen to you is not normal, and this is probably why  you see always 'public' and not friends  when you post. Something broke in your side.

**Comment by dwatney** [comment]
On a hunch, I made a new privacy group, got rid of the old one, and set
the new one as the default ACL. No change.

I did change from one mysql database server to another recently, but I
am pretty sure this worked after the switch. The new one is v5.7.15 and
the old one was 5.6.x.

**Comment by elvecio** [comment]
Yes, after creating a new 'friends group' I can see the problem, now I'm in the same problem/situation. There is some bug that is related to the creation of a new group.
