### ISSUE TITLE
change profile photo 

### ISSUE THREAD

**Issue by chris1315** [redmatrix/hubzilla#551]
If you want to change the photo of your secondary profile. You select it then > change profile photo. But you have to take care because you have to check Select a profile: (the default is always the default).

What to do. If you are on a profile 2 and do change profile photo. Put the photo to the profile selectionned. Why change it again. At least you can remind us the name of the selectioned profile.

**Comment by zotlabs** [comment]
Should be fixed in 2a59f45a3b2da30
