### ISSUE TITLE
Change specific profile photo with a photo from album

### ISSUE THREAD

**Issue by chris1315** [redmatrix/hubzilla#552]
You can have two different photos when you upload photo to two profiles but if you choose from an album you have the same photo on all profiles. Not to only the selectioned profile.

Imagine we put our real photo to a private profile.

**Comment by zotlabs** [comment]
Should be fixed in 2a59f45a3b2da30

**Comment by chris1315** [comment]
it works I can change a profile photo from a photo album without damaging the other photo profile. Thank you I tested and it is ok. Sorry for the delay
