### ISSUE TITLE
Private messages get mangled

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#560]
Links in private messages show up strange: http://hwraid.le-vert.net turns into http://hwraid.le$6ert.net. Somehow also the letter "u" is involved in strange behaviour: "dann testen wir mal  ~ und Ø und å" turns into "dann testen wir d!l ~ Pnd Ø und å", "u U u U u" turns into "u U u U P".
Lorem ipsum gets mangled too every other line, no matter which language you test (I tested original, english, kyrillic, arabic and chinese). 
Are these errors connected to rot47?
Postgres db is globally set to utf-8.

We have no idea what bug/misconfiguration could cause this problem, so please help.

**Comment by zotlabs** [comment]
I can't duplicate. I've thrown in Lorem ipsum and foreign text of all kinds, the 'dann tested....' string mentioned above and it is all reproduced perfectly at both ends of the private message.

**Comment by ilu33** [comment]
Then this is either a locale problem or another postgres issue - or both :smiling_imp: 
Strange how the "u" is primarily affected.

**Comment by zotlabs** [comment]
But it's OK before it enters the database? 

In any event, I've got a postgres test site now, but it's behind a firewall and I can't access it until Monday. I'll have a look then unless we come up with any brilliant ideas in the meantime.

**Comment by ilu33** [comment]
I can enter the message correctly - after I hit submit, the page gets reloaded and the message displays mangled. When I send a message to myself from Michael's hub (mysql based) write and reload work ok but the messages arrives mangled at our (postgres based) hub.
Would it help to increase loglevel? It's set to 2 atm.

**Comment by zotlabs** [comment]
This needs more investigation, and we intentionally don't do a lot of logging of the contents of private mail. To verify that it either is or isn't a postgres issue you may need to insert a log statement to see what the text is just prior to storage - and compare that with what you see in the database.

**Comment by zotlabs** [comment]
Just tested on postgres and still cannot duplicate the issue.

**Comment by ilu33** [comment]
We inserted log statements but couldn't find anything abnormal. And it seems that the problem fixed itself. Whatever happened - we don't know. Maybe your pdo commit is somehow involved?
We usually test on Wednesday and Friday but not much in between and we always pull from git dev branch before.

**Comment by zotlabs** [comment]
FYI - I did test with and without the PDO merge. 

I'm for leaving this open a while just in case it pops up again.
