### ISSUE TITLE
Don't send or create a new connection request if you're already connected

### ISSUE THREAD

**Issue by zzottel** [redmatrix/hubzilla#57]
Adding more detail as I just stumbled over the thread in the Grid that was the reason for this bug report:

A member had used an old export of his channel to recreate it at another host. Not all his current connections were in that export, so he started reconnecting to his old connections. This lead to new connection requests being shown at his connections, although in their view, they were still connected to the member.

**Comment by jeroenpraat** [comment]
@zzottel  Is this issue still needed? If not, can you please close this issue?
