### ISSUE TITLE
attending an event creates a 1:1 copy (pdo/postgresql)

### ISSUE THREAD

**Issue by fsteinel** [redmatrix/hubzilla#576]
attending an event creates a 1:1 copy in the ```event``` table and the event view of every participant.
Tested with 4 participants:
```SQL
select count(*) from event where event_xchan='2UcxmOdBaKcaVuf1F2HZrPbllXBJ5AXIzd-jW81M2TxfM6GCl7-iAN5x_QzBWu2txLyzXiWjtsRiznyOaemFsw';
```
Result:
```SQL
 count 
-------
     4
(1 row)
```

**Comment by zotlabs** [comment]
Is this really a 1:1 copy ? If I recall, attending an event auto-adds it to your own calendar if it wasn't in your calendar already. The copies should vary by 'uid' (event_xchan shouldn't be a unique constraint; though it's probably possible to place a unique constraint on uid+event_xchan).  I might need a step-by-step to duplicate whatever you're seeing (with emphasis on who generated the event and who attended it).

**Comment by fsteinel** [comment]
Ah, no 1:1 copy
```SQL
id | aid | uid | cal_id 
----+-----+-----+--------
  8 |   4 |  11 |      0
  9 |   2 |   3 |      0
 10 |   3 |   4 |      0
```
and
```SQL
select * from cal;
cal_id | cal_aid | cal_uid | cal_hash | cal_name | uri | logname | pass | ctag | synctoken | cal_types 
--------+---------+---------+----------+----------+-----+---------+------+------+-----------+-----------
(0 rows)
```
But still:
![events](https://cloud.githubusercontent.com/assets/7137/19953939/88cdfa20-a173-11e6-90e1-73cb60134288.png)

**Comment by zotlabs** [comment]
Yeah I was just seeing what I could duplicate and saw that. I'm on it.

**Comment by zotlabs** [comment]
Found the bug. Thanks.

**Comment by fsteinel** [comment]
It's fixed :+1:
