### ISSUE TITLE
connect

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#577]
./util/connect ch1 ch2 leads to a connection hanging unconfirmed in ch2 while it appears to be confirmed (permissions given) in ch1. Issuing the same command the other way round seems to do nothing.

**Comment by ilu33** [comment]
Issuing the same command the other way round (./util/connect ch2 ch1) now removed the connection from ch2 while it still appears confirmed in ch1. Not good.
Tried ./util/connect ch1 ch2 again but nothing happend in ch2. Still looks confirmed in ch1.

**Comment by zotlabs** [comment]
OK, this one is going to need some coffee to sort out the bidirectional stuff. That will probably have to wait until tomorrow morning.

**Comment by zotlabs** [comment]
Well I had a look and it's working fine for me. I connected ch1 to ch2. This showed ch1 as connected but with no permissions. Looking at ch2, ch1 was 'pending' (awaiting approval). That's the way it should look. Then I connected ch2 to ch1. At that point both showed as connected from each channel with normal permissions in each direction and neither was pending.
