### ISSUE TITLE
WSOD when displaying content logged in (dev)

### ISSUE THREAD

**Issue by zzottel** [redmatrix/hubzilla#581]
Today, I updated Hubzilla dev and some relevant Debian packages: MySQL (5.5.53), libapache2-mod-php5 (5.6.27), and php5 (5.6.27). Not sure which of the updates lead to my problem, but:

As soon as I'm logged in, I'm getting a WSOD on pages like network/, channel/, display/ (not sure which else, it seems any page that displays network content), but not on pages like apps/, admin/, events/ etc. Unread counts and notifications are shown on pages that work.

There are no error messages anywhere, not in php.out (.htconfig.php lines active), not in dbfail.out, not in the normal Hubzilla log even when set to Loglevel All, not in Apache's error logs. The only thing I see is a 500 in the Apache access logs.

It works if I'm not logged in, i.e. I can access channel/ pages with suitable access rights then without problems. Also, I can still access these same pages when I'm logged in as long as it isn't my channel, i.e. https://hubzilla.zottel.net/channel/zottelszeug is accessible whether I'm logged in or not. When I'm not logged in, https://hubzilla.zottel.net/channel/zottel correctly redirects to the profile page, logged in I get the WSOD.

Even more precise: Showing one's own network or channel doesn't work, i.e. when I switch to the channel zottelszeug, looking at channel/zottelszeug/ yields a WSOD, but when I switch back to channel zottel, channel/zottelszeug/ works again.

As I don't see anything in any logs, I don't know where else to look. Any hints what I could do to help hunt this bug down?

(Note that the PR I just openend doesn't fix this problem, it's just something else I stumbled over while looking at php.out.)

**Comment by git-marijus** [comment]
Item table is fine?

**Comment by zzottel** [comment]
Yes, I think so. Just repaired it to be sure (still same behaviour); but I'd expect yes, anyway, as showing another channel's channel page works, but doesn't work anymore after switching to that channel.

**Comment by zotlabs** [comment]
Do you have smileybutton addon installed? (Fixing now...)

**Comment by zzottel** [comment]
Yes, I have, though I did test with safemode turned on? Anyway, it works again now, thanks!
