### ISSUE TITLE
new line detected in boot.php on line 1753

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#587]
13-Nov-2016 17:46:45  PHP Warning:  Header may not contain more than a single header, new line detected in boot.php on line 1753
This was just once in php.log. My collegue is not available atm and I can't figure out what $s does, so I don't know where it got the misformatted header from.

**Comment by zotlabs** [comment]
That's called from many places in the code to issue a redirect to another URL and exit. I don't see any place where we explicitly provide a URL with a newline in it, but this is occasionally taken from a variable and there may be some bad data somewhere. I'm not certain this is worth fixing but would require checking $s and seeing if it has a newline; and if so log what it is and provide a backtrace so we can figure out how it got there. If you see this message repeatedly it's probably worth tracking down. If it's a one-off occurrence I'm not certain we gain very much by trying to prevent it.

**Comment by ilu33** [comment]
o.k. it was just once. I'll watch for it.

**Comment by zotlabs** [comment]
No reports since the initial report a year ago. Closing.
