### ISSUE TITLE
Cannot modify header warning on wiki download

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#596]
This error in php.out appeared when I mistakenly clicked "Download" instead of "Edit" on an empty wiki:
PHP Warning:  Cannot modify header information - headers already sent by  (output started at /.../Zotlabs/Module/Wiki.php:114) in /..../boot.php on line 1747
Afterwards I realized that copy/paste doesn't work. I know it worked several days ago. I've no idea what caused this. The php error caused by the download might be related or not.

**Comment by git-marijus** [comment]
Are you talking about copy/paste in the editor?

**Comment by ilu33** [comment]
yes

**Comment by ilu33** [comment]
Another oddity: If I click on the edit symbol (next to download) I'd expect the wiki to load with the editor open. Instead I just get the option to delete it. To edit the wiki I need to click the wiki name first and then the edit tab. The pencil symbol stil only allows deleting.
I guess this is due to the ongoing work on the wiki gui, just take this as feedback.

**Comment by git-marijus** [comment]
I can c/p inside the editor here with no problems...
The php warning is not related.

**Comment by ilu33** [comment]
I found the problem: dom.event.clipboardevents.enabled was set to false in this browser. You can close the issue. Sorry I bothered you.

**Comment by git-marijus** [comment]
I will lwave it open because the php warning needs to be fixed..
