### ISSUE TITLE
Wiki sub-pages don't load any more

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#598]
My wiki sub-pages don't load any more: 403 forbidden.

**Comment by git-marijus** [comment]
Does your webserver has r/w access to /store and all its subfolders?

**Comment by ilu33** [comment]
Yes. It has worked until ... last weekend, I think. But I checked again to be sure.

**Comment by git-marijus** [comment]
Hm... I can't duplicate this issue. Can you check if the files are present in /store please?

**Comment by ilu33** [comment]
I think the issue is with the wiki names. Since I stored scripts, the wiki pages are named *.sh. This was no problem until recently. We are looking into webserver configs atm, maybe something was changed there. Do you have any idea?

**Comment by git-marijus** [comment]
Afaik the pagename extension as saved on disk for all wiki pages is hardcoded to .md (markdown).

**Comment by ilu33** [comment]
Yes, this results in f.e. "script.sh.md". But, before php gets to handle the request and looks for "script.sh.md", the webserver sees that "script.sh" is requested and blocks that request instead of handing it over to php.
