### ISSUE TITLE
URL's with ( ) in them are improperly parsed

### ISSUE THREAD

**Issue by encyclomundi** [redmatrix/hubzilla#607]
If the URL, mainly from Wikipedia, contains (), that part of the url is placed after the [url] tag. See example.

![parlementum](https://cloud.githubusercontent.com/assets/495249/20787030/95b77a9e-b75e-11e6-9b82-116d63b8ce67.png)

Hubzilla Version 1.15.1 - 1184 
PHP Version 7.0.13-1
PHP-FPM Version same

**Comment by zotlabs** [comment]
I've tried my fix with a wide variety of input and it seems to function correctly - and especially with the wikipedia case. So I'm going to close this as 'fixed in dev'. Re-open if you still have issues.
