### ISSUE TITLE
request

### ISSUE THREAD

**Issue by albigro** [redmatrix/hubzilla#620]
I'm not a coder but testing 2.0 RC ...
Not quite certain, but i used the equivalent branch in the addon git?
 git diff:
--- a/util/add_addon_repo
+++ b/util/add_addon_repo
@@ -18,7 +18,7 @@ fi

 mkdir -p extend/addon/$2
 mkdir addon > /dev/null 2>&1
-git clone $1 extend/addon/$2
+git clone -b 2.0RC $1 extend/addon/$2
 if [ $? -ne 0 ]; then
        exit $?

**Comment by zotlabs** [comment]
git clone copies the entire repository - all branches.

After you've added the repository,

cd extend/addon/xyz
git checkout 2.0RC

replacing xyz with your local repository name.
