### ISSUE TITLE
problem with channel source

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#635]
following scenario:
you have a channel, and then one person  **using your channel as a source**, you create a post, then the post is replicated in the other person's channel. Then you come back in the post and **add a tag**. At this point the tag is also added in the post of the other channel using your channel as a source, but at the **same time** in the **channel home page** that your post **is gone**. You may even find your post **just in grid**, while on your home page the post is gone. It seems that at the moment that you add a tag something happens and changes the configuration of the post.

**Comment by zotlabs** [comment]
Thank you for figuring out how to duplicate this. It was a very difficult problem, but should be fixed in dev now.

**Comment by elvecio** [comment]
I've just been lucky enough to have that problem the first time, because then the investigation is part of my nature ;-)
