### ISSUE TITLE
Default privacy group not set for new connections

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#641]
a. When the 'Channel permissions category' is e.g. set to 'Social - Mostly Public' the default privacy group is automatically set to 'Friends' (or the translated language string). New connections are automatically added to this privacy group. 

b. When the 'Channel permissions category' is set to 'Custom/Expert Mode' you can set the default privacy group yourself with 'Add new connections to this privacy group'. 

In both situations (a. and b.) the default privacy group is **not** set for new connections.

This has worked in the past, because I see in my existing channels I have a part of the connections in the default privacy group and another part (more recent connections) not. As a workaround I have to add them manually.

**Comment by zotlabs** [comment]
"a" is not true. 'Social - Mostly Public' does not provide or use a default privacy group. A 'Friends' group is created for all channels but only the private and custom roles use it automatically. 

Just tested with custom permissions, and this was working properly. My test was a locally initiated connection. To assist us in further tracking this down, was the friend request locally (by you) or remotely (by them) initiated, and from what network; as this code is duplicated with minor variations for every different network connector. And if the request was remotely initiated, note that we don't actually add them to the privacy group until the connection has been approved.

**Comment by jeroenpraat** [comment]
a. Okay. Didn't know that. So what is the reason for a Friends group? Isn't that a bit confusing?

b. One is my admin channel. Channels are automatically added when an account is created. Two is a forum channel (but with custom permissions). Channels are initiated remotely an automatically approved (using Connection Default Permissions).
