### ISSUE TITLE
Wiki page ends up in gateway timeout

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#643]
After 89 edits/commits a wiki page doesn't load any more and times out with 504. Are all git changes loaded together with the page content?

**Comment by git-marijus** [comment]
I did some tests could not reproduce this after 100+ commits

**Comment by ilu33** [comment]
An hour later we were warned that php5-fpm was out of control and eating up ressources - a restart fixed that. So maybe the problem started somewhere else but we don't know where. There's only hubzilla running on that server, nothing else.

**Comment by ilu33** [comment]
I can reproduce this: Whenever I try to open that wiki page, php5-fpm rises to 100% cpu usage and the page times out with 504. So it's either the specific content of that wiki page (a list of internet addresses) or the number of commits or ...?

**Comment by git-marijus** [comment]
Is that still an issue for you?
