### ISSUE TITLE
Setup / installation question

### ISSUE THREAD

**Issue by FDominicus** [redmatrix/hubzilla#647]
I tried to install hubzilla following the INSTALL.txt 
So far  it has worked.
The login page is , the databases is also there and the entries for users are there also.
Anyway if I try to login I'm just thrown back to the login screen - but no login. 
There is no error in the apache files:
ls -l hubzilla-error.log 
-rw-r--r-- 1 root root 0 Jan 19 09:48 hubzilla-error.log

the last access entry is:
[19/Jan/2017:13:00:26 +0100] "GET /ping?_=1484825225736 HTTP/1.1" 200 686 "https://hubzilla.fam....de/login" "Mozilla/5.0 (X11; \
Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0"

This are the entries in the tabel account:
account_roles |            account_email             
---------------+--------------------------------------
          4096 | webmaster@fam-...
             0 | Friedrich.Dominicus@fam-...
so yeah webmaster is the "super user"

So what am I doing wrong and have to change?

**Comment by git-marijus** [comment]
Probably your email is not verified. Check your account.account_flags value.
Do you have sendmail set up correctly?

**Comment by FDominicus** [comment]
Am 19.01.2017, 13:33 Uhr, schrieb git-marijus <notifications@github.com>:

>
> Probably your email is not verified. Check your account.account_flags  
> value.
> Do you have sendmail set up correctly?

May be, I had an working postfix installation, but i was replaced with  
sendmail with the fast installation skript also  my Mariadb has been  
replaced with mysql 5.7. Which was not the most funny thing I have had  
encountered.

I see that I get my postfix running again.

Regards
Friedrich
>
>



-- 
Q-Software Solutions GmbH; Sitz: Bruchsal; Registergericht: Mannheim
Registriernummer: HRB232138; Geschaeftsfuehrer: Friedrich Dominicus

**Comment by git-marijus** [comment]
Not sure if you got the edit... Setting account.account_flags to 0 should let you log in.

**Comment by FDominicus** [comment]
Now here we go. The fast install skript is "brutal". I can  not recommend it. Especiallyy not if any other MTA as sendmail is installed. And it's not a good idea to use it if there is some Postgres or Mysql running. 
Mysql and Maria DB know seem to not speak the same language any more.

So what I did in the end, was working through the install Skript. What you might like to add to it is you recommendations here. If all the things have worked but login does not work check the account table and set account_flags to 0.

That has worked for me.
And yes it would be a good idea -  IMHO - to warn that the fast install skript, simply does not bother what is installed. At least that was a big ugly surprise for me

Anyway thanks for you help and now I'll see what I can do with that hubzilla ;-)

**Comment by ilu33** [comment]
Which script did you use exactly? Can't find anything called "fast". Was it homeinstall?

In any case, you might be right. I can't say about MariaDB but better don't use any of the scripts if you have postgres or nginx. Take them as suggestions and go through install and configurations manually.

**Comment by FDominicus** [comment]
Am 20.01.2017, 03:37 Uhr, schrieb ilu33 <notifications@github.com>:

>
> Which script did you use exactly? Can't find anything called "fast". Was  
> it homeinstall?
Yes it was the homeinstall
>
> In any case, you might be right. I can't say about MariaDB but better  
> don't use any of the scripts if you have postgres or >nginx. Take them  
> as suggestions and go through install and configurations manually.
I learned that the harder way ;-)

Regards
Friedrich



-- 
Q-Software Solutions GmbH; Sitz: Bruchsal; Registergericht: Mannheim
Registriernummer: HRB232138; Geschaeftsfuehrer: Friedrich Dominicus

**Comment by git-marijus** [comment]
The homeinstall script is just there to help people setup quick on a fresh debian install.
