### ISSUE TITLE
[hubzilla.org] page width broken by the "news-sticker" release element

### ISSUE THREAD

**Issue by Flaburgan** [redmatrix/hubzilla#648]
The #news-sticker element has the width of the page but is moved to the right of the page with a `position: relative;`. This creates a overflow and makes an evil horizontal scrollbar appear.

I didn't find the source code of the website so I open an issue here. Please point it so I can open a PR.

**Comment by git-marijus** [comment]
Thanks for the pointer. It should definitely be `position: absolute;`

**Comment by Flaburgan** [comment]
I can fix it if you show me where the code is.

**Comment by zotlabs** [comment]
The repository is https://github.com/anaqreon/hubzilla-website ;

however the news sticker is a one-off patch that anaqreon supplied me and was applied manually. It is not in the repository. I included it with only minimal tests done on a desktop. It has now been changed to absolute and the position adjusted slightly to compensate. I still haven't tested on a smaller screen size device but will do so later today. If you could verify, that would be great. We will probably drop the news-sticker anyway in a few weeks at most. (The colours are awful, I don't care for the jaggies introduced by rotation, and it's highlighting a transient news event with a limited shelf-life.)

**Comment by zotlabs** [comment]
Fixed by removing the news-sticker. I'd recommend integrating an announcements feed widget into the page going forward.
