### ISSUE TITLE
in menu "Manage Channel Locations" for browser-window 760 until 785 px are missing delete-Icon

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#651]
in menu "Manage Channel Locations" for browser-window 760 until 785 px are missing delete-Icon

**Comment by git-marijus** [comment]
Can you please provide versions for browser and hubzilla?
Thanks

**Comment by HappyPony** [comment]
- Btowser Firefox Version 50.1.0
- Hubzilla (standard) Version 2.0.6

![delete-icon-missing](https://cloud.githubusercontent.com/assets/3226308/22232251/97649f66-e1e8-11e6-9d96-ac13063bf624.png)

**Comment by git-marijus** [comment]
I see... Should be fixed now in dev and master branch.
