### ISSUE TITLE
 Feature request: menu feature for display of apps

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#652]
I suggest a menu feature for display of apps. Namely similar Channel, About, Photos, Files, Webpages, Wikis menuitem here https://hub.freecommunication.org/channel/Channel_ID. My draft:
![apps-galerie-order-proposal_privat](https://cloud.githubusercontent.com/assets/3226308/22294274/edea51d4-e312-11e6-9e0e-c89e1d18c890.png)

 
![apps-galerie-order-proposal_all](https://cloud.githubusercontent.com/assets/3226308/22294265/e80c3f3e-e312-11e6-93ff-56425a6a77d6.png)

**Comment by git-marijus** [comment]
Actually this is already possible:
- Click "Edit App"
- Assign the apps one or more categories

After this you will get a category menu on the left side...
