### ISSUE TITLE
Feature request: menu feature "compact-view for apps" 

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#654]
I suggest with radio-button implement Edit and compact-view. Here my proposal "compact-view for apps" 

```
 .app-detail img {
  width: 30pt; height: 30pt;
  }
 .app-detail {
  height: 80pt;
  }
   .app-container {
  height: 75pt;   
  padding: 5px;
  width: 60pt;
   }
} 
```
I use this CSS with Stylish-Addon https://addons.mozilla.org/de/firefox/addon/stylishsync/?src=api.

![apps-galerie-order-proposal_compact](https://cloud.githubusercontent.com/assets/3226308/22320650/63b86786-e38e-11e6-8f84-0baa09b829b4.png)

**Comment by git-marijus** [comment]
Your proposal does not really follow the default theme design guidelines. Anyway, there is an effort in dev branch to implement the apps page within the nav-bar which will dramatically change the way we use apps and will probably make this page obsolete...

**Comment by zotlabs** [comment]
The app-menu has been in place for some time now - can we close this?
