### ISSUE TITLE
Incomplete titles for items .page-title, .wall-item-title > h3

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#656]
Incomplete titles for items .page-title, .wall-item-title > h3. I sugggest for this Items
```
.section-title-wrapper > .page-title, .wall-item-title > h3 
```

this CSS-Formats implements

```
  .section-title-wrapper > .page-title, .wall-item-title > h3, .section-title-wrapper h2 {
  white-space: normal; 
}
```
 

**Before ~ after examples**

**Representation with white-space: nowrap;**

![wall-item-title-nowrap](https://cloud.githubusercontent.com/assets/3226308/22360620/d5330fe2-e451-11e6-81d9-88b345303ff9.png)

**Representation with white-space: normal;**

![wall-item-title-normal](https://cloud.githubusercontent.com/assets/3226308/22360589/7914f478-e451-11e6-8009-f8be1f66d874.png)

- Browser Firefox Version 50.1.0
- Hubzilla (standard) Version 2.0.6

S. also ticket #651 .

Edit: add `.section-title-wrapper h2`-item for Wiki

**Comment by git-marijus** [comment]
Issue #651 is already fixed in dev and master branch.

For the titles: it was a design decision to ellipsize long titles. If we let them break aka `white-space: normal;` they destroy the graphical view of the post header. Hovering the title with the mouse will reveal the whole title in the tooltip.

We try to maintain a design that works equally well on big and small screens. We need to make sacrifices though in some situations. If in doubt we choose the way that also works on small screens...

**Comment by HappyPony** [comment]
I suggest for CSS-`style guide`-concept and implement to take into consideration with [Responsive Web Desgin](http://www.hongkiat.com/blog/responsive-web-nav/) . Responsive Web Desgin allowed CSS-solitions without sacrifices for any screens - whether big or small :).

**Comment by git-marijus** [comment]
That is what we basically use for our navigation (we use the bootstrap library). Page or post tiltles are very different to navigation though.

As you can see there is space for 3 lines of text at the right side of the author image (title, author name, and timestamp). We can't break any of them without making the post heading look broken (some people would say ugly).

If you have a better idea of how to solve this problem which would also work throughout the application (not only for posts) you are welcome to share it here.

**Comment by HappyPony** [comment]
> As you can see there is space for 3 lines of text at the right side of the author image (title, author name, and timestamp).

I didn't (quite) follow that. Can you this problem specify with one Screenshot?

**Comment by git-marijus** [comment]
Your second image with the linebrak shows it quite clear: the timestamp line has moved under the author image.

We don't want that. Thats why we restrict the header to 3 lines of text an ellipsize it if it does not fit...
