### ISSUE TITLE
feature request: alarm color for "Your default profile visible to anybody on the internet" -message 

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#667]
I suggest alarm-background-color for the message "Your default profile visible to anybody on the internet" - s. example:

![edit-profile-alarm-color](https://cloud.githubusercontent.com/assets/3226308/22693759/e4126be2-ed44-11e6-9809-faecd0a741b0.png)

**Comment by git-marijus** [comment]
It's not a warning or danger... It's an info...

**Comment by zotlabs** [comment]
Working as designed. Closing.
