### ISSUE TITLE
Docs say POST status update with basic auth work, but code (and logs) say it doesn't.

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#67]
Not sure whether API access via basic auth is no longer supported and the docs are wrong, or I'm doing something wrong.

The posting docs https://github.com/redmatrix/hubzilla/blob/master/doc/api_posting.bb state that one can just POST with form-urlencoded params and basic auth.

However, when doing that, I get this:

```
2015-10-04 05:39:42:iltj7744updvgpr1ph4utvm4a4 api.php:92:api_login: /home/src/hubzilla/include/api.php92api_login
exception 'OAuthException' with message 'Invalid consumer key' in /home/src/hubzilla/library/OAuth1.php:610
Stack trace:
#0 /home/src/hubzilla/library/OAuth1.php(556): OAuthServer->get_consumer(Object(OAuthRequest))
#1 /home/src/hubzilla/include/api.php(77): OAuthServer->verify_request(Object(OAuthRequest))
#2 /home/src/hubzilla/include/api.php(173): api_login(Object(App))
#3 /home/src/hubzilla/mod/api.php(114): api_call(Object(App))
#4 /home/src/hubzilla/index.php(339): api_content(Object(App))
#5 {main}
2015-10-04 05:39:42:mcghd2oqshm0ev24insf0ea7i2 auth.php:77:account_verify_password: password verified for radio@spaz.org  
2015-10-04 05:39:42:mcghd2oqshm0ev24insf0ea7i2 api.php:180:api_call: API call for SPAZ Radio: api/statuses/update
2015-10-04 05:39:42:mcghd2oqshm0ev24insf0ea7i2 api.php:181:api_call: API parameters: Array
(
    [q] => api/statuses/update
    [channel] => spazradioinfo@hub.spaz.org
    [title] => 
    [category] => 
    [status] => Now playing: Dam Free Radio! - 2015-09-17
)

2015-10-04 05:39:42:mcghd2oqshm0ev24insf0ea7i2 api.php:774:api_statuses_update: api_statuses_update: no user

```

Which, following those line numbers, seems like it does a successful password auth then calls api_user instead of just accepting the basic auth it just did:
https://github.com/redmatrix/hubzilla/blob/master/include/api.php#L774

Which I'm guessing the api_user() is failing becuase allow_api isn't set in the session, which appears to be set via api_call, and I lost the thread trying to find out what or where api_call is called (looks like from mod/api.php) 

I can deal with Oauth2 if needed but basic auth would be so much simpler for this use case.

**Comment by redmatrix** [comment]
This has been working for several years now; and this part of the code hasn't changed recently, so it definitely looks to be a regression.

**Comment by redmatrix** [comment]
Just tested and see no problems. Works fine. 

curl -u mike:password http://myhubzillasite/api/statuses/update.xml -d status='Howdy!' -d lat='30.468' -d long='-94.743'

**Comment by kenrestivo** [comment]
http://myhubzillasite/api/statuses/update.xml  works fine
http://myhubzillasite/api/statuses/update.json works fine

But http://myhubzillasite/api/statuses/update gives the error above. The docs don't include the .xml or .json extension. Looks like the incorrect URL is auto-generated by BBcode.

**Comment by redmatrix** [comment]
There are a few ways to specify the channel. If you login with a channel nickname insread of an email address, and the account password, we'll connect you to the requested channel. If you login using the account email, you'll connect to the default channel, but you can use -d nickname to connect to the channel with that nickname. You don't add the @wherever when using -d , just the nickname.
