### ISSUE TITLE
Code blocks in Markdown web page import shouldn't be escaped 

### ISSUE THREAD

**Issue by navigium** [redmatrix/hubzilla#677]
*Situation*: importing a website containing a page which has a markdown file as it's content.

*Steps to reproduce*: 

1. Create a zip file containing the appropriate `page.json` file and a markdown file with the following   
    content:
    ~~~markdown
    ```
    {"hello": "world"}
    ```
    ~~~

2. Import the web page in the zip file using the website import.

*What happens*: the imported markdown ends up in Hubzilla like this:

~~~markdown
```
{&quot;hello&quot;: &quot;world&quot;}
```
~~~
which obviously shouldn't happen in the markdown code itself but only in the converted HTML.

**Comment by zotlabs** [comment]
This is being added by z_input_filter(); The goal of this function is to ensure that nobody can store unpurified HTML without having permission to do so. The easy way is to convert angle brackets and quotes to html entities, which is what we do.  

The hard way is to check if the content-type is markdown and

- convert any angle brackets (but not quotes) to html entities that occur within code blocks (and only within code blocks)
- then run the complete contents through the html purifier.


There may be something I missed here but that's basically what is needed.

**Comment by navigium** [comment]
This won't work. It should also be possible to include html code in code block to create a page about html code. IMHO we shouldn't alter the Markdown code at all. If someone tries to include disallowed HTML Code in the Markdown document, this should be handled when the Markdown is converted to HTML. As I see it it should work like  this:

* Store the Markdown code exactly as provided in the file or the input field.
* Sanitize the Markdown code when converting it to html. 
    * Remove HTML code that's not in a code block
    * Replace disallowed characters and replace them with HTML entities in code blocks. (As far as I know this is already done by the used markdown.php script).

**Comment by zotlabs** [comment]
**All** input must be sanitised before it can be stored. No exceptions. Violate this principle at your own peril.

**Comment by navigium** [comment]
I'm sorry, I didn't express myself clear enough. I didn't mean to say
that you shouldn't sanitize the input at all. Of course it has to be
sanitized to protect against server side attacks as SQL injection and
what not.

Nevertheless, Markdown isn't HTML and therefore it doesn't need to be
sanitized with regard to HTML/JS attacks upon creation but upon
conversion to html. As far as I see it, does markdown.php do this
anyway, at least with the right settings.

Of course we could also sanitize the Markdown for XSS and HTML injection
before storing it. This would mean that we need a function tailored
towards Markdown instead of using a HTML sanitization function. This
would include things like:

* remove HTML outside of a code block

* Remove JS from links as in `[name](javasript:do.evil.thing)`.

* probably more.

I don't see the security benefit this would provide as this is done
again when converting the Markdown to HTML.
On 24 February 2017 21:48:11 CET, zotlabs <notifications@github.com> wrote:

    *All* input must be sanitised before it can be stored. No
    exceptions. Violate this principle at your own peril.

    —
    You are receiving this because you authored the thread.
    Reply to this email directly, view it on GitHub
    <https://github.com/redmatrix/hubzilla/issues/677#issuecomment-282400477>,
    or mute the thread

**Comment by zotlabs** [comment]
> I don't see the security benefit this would provide as this is done
again when converting the Markdown to HTML.

"View Source" would then execute malicious code. 

By design, markdown is an HTML document and without filtering, can contain any HTML (really anything) and only that within code blocks is escaped by the markdown engine during rendering. The rest is simply passed to the output without any purification or analysis.  Therefore the content must be purified before passing to the markdown processor. The best place to purify it is on receipt as HTML purification is a somewhat intensive process and if performed at the output side will affect server performance somewhat dramatically.

You're entirely correct that sanitising markdown correctly is somewhat difficult and when done correctly one needs to account for example code in code blocks and unsupported schemes in links. Currently we are not doing it correctly and that is the bug.

**Comment by zotlabs** [comment]
The example provided should now work correctly for 2.6 or later. Tested on 2.8. Closing.
