### ISSUE TITLE
upload for large files failed 

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#679]
I uploaded file 83,3 MB size. Hubzilla reportet "Ready", but file aren't uploaded. I repeat such a one failed upload at different Hubzilla-server

**Comment by git-marijus** [comment]
Have you checked your file upload limits in php.ini?

**Comment by zotlabs** [comment]
You should be able to upload files of nearly unlimited size using DAV, but web based uploads are restricted by php settings. We have no control over these settings.  

Hubzilla can restrict uploads by account service class but it isn't likely you've configured this or you would know your limits. 

There is a plugin called 'upload_limits' . You can install that and visit /upload_limits on your website and find out what the various system imposed upload limits are. Adjusting them is a server configuration issue and has nothing to do with hubzilla.

**Comment by zotlabs** [comment]
Leaving this for a place-holder:

https://github.com/23/resumable.js

provides client side chunked uploads of large files. This would be an interesting integration or plugin project.

**Comment by zotlabs** [comment]
Update: large file support was added to the post editor in Hubzilla 2.6. It is still missing from the /cloud page. It is also missing from the various photo uploads but these "usually" fit in memory.

**Comment by zotlabs** [comment]
fixed in dev (2.9)
