### ISSUE TITLE
picture upload for profile photos doesn't respact the selected file

### ISSUE THREAD

**Issue by rabuzarus** [redmatrix/hubzilla#68]
If you upload a photo on the profile edit page it is used for all available profiles and not only for the one which was selected

**Comment by redmatrix** [comment]
more information required - just tried and works for me.

**Comment by rabuzarus** [comment]
sry I can't give you not much more infos because it's not my hub
I have an account on https://hub.hfrc.de ( version: 2015-10-01.1172H+4deccee)

Strange thing is:
The topbar menu has the picture from the advanced profile - also in "edit profiles" both profiles are displayed with the picture from the advanced profile. But if I'm going to my channel page there is the picture of the standard profile in the left side vcard_widget.
On the photo page I see the standard avatar picture on the left side widget (the one if you have not choose any personal profile picture).

**Comment by redmatrix** [comment]
Advanced profile is different than multiple profiles. I suspect you have a cache issue.

**Comment by rabuzarus** [comment]
hmm strange, i tried clearing the browser cache before starting this bug report
Now I tried again and it is working.
Big sorry for the noise
