### ISSUE TITLE
No permission to edit with Remote authentication

### ISSUE THREAD

**Issue by bugmenot2** [redmatrix/hubzilla#690]
I could not find a way to edit a wiki with Remote authentication from a different hub. I'm using Forum - Mostly Public category.
If it is not possible, it should be explicitly documented.
1) Wiki edit possibility / permissions settings
2) Posting possibility / permissions settings

**Comment by zotlabs** [comment]
By default "wiki write" permissions are not automatically granted except for the 'repository' permission role. The original wiki write permission is granted to those that 'can upload/modify my channel storage and photos'. This means that *any* of your friends can delete any of your files/photos/wikis. We didn't feel this permission should be granted without your explicit knowledge/approval. 

In 2.2 (which will be released any day now) you can assign a permission group to those you want to grant wiki write access and also provide a separate wiki write permission from your files and photos. Currently you must either use a custom permissions role or specifically edit the permissions of those connections you wish to have this ability.

**Comment by bugmenot2** [comment]
Will it also be possible to grant wiki write access to any authenticated user, not just friends (public community scenario)?

**Comment by zotlabs** [comment]
Yes, but I think this will require using  a custom permission role. This doesn't fit very well in any of our "preset" permission roles. You can do this today, though the specific "write_wiki" permission is new to 2.2. There were a couple of late breaking bugs but 2.2 is still scheduled for official release in the next day or two.
