### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/hubzilla#696]
No reason is left blank. What should be

server > http://hubzilla.mamalibre.com.ar

**Comment by jeroenpraat** [comment]
I see an Error 404 (means: can't find it). I also see http instead of the mandatory https. So this ain't a Hubzilla issue, but a server issue. Please make sure that the server basics works, before issuing an issue here. Closing this issue cause of that.

**Comment by mama21mama** [comment]
Gives 404 error because it deletes the files. Because it showed blank page without any error in sight. I do not know what has happened. Later restore a backup in a stable code of hubzilla.
