### ISSUE TITLE
New profile photo fails to apply on new Hubzilla-channel

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#7]
I can access the menu for setting a new profile photo, photos are uploaded and stored in the profile folder in the channel cloud, but the image cannot be applied.

**Comment by hfroese** [comment]
Same here.

**Comment by hfroese** [comment]
Sorry. Forgot "chmod -R 777 store" :-/

**Comment by HaakonME** [comment]
Right, I deleted the channel - also in the database - and started over. A new big profile Image is applied on the channel page - , e.g. https://zot-mor.rhcloud.com/photo/profile/l/7 but _not_ the little one included in the navbar or in posts, e.g. https://zot-mor.rhcloud.com/photo/profile/m/3 . How to fix?

**Comment by HaakonME** [comment]
Updating the profile image URL in column xchan_photo_l, xchan_photo_m and xchan_photo_s in table xchan at ZotMor seems to do the trick there. Now to see if it propagates to clones.

**Comment by redmatrix** [comment]
There are a number of issues with that xchan, compounded by the fact that you've got a number of hublocs and the primary is dead. If you want zot-mor to be the primary, please visit /locs on that site and make it so. This will probably fix several of the xchan issues. Delete any locations that aren't valid. Once you've done that, go back and edit the xchan_photo_date and make it later than the date that's there currently. Within about 24-48 hours the photo should be propagated.

**Comment by HaakonME** [comment]
Right, I have done all steps except the date bit now. The OpenShift-server seems to have some issue and does not respond well at the moment. 

I was hoping to have fixed my OpenShift-Hubzilla-deploy script first before making ZotMor my primary - see initial mostly working version at https://github.com/HaakonME/openshift-hubzilla-deploy/blob/master/openshift-hubzilla-deploy . 

The store directory, .htconfig.php and .htaccess needs to be handled correctly upon each git push, ie. they must be in the persistent $OPENSHIFT_DATA_DIR to survive, and then symlinked in the new current repo. 

The store seems fine now, but I got some "cannot stat" error when it got to the .htconfig.php , so either I am creating the symlinks wrong, or they cannot be created this way, or perhaps should be moved into the step before deploy and put in a script called build. The documentation is very vague about what should be done in which step.

I think we can close this one. Thank you!
