### ISSUE TITLE
Email notifications not sent, when subdomain used

### ISSUE THREAD

**Issue by lazyadmin111** [redmatrix/hubzilla#700]
It turned out, that it was not really the fault of the mail system, but the code in Zotlab/Lib/Enotify.php, in particular the code to create the "reply-to" address. It may create an email address which doesn't exist, and thus some mail servers might deny to deliver.

I will try to provide a patch for it.

**Comment by zotlabs** [comment]
The 'code to create the "reply-to" address' is used as a fallback if you don't set one. Any address you set takes precedence and is what Hubzilla will use for all system generated emails. The solution is:

        % util/config system.reply_address 'a_legal_address@mysite.com'
        % util/config system.from_email 'a_legal_address@mysite.com'

**Comment by lazyadmin111** [comment]
yes thats true, this is a workaround.

However, the problem is that the mail is not delived because this reply-to-address is generated by default. I experienced a mail-server which would have accepted the mail, if hubzilla wouldn't have added that reply-to-address which didn't exist by default.
