### ISSUE TITLE
localized https://demo.hubzilla.org -dialog

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#718]
I suggest localized the https://demo.hubzilla.org -dialog. Here German-Edition

> Willkommen auf dem Hubzilla demo Hub!
> 
> Dieser demo Hub (Hubzilla-Knoten) ist konzipiert, um Ihnen eine Chance zu geben, einige Features der Hubzilla-Platform kennenzulernen. Die fiktive Aktivitäten illustrieren nur einige von vielen Möglichkeiten, die den Communities für die  Kommunikation und Zusammenarbeit im Hubzilla-Netzwerk zur Verfügung stehen. 
> 
> Sie können selbst in der Praxis testen, welche Möglichkeiten Ihnen im Hubzilla-Netzwerk mit Nomadic Identity und mit dem dezentralen Zugang. Richten Sie einen eigenen Hubzilla-Knoten ein oder registrieren Sie sich auf einem offenen Hub. Sie können dann Ihren Kanal klonen oder mit diesem Kanal auf einen anderen Hub umziehen. Mit Hubzilla kontrollieren Sie Ihre Daten, aber auch Ihre Identität! 
> 
> Die Demoinstanz wird im 10-Minuten-Takt zurückgesetzt, wobei Ihre Hubzilla-Sitzung evtl. unterbrochen wird. Laden Sie die Website https://demo.hubzilla.org/ einfach neu, um fortzufahren. Sie können dieses Dialog-Fenster mit einem Klick auf das blaue [i]-Symbol rechts oben in der Navigationsleiste.

for this dialog 

> Welcome to the Hubzilla demo hub!
>
> This demo hub is designed to give you a chance to explore some of the features offered by the Hubzilla platform. The activities of the fictional characters illustrate only a few of the ways communities can use Hubzilla to collaborate and connect.

**Comment by git-marijus** [comment]
I think this is already implemented now. Can we close this issue?
