### ISSUE TITLE
Browser autor-refresh after posting not happening in Hubzilla, but does in RedMatrix

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#72]
LibertyPod runs RedMatrix 2015-10-01.1172R+63eb0e3 and ZotMor runs Hubzilla 2015-10-04.1175H. 

Posting on LibertyPod will immediately update the browser view, i.e. it will show your new post and any comments once you hit the Share button.

Posting on Hubzilla will update the browser view for a top level post, but it will NOT update the browser view when entering a comment.

LibertyPod automatically showed the comment as it arrived from ZotMor, whilst ZotMor did not show the comment till I manually hit the browser's refresh button.

Note: I am using Firefox Developer Edition 43.0a2 (2015-09-25) when running this test.

**Comment by HaakonME** [comment]
This might help: web console shows a function call to function Yb is done for comments in /network but not in /channel in Hubzilla.

**Comment by HaakonME** [comment]
I now believe this issue might be browser specific, since Firefox Mobile do not seem to have the problem. However, since the PC version only has the problem in /channel and not in /network and the web console output is different, investigating the difference between these two views might give a solution.

**Comment by git-marijus** [comment]
#80 might fix this issue
