### ISSUE TITLE
Beautiful wikis - add web page tools to wiki or wiki to web page tools

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#720]
Hubzilla's web page tools allows beautiful web pages to be created, i.e. with layouts, widgets, Foundation and jQuery and what not, but the same cannot be said about the wiki tool. 

Is it possible to add wiki as a page type to the web page tools to get a beautiful wiki? 

Is it possible to add the web page tools to the wiki app to get a beautiful wiki?

**Comment by git-marijus** [comment]
wiki != webpage

You could give members write access to your webpages though...
