### ISSUE TITLE
nice-to-have: Register-opinion https://hubchart-tarine.rhcloud.com/ on hubzilla.org and demo.hubzilla.org

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#725]
I suggest the register-opinion/ link for https://hubchart-tarine.rhcloud.com/ on https://hubzilla.org -Homepage and on https://demo.hubzilla.org to offer. Thereby the visitor can as the case may be itself 	immediately register on the Hubzilla-grid.

**Comment by git-marijus** [comment]
There is actually /pubsites for that. I don't think https://hubchart-tarine.rhcloud.com is the proper place to find a public hub.

**Comment by elvecio** [comment]
/pubsite lacks of information, I also use "tarine" site to look for a new site/hub ;) ,  I see there some important information to decide on which hub to subscribe.

**Comment by ilu33** [comment]
I agree that https://hubchart-tarine.rhcloud.com has important information for a new user that /pubsites doesn't supply. It's presented in a neutral informative way, very well done.
The only thing missing is the rather improtant info about server roles (pro/standard). Are you  affilliated with the site @elvecio @HappyPony ? Maybe you can pass on the suggestion to incorporate this info?

**Comment by HappyPony** [comment]
I asked also for contact with https://hubchart-tarine.rhcloud.com/ -operator by https://www.openshift.com/ -operator via Twitter.

**Comment by HappyPony** [comment]
I am not affiliated with the site @elvecio .

**Comment by zotlabs** [comment]
Since the referenced server has been offline for some time now and there are no immediate plans to bring it back, the issue seems to have solved itself.
