### ISSUE TITLE
Ability to store address book and contacts

### ISSUE THREAD

**Issue by mobtechpd** [redmatrix/hubzilla#729]
Please add ability to store contacts in hubzilla like in nextcloud or owncloud, and add ability to sync via davdroid app

**Comment by jeroenpraat** [comment]
Is already possible. Please see the CDAV plugin: https://github.com/redmatrix/hubzilla-addons/tree/master/cdav

**Comment by mobtechpd** [comment]
does cdav plugin enabled on https://redmatrix.us ?
