### ISSUE TITLE
YouTube embeds from feeds.

### ISSUE THREAD

**Issue by Gadget-Guru** [redmatrix/hubzilla#73]
[This article](http://thelibertarianrepublic.com/the-luckiest-fools-at-the-shooting-range) from [this feed](http://feeds.feedburner.com/thelibertarianrepublic/PwgM) has a YouTube embed that appears as "[youtube]EpXwIghxaDU[/youtube]" in my stream. I recall that we are no longer using the [youtube][/youtube] bbcode and instead should be [embed][/embed]. We should probably fix this for feeds.

(edit) the example above is not the only one, the issue exists in all feeds with youtube embeds.

**Comment by royalterra** [comment]
I will add to this issue how is present the VIDEO in Hubzilla only show half of the image . Please support better format

**Comment by zotlabs** [comment]
In the standard theme the entire video is shown, but obviously this will not be the case on phones with a 100px wide screen.  The feed issue was fixed several months ago.
