### ISSUE TITLE
Support for Nodeinfo 2.0

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla#732]
There is a new version of the nodeinfo statistics out there
https://github.com/jhass/nodeinfo/pull/17

It would be great if Hubzilla would supports it.

**Comment by zotlabs** [comment]
Federation protocols related to other projects and services are plugins in hubzilla. Please re-open in hubzilla-addons and file against the statistics_json plugin. This is not a core issue. 

The mentioned protocol is so deeply flawed and inflexible that I would discourage developers from wasting their time with it. I would hope that any developer who makes this choice also commits to long-term maintenance of the plugin as it is designed to quickly go stale and requires coding and a new version document for every change in the social web. It cannot be dynamically generated. Version 2 does not even adequately cover Hubzilla and its variants, though it's a slight improvement over version 1.
