### ISSUE TITLE
Interface/Apps problems

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#737]
I lost track of this project due to being otherwise occupied and when - after doing nothing for a couple of month - I updated our server to the newest dev version I realized that our redbasic-derived theme was incompatible. So I switched back to redbasic but still all navigation icons are gone. Also newly added wiki pages don't show up. Everything works as long as I know the exact url but no way to reach anything except settings and connections via menu.
There are dozens of errors but I can't say whether anything is related. Here are some of the recent ones:
```php
PHP Fatal error:  Class 'Zotlabs\Lib\App' not found in .../Zotlabs/Lib/DB_Upgrade.php on line 86
```
```sql
2017-04-26 23:07:00
alter table channel add channel_password varchar(255) not null ;
SQLSTATE[23502]: Not null violation: 7 ERROR:  column "channel_password" contains null values
2017-04-26 23:07:00
alter table channel add channel_salt varchar(255) not null ;
SQLSTATE[23502]: Not null violation: 7 ERROR:  column "channel_salt" contains null values
2017-04-26 23:50:01
select * from item where resource_type = 'nwikipage' and resource_id = '598865c4c745a294a57b3c3b18733dcb5eb78f70e126e2781906b8192bf1720f' and uid = 4 and item_deleted = 0
			 group by mid order by created asc;
SQLSTATE[42803]: Grouping error: 7 ERROR:  column "item.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select * from item where resource_type = 'nwikipage' and res...
               ^
2017-04-26 23:50:55
SELECT * from item WHERE uid = 4 AND ( id = 10710 OR ( resource_type = 'nwiki' and resource_id = 598865 )) ;
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text = integer
LINE 1: ...0710 OR ( resource_type = 'nwiki' and resource_id = 598865 )...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by git-marijus** [comment]
From the releasenotes for version 2.2:

Apps are now central to the Hubzilla experience. The navigation bar has been simplified and an "app tray" provides quick access to Hubzilla functions. You can easily add and remove your own favourite apps from the navigation menu.

Your wikis are now nomadic and can be synced to channel clones and backed up with your channel data. This involved changing the storage format. Old wiki content wasn't migrated for various reasons. Your old wikis are available by enabling the 'gitwiki' plugin. You can copy/paste these existing pages to the new wiki, or paste all existing commits if you feel a compelling need to do so. We've also added specific wiki permissions instead of overloading the webpage permissions.

Max and min version check for core/theme compatibility. We now fallback to the default theme if a theme does not meet the max/min version requirement.

**Comment by ilu33** [comment]
I've read all this. The gitwiki plugin dit nothing so I saved all old wiki pages and I'm trying to create them anew. Now the link to the new page should show up somewhere, shouldn't it? I'd expect it in the left menu under "home" and over "create new page". But there's nothing.

So things like viewing my channel or network or photos are now apps? Well, strange, but if you say so ... I can click "Add Apps" which brings up a left side menu but the window is empty. No apps there for nothing.

And anyway, I have to do something about those errors.

**Comment by git-marijus** [comment]
From what version did you upgrade to dev branch?

Have you tried /gitwiki

**Comment by ilu33** [comment]
I don't remember - how can I find out? I think I did the last update before this one around Jan/Feb and the interface already seemed broken but I had no time to check. I've told users to temporarily just bookmark the URLs. We've always been on dev branch.

**Comment by ilu33** [comment]
There are 3 problems: 
1. Wiki problem: This is the log entry when I open a wiki page, and the sql errors I mentioned in the first post are related.
```sql
2017-04-27 16:46:19:LOG_ERR:ot0ctp9f8or5jrkdh6st4g2qs1:dba_driver.php:461:db_logger: dba_pdo: ERROR: select * from item where resource_type = 'nwikipage' and resource_id = '598865c4c745a294a57b3c3b18733dcb5eb78f70e126e2781906b8192bf1720f' and uid = 4 and item_deleted = 0 
			 group by mid order by created asc;
SQLSTATE[42803]: Grouping error: 7 ERROR:  column "item.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select * from item where resource_type = 'nwikipage' and res...
               ^
```
2. Interface problem: I've no idea, nothing in the (enourmous) logfiles seems to match.

3. The critcal PHP error from my first post which just happened once during upgrade and probably doesn't effect the system anymore.

**Comment by git-marijus** [comment]
The php error you mentioned and th db warnings should be already fixed in dev

**Comment by git-marijus** [comment]
What happens if you go to /apps

**Comment by ilu33** [comment]
Same as if I click "Add Apps" - category menu on the left side but empty window.

**Comment by git-marijus** [comment]
You might have some failed db updates...

**Comment by ilu33** [comment]
I pulled again and now the wiki problems seems to be fixed. 

"You might have some failed db updates..." - Might the php error be involved? How can I check what went wrong?

**Comment by ilu33** [comment]
I had to manually clear the log because it was cluttered with megabytes of "maxversion" theme warnings from the last 12 hours although the offending themes were already disabled. I deleted all themes but the log is still drowning at 10 kb/hour. No idea were it even gets the theme from.

**Comment by ilu33** [comment]
I did the update to 1188 which was successful. No idea about 1183 though and still no apps pages.

**Comment by git-marijus** [comment]
This is update 1183:
`function update_r1183() {

	if(ACTIVE_DBTYPE == DBTYPE_POSTGRES) {
		$r1 = q("alter table hook ALTER COLUMN priority TYPE smallint");
		$r2 = q("alter table hook ALTER COLUMN priority SET NOT NULL");
		$r3 = q("alter table hook ALTER COLUMN priority SET DEFAULT '0'");
		$r1 = $r1 && $r2 && $r3;
	}
	else {
		$r1 = q("alter table hook CHANGE priority priority smallint NOT NULL DEFAULT '0' ");
	}
	$r2 = q("create index priority_idx on hook (priority)");

	if($r1 && $r2)
		return UPDATE_SUCCESS;
	return UPDATE_FAILED;
}
`
You can check if those changes are present in your DB. If not, you need to execute them manually.

**Comment by ilu33** [comment]
Thank you for coming back to this. I'll try to do the repair.

**Comment by ilu33** [comment]
I repaired the missing stuff from update 1183 and checked all database updates thereafter. They should all be ok now. But the interface is still missing. Instead of "<div class="section-content-wrapper"> our pages show <div class="clearfix section-content-wrapper"> in the caption where the apps should be shown. 

We also get the error message "Bootstrap tooltips require Tether (http://tether.io/)" from bootstrap.js. No idea whether this is related.

I'm at a loss how to debug this further. Do you have any ideas how to proceed?

**Comment by zotlabs** [comment]
app['plugin'] in fact was set to 255 spaces or padding characters (which took up three lines on my terminal), which was then checked to see if the plugin with a name of 255 spaces/padding was installed. Pull request #774 is a dirty fix but should work. The proper fix is to change the database schema so that app.app_plugin is varchar(255) instead of char(255); but then the existing apps need to be dropped and the pconfig flag for first time loading of apps also dropped (I believe setting to 0 will not work).

**Comment by ilu33** [comment]
Sorry it took me so long. Works like a charm now, thanks for fixing this. I have to remember that whenever we have a weird problem, it's very probably due to postgresql. I'd never imagined this could be postgres-related.
I've already contemplated to move to mariadb but if we do so nobody would test postgres anymore ...
