### ISSUE TITLE
widget_portfolio with WebDAV

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#745]
Foundation 6's Portfolio template - http://foundation.zurb.com/templates-previews-sites-f6/portfolio.html is used at https://zot-mor.rhcloud.com/page/art/thatsimpossible . 

The current album widget takes the arguments album and title, and displays photos uploaded with WebDAV sync closely spaced. 

It would be nice to copy the album widget to widget_portfolio , giving the appearance from the Portfolio template, with two more arguments - photo title and number of images from the portfolio, so that it will be possible to show say three images from the portfolio if you are logged out and some higher number once you are logged in.

The reasoning behind this is to make it easy for artists to showcase their portfolios' with Hubzilla.

Is this hard to do?

**Comment by zotlabs** [comment]
Should be pretty easy to do. You're really just altering the SQL of the album widget slightly and applying a different template. The best way I can think of to set the count is allow the widget to take a count as an argument (let's call it 'limit' for consistency with other tools) and then

[var=limit][if $observer.name]999[else]3[/if][/var]

**Comment by HaakonME** [comment]
Nice. Is https://github.com/redmatrix/hubzilla/blob/master/view/tpl/photo_album.tpl the right template?

**Comment by zotlabs** [comment]
That looks correct.

**Comment by zotlabs** [comment]
@HaakonME can we close this?

**Comment by HaakonME** [comment]
Yes. We need to remember to fix the other problem of syncing photos.
