### ISSUE TITLE
missing "Embed image from photo albums" menu

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#746]
By browser-window-size < 970 px disappears "Embed image from photo albums" menu - s. screenshots

**Size > 970 px**

![embed-image-from-album](https://cloud.githubusercontent.com/assets/3226308/25650839/ee73f88e-2fdf-11e7-8b70-f4169fe60761.png)

**Size < 970 px**

![none-embed-image-from-album-menu](https://cloud.githubusercontent.com/assets/3226308/25650840/ee79ff9a-2fdf-11e7-866f-dbb02983d9cf.png)

**Comment by git-marijus** [comment]
This is already fixed ib dev branch iirc
