### ISSUE TITLE
OpenShift quota per gear issue: how to put a cap on dreport?

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#75]
One of my Hubzilla gears - 1Gb - on OpenShift have gone full in less than a few hours. The real surprise was how big the new delivery report was - a whooping 150Mb! How can I put a cap on log or report sizes like this? Is there a configuration setting? For now, I had to truncate the dreport table to get some of my quota back.

**Comment by zotlabs** [comment]
This has been configurable for the last year or so.
