### ISSUE TITLE
multilple repetition of results in the Hubzila-search result list

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#757]
in the Hubzila-search result list are multilple repetition of items. Namely, that are versions of edited items.

Here for example the searchresults for string "zip"  https://hub.libranet.de/search?search=zip

![hubzilla-serp](https://cloud.githubusercontent.com/assets/3226308/25768866/04f3f88c-320d-11e7-9d0c-ba8c9210282b.png)

**Comment by git-marijus** [comment]
This has been addressed here in commit 40c8549cf5438aa12db68c6ec2c98493f6707bda
