### ISSUE TITLE
filtered to remove edit activities for notifications 

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#758]
Here 

![838](https://cloud.githubusercontent.com/assets/3226308/25779208/276647c4-3313-11e7-978a-411142bee0d5.png)

says notification demon "commented on member abc's post", although in this case, the member abc only modified the post. I believe that commented-wording misleading for this event. Especially Hubzilla-Beginners maybe to look vainly for comments :-|.  Mike mean 

> The notifications probably need to be filtered to remove edit activities. 

s. [Misleading notification for modified event](https://hub.freecommunication.org/channel/nmoplus/?f=&mid=d97fcb261839538a4f4592dfa1972376be6f366b88efee0a26c0ed5352627570@hub.freecommunication.org&zid=nmoplus%40hub.freecommunication.org)

**Comment by git-marijus** [comment]
This has been addressed here in commit 40c8549cf5438aa12db68c6ec2c98493f6707bda
