### ISSUE TITLE
watch-utility for sync-complete 

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#759]
One watch-utility for review, above sync-complete. I suggest, when synchronization to chec above count of webpages on original-profil accord with the  count of webpages on clone-profil.  Because now and then synchronisation has failed. 

For example I cloned my hub.freecommunication.org-`nmoplus` -Profil on `hub.libranet.de` -Hub at moment `xyz`. After Login on https://hub.libranet.de are for me yet only these webpages available, these I modify on the `hub.freecommunication.org` after the time `xyz`. Is it a bug or feature, that not all webpages from hub.freecommunication.org-`nmoplus` -Profil are available for the hub.libranet.de -clon?

Hubzilla-Version:

    hub.freecommunication.org - 2.0.6
    hub.libranet.de - 2.2

s. also [not all webpages from original -Profil are available for the clon](https://hub.freecommunication.org/channel/nmoplus/&f=&mid=fd2f0eaea5f4ddc1b20ce0801828f5579f5a5b0ed811753d413e4fe08e4f782c@hub.freecommunication.org)

**Comment by HappyPony** [comment]
Also blocks, menus, Layouts and pages are vulnerable to this error. I reproduced this bug for two hubs.

Hubzilla-Version:
   - source -> hub.freecommunication.org - 2.0.6
- target -> hub.libranet.de - 2.2

**Comment by zotlabs** [comment]
Retroactively discovering sync failures could exhaust server resources for smaller sites. The best solution by far would be to analyse why it failed and fix that.

**Comment by HappyPony** [comment]
Can you clarify, what you mean with "smaller site"? Respectively, what of server features do you need to know for the analyse? Need you data from source or from target server? I guess, I can reproduce this bug any time. Reproduce scenario - create one clone of Hubzilla channel, that is at hub.freecommunication.org hosted.

**Comment by zotlabs** [comment]
When you add or update a page, a sync packet containing the changes is sent to your clone. So first you need to know if this sync packet is being sent. Then you need to know if it is being received. If it is, then why doesn't the content in the sync packet get synced properly?

That's pretty much all there is to it.

**Comment by HappyPony** [comment]
Oh, I **my intention is, that old, after moment `xyz` not modified pages from `hub.freecommunication.org`** - s. details in the startpost - **are not exist at `nmoplus` -Profil on `hub.libranet.de` while I modify these pages on `hub.freecommunication.org`** . When I modify one page on `hub.freecommunication.org` after moment `xyz`, then is this page created at `nmoplus` -Profil on `hub.libranet.de`.

**Comment by git-marijus** [comment]
In fact i don't think there is a bug. @HappyPony in a later comment writes in german language that only the pages that were created before the clone was created were not synced. That is by design though. When the not synced pages were edited they did sync. So everything works as expected.

**Comment by HappyPony** [comment]
> In fact i don't think there is a bug.

I cloned one Profil from Hub H1 with Hubzila Version 2.2 to Hub H2 with Version 2.3.2. The 'old' webpages from H1 are also cloned. But the in webpages contains images are on Hub H2 not displayed.
