### ISSUE TITLE
parsed code in [code]snippet[/code]

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#765]
Code in `[code] here code[/code]` [for example here](https://hub.freecommunication.org/channel/nmoplus/?f=&mid=08ca90206e721b5f1df595b9530a1ed297a85ebd0ee6e56bec9575c504179842@hub.freecommunication.org&zid=nmoplus%40hub.freecommunication.org) was parsed and the image was inserted. I mean ist ist a bug, that the image inserted is. I mark the snippet as code, so that any image inserted was.

**Comment by git-marijus** [comment]
We have the [nobb][/nobb] tag for not parsing bbcode.
