### ISSUE TITLE
The clone changes the photo address in my post without permission.

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#769]
The clone changes the photo address in my post without permission.
In the post I have a photo with /hub1/cloud/misterx/photo123456789.jpg
And in the clone, the same post, I have /hubclone/cloud/misterx/photo123456789.jpg

hub1 becomes hubclone, so in my clone  I can not see more the photo in the post.
And of course the photo has not been copied into the "hubclone" , so there is no file inside.

**Comment by zotlabs** [comment]
> And of course the photo has not been copied into the "hubclone" 

Why not?

**Comment by elvecio** [comment]
Genuinely I do not know the intention of the software about this. If the intention is to copy the file to the new hub (the file with the same identical name), then it did not work, my cloud in the "hubclone" is completely empty. I basically believe that the path/address of the file/photo does not have to change but it remains the same (in the original hub) also in the source code of the "cloned post" ( in the hubclone).

**Comment by git-marijus** [comment]
There were another two commits related to this issue: 912be5a792b286f844a2c933fd5f7775a34887a4 and 30358100ab729e7ce7bd3f05cc64a391239906e0
Please try again. Probably best with two dev hubs...
