### ISSUE TITLE
wrong parsing for string [observer.baseurl]/settings/features

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#772]
This string ` [observer=1][observer.baseurl]/settings/features[/observer] -> Additional Features` will be wrong parsed. Only with one line break is the result OK. For example:
> [observer=1][observer.baseurl]/settings/features[/observer]
-> Additional Features` 

S. also [Searchquery limited for searchresults from your favoured channel](https://hub.libranet.de/page/flegno/searchquery-for-results-exclusively-with-results-from-your-favoured-channel)

**Comment by zotlabs** [comment]
Please provide precise steps to duplicate, such as what tool was being used (post editor, webpage editor, wiki editor, etc.) and what content-type was being used if applicable. For instance the wiki only supports a small subset of the available bbcode observer tags when using markdown.  I was not able to reproduce using any of these tools and bbcode content-type - with or without linebreaks. All rendered perfectly. When using markdown, the webpage editor didn't convert any tags at all, and the wiki only converted observer.baseurl . This is all known behaviour as markdown shouldn't be expected to render bbcode - even though it's partially supported in the wiki.

**Comment by HappyPony** [comment]
I can not duplicate this behavior
