### ISSUE TITLE
synchronization webpages for cloned channel failed

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#776]
I cloned my channel from https://dev.hubzilla.org to https://econpros.com/ . Both hubs have Hubzilla-Version 2.5

I have on https://dev.hubzilla.org/ several blocks, menus, layouts and pages in https://dev.hubzilla.org/channel/flegno . But here https://econpros.com/ is synchronized only one menuitem https://econpros.com/mitem/141
> Color-carrousel  created: 2017-05-14 17:24:23, changed 2017-05-14 17:24:23

Notice: ( "Color-carrousel" is the Menu Name)

**Comment by HappyPony** [comment]
When I change pages or Lother obejcts on https://dev.hubzilla.org/ , these are not synchronized on https://econpros.com/ . S. also bug #759

**Comment by zotlabs** [comment]
I'm getting a DNS failure and cannot connect to econpros.com - perhaps this is the reason?

**Comment by HappyPony** [comment]
For me is https://econpros.com/ currently availably. But I'm getting again and again the message:
> Apologies but this site is unavailable at the moment. Please try again later.

**Comment by zotlabs** [comment]
If you know how to reliably synchronise and/or store data on dead or intermittently running websites, feel free to submit a patch.
