### ISSUE TITLE
parser miscarries on special characters

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#777]
parser miscarries on special characters, for example german umlauts:
```
[dl]
[*=Hochverfügbarkeit] 
[*=Hochverfuegbarkeit] 
[/dl]
```
The string `Hochverfügbarkeit` will be in dl-item not parsed, but Hochverfuegbarkeit

**Comment by zotlabs** [comment]
add 'u' to the preg options

or cherry-pick red  2cc1844d979 and 5c8a911c933

**Comment by HappyPony** [comment]
@zotlabs Is this comment 
> add 'u' to the preg options
> 
> or cherry-pick red 2cc1844d979 and 5c8a911c933

for me?

**Comment by HappyPony** [comment]
parser miscarries in [dl]-statement also on **cyrillic characters**, for example 
> [*=Вездесущность] под вездесущностью в Hubzilla-контексте понимается способность и возможность для участников Hubzilla-сети принимать полноценное участие в жизни сети везде, ...

**Comment by zotlabs** [comment]
Yeah I know - it will happen for pretty much any unicode character sequence, Navajo, Sanskrit, Dingbats, anything. I fixed it a week ago, but I don't use Hubzilla, so if you want to fix it, visit include/bbcode.php (dev tree), and go to line 386 and change /ism to /uism and submit a pull request.
