### ISSUE TITLE
observer values empty

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#784]
observer values will be displayed in preview in block editor, but in the webpage http://hub2.sprechrun.de/page/flegno/switch are this values empty. Hubzilla-Version 2.4RC

![5](https://cloud.githubusercontent.com/assets/3226308/26166184/f460fbe4-3b32-11e7-85ae-c81e6d3630a9.png)

![6](https://cloud.githubusercontent.com/assets/3226308/26166048/8fd0e61c-3b32-11e7-920d-f32942c2df3b.png)

**Comment by git-marijus** [comment]
Works for me. Note that you must authenticated for observer related code to work.
