### ISSUE TITLE
Attachment in post uploads successfully to Files yet disappears in post

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#787]
Parlementum.net runs 2.5, and upon uploading images in a post as attachment, the wheels spins, then nothing appears in the post. 

Checking in Files, the attachment is uploaded successfully.

Prior to adding the attachment, some text was written and a link inserted with the Link-button.

**Comment by git-marijus** [comment]
I can't reproduce this.

**Comment by HaakonME** [comment]
I think I have a clue as this happened again - the attached image is uploaded to Files but is not included in the post, and it is not possible to use the embed from photo album either. The image is in portrait mode, rather than landscape mode, resolution 4032×2268. Could the problem be the orientation at that resolution?

**Comment by zotlabs** [comment]
The problem could easily be that you've exhausted memory trying to rotate it correctly. Just loading the photo in memory is going to consume around 30MB. Rotating will double that. Storing it will use another 30MB at least. How much memory does your PHP have available?

**Comment by HaakonME** [comment]
I see. Thanks, I will check with the admin.

**Comment by zotlabs** [comment]
You could possibly create a config to bypass the auto-rotation. That would save a bit of memory. But we also use the same function to read exif info for displaying a map if you have that feature enabled. So even then probably it isn't an easy fix as one would need to split out the bit that reads exif.
