### ISSUE TITLE
menu vanished for window width less as 745 px, Version 2.4RC

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#792]
menu vanished for window less as 745 px

![1](https://cloud.githubusercontent.com/assets/3226308/26282379/e2547a3a-3e10-11e7-944a-2e44a420275b.png)

**Comment by git-marijus** [comment]
When you change the window size the button to bring in left aside does not appear right? We need to add an on resize controler to that functionality. The code is in /view/theme/redbasic/js/redbasic.js it will need some additional jquery...

**Comment by HappyPony** [comment]
> When you change the window size the button to bring in left aside does not appear right? 

Correct, the menu from left aside is vanished.
