### ISSUE TITLE
invalide URL by restore of encoded characters

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#795]
That is one valide URL - Click -> https://dev.hubzilla.org/page/expertmode/ru/seo-%d0%be%d0%bf%d1%82%d0%b8%d0%bc%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%bd%d0%be%d0%b5-%d1%81%d1%82%d1%80%d1%83%d0%ba%d1%82%d1%83%d1%80%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d0%b5-%d1%81%d0%be%d0%b4%d0%b5%d1%80%d0%b6%d0%b0%d0%bd%d0%b8%d1%8f-%d0%bc%d0%bd%d0%be%d0%b3%d0%be%d1%8f%d0%b7%d1%8b%d1%87%d0%bd%d1%8b%d1%85-%d1%80%d0%b5%d1%81%d1%83%d1%80%d1%81%d0%be%d0%b2

But when I store this webpage item repeatedly, then is the webpage-URL invalide. I assume, that Hubzilla convert erroneously stored escaped character repeatedly. You can reproduce this behavior, when you for example in Hubzilla 

1) create one webpage with this ` Page link name`-value
> ru/SEO-оптимированное-структурирование-содержания-многоязычных-ресурсов 

2) `store `the item from step 1
3) `edit `the item from step 1
4) `store `the item from step 1
5) `click` on the stored URL from step 4

`Hubzilla-Version 2.5.2`

**Comment by zotlabs** [comment]
devs: The fix to this can be cherry-picked from red 1b75e4d

**Comment by HappyPony** [comment]
@zotlabs can you please post a link to 1b75e4d -fix?
