### ISSUE TITLE
Comments to photo posts disappear from photos module after edit

### ISSUE THREAD

**Issue by solstag** [redmatrix/hubzilla#801]
I had uploaded a photo creating a post on my channel.

I commented on that post. The comment showed up when viewing the photo in the photos module.

I edited the post, then I edited the comment.

The comment no longer appears associated with the photo in the photos module.

**Comment by zotlabs** [comment]
Was not able to duplicate. I'm aware some work was done on the photos interactions a month or two ago so this may have been fixed.

**Comment by solstag** [comment]
Ok, so I waited the update to 2.8 to try to reproduce this, but now when clicking on "Edit" for the post created by a photo upload I am met with a blank page and an "Item is not editable" popup message.

Is that by design or another bug? If that's expected I shall close this bug. Thanks!

**Comment by zotlabs** [comment]
I now understand the original issue a bit better. You attempted to edit the "linked item" which is attached to every photo, not a post that you had uploaded a photo into. This "linked item" is not and should not be editable, as it contains a lot of metadata about the photo and editing it is something like using the Windows Registry Editor - you can really mess things up if you aren't careful. So the "Item is not editable" is the correct response. Editing comments attached to the photo is supported, and some attributes of the photo such as changing the caption and tags is supported through editing in the photos module, but not in the editpost module.

**Comment by solstag** [comment]
Perfect, done with this then!
