### ISSUE TITLE
Installer fails to create some Mysql tables

### ISSUE THREAD

**Issue by mtancoigne** [redmatrix/hubzilla#803]
Following the INSTALL guide, i'm setting up an instance of Hubzilla on an OVH VPS.

When creating the database tables, I have these errors:

```log
Erreurs rencontrées pendant la création de tables de BDD.

CREATE TABLE IF NOT EXISTS `abook` (
  # some truncated content
) ENGINE=MyISAM  DEFAULT CHARSET=utf8

Erreurs rencontrées pendant la création de tables de BDD.

CREATE TABLE IF NOT EXISTS `app` (
  # some truncated content
) ENGINE=MyISAM DEFAULT CHARSET=utf8

Erreurs rencontrées pendant la création de tables de BDD.

CREATE TABLE IF NOT EXISTS `profile` (
  # some truncated content
) ENGINE=MyISAM  DEFAULT CHARSET=utf8

Erreurs rencontrées pendant la création de tables de BDD.

CREATE TABLE IF NOT EXISTS `site` (
 # some truncated content
) ENGINE=MyISAM DEFAULT CHARSET=utf8
``` 

I tried to manually create the table and got these errors:
  - table `abook`: _BLOB, TEXT, GEOMETRY or JSON column 'abook_incl' can't have a default value_
  - table `app`: _BLOB, TEXT, GEOMETRY or JSON column 'app_desc' can't have a default value_
  - table `profiles`: _BLOB, TEXT, GEOMETRY or JSON column 'profile_vcard' can't have a default value_
  - table `site`: _BLOB, TEXT, GEOMETRY or JSON column 'site_crypto' can't have a default value_

So I updated the queries, removing the default value for all the TEXT fields.

**Comment by git-marijus** [comment]
What mysql version are you using?

**Comment by mtancoigne** [comment]
it's mysql-server 5.7.18-0ubuntu0.16.04.1

**Comment by git-marijus** [comment]
Thanks for reporting. We will fix this asap.

**Comment by dawnbreak** [comment]
@git-marijus Do you have already worked on this? I finally got MySQL 5.7 included in Travis and it complains about this. Will prepare a PR soon, but I haven't looked into the SQL error yet.

**Comment by zotlabs** [comment]
It doesn't appear to be fixed yet. Basically remove any DEFAULT clause from text and mediumtext fields. There are only a few places.  

Don't know if you're up for it, but I've also been converting everything to innodb and utf8mb4 in my other fork. That also requires all char(255) fields to be changed to char(191) so that it doesn't complain about index limits. So far I haven't seen any problems.

**Comment by git-marijus** [comment]
I am pretty busy atm and have not fixed that issue yet @dawnbreak. There is a fix in mikes repo but this one will likely have merge conflicts.
Anyway, i was planning to merge mikes work on porting the DB to innodb in this release cycle.
So a PR would be highly appreciated 😃

**Comment by mtancoigne** [comment]
@git-marijus noted, i'll try to do it tonight.

**Comment by mtancoigne** [comment]
The PR is open, sadly, I could not test it on a fresh install... If you want me to do it, i'll have to go home first...

**Comment by git-marijus** [comment]
Looks good to me. Thanks for the PR
