### ISSUE TITLE
domain/cloud/channelname returns white page

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#807]
I am running DEV, version 2.5.2.

Logged in users at https://zot-mor.rhcloud.com/ are greeted to a white page when they try to view their Files, e.g. https://zot-mor.rhcloud.com/cloud/haakon

**Comment by zotlabs** [comment]
Unable to duplicate here. Do you have PHP logging enabled? That's the first thing to check for white screens.

**Comment by dawnbreak** [comment]
I have updated some of the Sabre libraries, but had no problem on my machine. Can you see if commit a7ecf519156c1110acbb0eadd13dee63b7adaabd is still working (git checkout a7ecf519156c1110acbb0eadd13dee63b7adaabd).
Will look into it tonight when I have access to my dev environment.

**Comment by zotlabs** [comment]
fwiw I had no problem after the Sabre update. The only thing I can think of is that they might have dropped PHP 5.5 support as they often drop deprecated versions, but I don't think Haakon is using that.

**Comment by dawnbreak** [comment]
Could not reproduce yet on different environments. PHP5.5 is still supported. 5.4 shouldn't have worked before.
Need some logs.

**Comment by HaakonME** [comment]
These lines in the PHP log seem relevant:
`213.136.74.244 - - [04/Jun/2017:12:22:03 -0400] "POST /post HTTP/1.1" 200 16 "-" "Red"
[Sun Jun 04 12:22:04 2017] [error] [client 127.6.95.1] PHP Parse error:  syntax error, unexpected '$yieldFirst' (T_VARIABLE) in /var/lib/openshift/55999305e0b8cd838f000053/app-root/runtime/repo/vendor/sabre/dav/lib/DAV/Server.php on line 887
81.166.162.135 - - [04/Jun/2017:12:22:04 -0400] "PROPFIND /dav/haakon HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64) KHTML/5.18.0 (like Gecko) Konqueror/5.18"
81.166.162.135 - - [04/Jun/2017:12:22:14 -0400] "PROPFIND /dav/haakon HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64) KHTML/5.18.0 (like Gecko) Konqueror/5.18"
[Sun Jun 04 12:22:14 2017] [error] [client 127.6.95.1] PHP Parse error:  syntax error, unexpected '$yieldFirst' (T_VARIABLE) in /var/lib/openshift/55999305e0b8cd838f000053/app-root/runtime/repo/vendor/sabre/dav/lib/DAV/Server.php on line 887
176.58.122.108 - - [04/Jun/2017:12:22:19 -0400] "POST /post HTTP/1.1" 200 16 "-" "Red"
62.210.122.6 - - [04/Jun/2017:12:22:22 -0400] "POST /post HTTP/1.1" 200 16 "-" "Red"`

**Comment by HaakonME** [comment]
In the OpenShift v2 environment, the only persistent storage is what is put into the $OPENSHIFT_DATA_DIR - the rest is deleted and replaced on each push, so the .openshift/action_hooks/deploy script creates or checks for the existence of symlinks to $OPENSHIFT_DATA_DIR to make sure important files are preserved, e.g. config files and the Hubzilla store directory needs to be there.

```
drwxrwx---.  3 myappid myappid     31 2017-06-04 12:07 store/

[zot-mor.rhcloud.com repo]\> cd store
[zot-mor.rhcloud.com store]\> ls -laF
totalt 4
drwxrwx---.  3 myappid myappid   31 2017-06-04 12:07 ./
drwxr-x---. 16 myappid myappid 4096 2017-06-04 12:07 ../
drwxrwx---.  3 myappid myappid   20 2017-06-04 12:30 [data]/
lrwxrwxrwx.  1 myappid myappid   63 2017-06-04 12:07 store -> /var/lib/openshift/myappid/app-root/data/store/
```

Now, I have not changed the script AFAIK (checked gitk), so why this suddenly stopped working is a bit weird. I have not looked at this in ages, but I do find it a bit strange that there in the main directory is directory called store and in that a subdirectory which is a link to the real store.

**Comment by git-marijus** [comment]
That indicates that you are using php version < 5.5
yield was introduced in 5.5

**Comment by HaakonME** [comment]
Indeed, the cartridge is php-5.4.

**Comment by HaakonME** [comment]
Does this mean Files will be unavailable because of php version < 5.5 ?

**Comment by git-marijus** [comment]
I think we are at 5.5 min version since quite a while.

**Comment by HaakonME** [comment]
Yes, I know, it just has not been a problem till now, but I think it is unrelated. Luckily, I found another clone, which seems to indicate "something" did change - the store directory in the main Hubzilla directory is supposed to be a symlink, so something has gone bump in the night at ZotMor. I will fix that, and then we can see if the problem is resolved - thanks for all your help so far.

**Comment by HaakonME** [comment]
It seems the yield code in 

vendor/sabre/dav/lib/DAV/Server.php

is quite recent - May 4th 2017.

`@@ -877,12 +878,14 @@ class Server extends EventEmitter implements LoggerAwareInterface {
     /**
      * Small helper to support PROPFIND with DEPTH_INFINITY.
      *
-     * @param array[] $propFindRequests
      * @param PropFind $propFind
-     * @return void
+     * @param array $yieldFirst
+     * @return \Iterator
      */
-    private function addPathNodesRecursively(&$propFindRequests, PropFind $propFind) {
-
+    private function generatePathNodes(PropFind $propFind, array $yieldFirst = null) {
+        if ($yieldFirst !== null) {
+            yield $yieldFirst;
+        }`

**Comment by HaakonME** [comment]
Is it safe to revert the file?

**Comment by git-marijus** [comment]
It probably won't work.

**Comment by HaakonME** [comment]
Probably not, but how would I do it?

**Comment by git-marijus** [comment]
Does 2.4 work for you? This update is in dev branch only so far...
