### ISSUE TITLE
Double photos  Double files ?

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#813]
Maybe just a stupid question...
the path /photos  really exists or is a sort of 'alias' for /cloud ?
If exists , we have double photos and so double files  in the server?

**Comment by zotlabs** [comment]
It represents a different view of the image files that are stored in /cloud. Some code and data structures are duplicated to create this view and generate representative thumbnails of the photos, but no - the files themselves are not duplicated.
