### ISSUE TITLE
Get the post in plain text via Zot API?

### ISSUE THREAD

**Issue by Flashwalker** [redmatrix/hubzilla#816]
If i post via **Twitter API** in **HTML** markup, hub converts the post from **HTML** to **bbcode**, and when i get request the post via **Twitter API** i get the post converted from **bbcode** to **plain text** (without **bbcode**), which is good.

Is there a way to get **plain text** (without **bbcode**) via **Zot API**?

**Comment by zotlabs** [comment]
Not currently.
