### ISSUE TITLE
Enhancement: Add support for Markdown

### ISSUE THREAD

**Issue by Flashwalker** [redmatrix/hubzilla#817]
Due to currently **bbcode** parser is ugly dumbass who breaks the text,  how about to implement support for **Markdown + custom HTML** tags in parallel or instead of **bbcode**?

It would be nice:

\+ It would be much easier to write posts  
\+ raw **HTML** support rocks \o
\+ the only differents for custom bbcode tags would be the `<>` brackets (e.g.: `<embed>http://youtu.be/bla-bla</embed>`), so there is no disadvantages.

**Comment by zotlabs** [comment]
We had markdown support for years - but nobody was interested enough to support it when bugs were encountered - mostly dealing with preservation of whitespace and handling code blocks. 

The code is still there (and we offer markdown as an input choice for webpages and wikis); but it's currently commented out for posts/comments until the bugs are fixed.

Most of the editor tools work with bbcode, and these tools have also been enhanced over the years, so bringing markdown back requires either a parallel set of editor tools be developed; or as we did originally - convert markdown to bbcode so the editor tools would work without modification. This is where most of the problems occurred - as markdown to bbcode means markdown to html to bbcode and there are inevitably small differences with each conversion. 

The security ramifications of markdown are much more serious. It's a mother to purify markdown without introducing further conversion bugs. Anyway that's where it sits at the moment. If you want it, pull requests that sort out all the issues and offering ongoing support are welcomed.

**Comment by Flashwalker** [comment]
For now, if i post `text/bbcode` via Zot API:
```
[b]bla-bla-bla[/b]
http://www.youtube.com/watch?v=####
https://vimeo.com/####

[b][i]bla-bla-bla-bla[/i][/b]
```

Parser breaks it to smashed сrap:
```
[b]bla-bla-bla[/b][embed]http://www.youtube.com/watch?v=####
#^[url=https://vimeo.com/####

]https://vimeo.com/####

[/url][/embed][b][i]bla-bla-bla-bla[/i][/b]

```

But posting the same from post composing web form returns:
```
[b]bla-bla-bla[/b]
[embed]http://www.youtube.com/watch?v=####[/embed]
[embed]https://vimeo.com/####[/embed]

[b][i]bla-bla-bla-bla[/i][/b]
```

Is it **API** or parser's issue?  
I'm using **curl** like this:
```
$ xclip -o -sel c | curl -F 'sprunge=<-' http://sprunge.us
$ xclip -o -sel c | curl -F 'f:1=<-' ix.io
```
and it posts properly: http://sprunge.us/JPIH , http://ix.io/xzp

**Comment by zotlabs** [comment]
I think it's getting mangled by the procedure to attempt to embed the "naked link" videos with oembed; which would likely have the same issues with markdown. You can probably avoid this processing step and get consistent results when posting by either wrapping the "naked links" with [embed]....[/embed] or [url]...[/url]. We just try and turn them into embedded videos because that's what people expect us to do. To do this we have to probe the actual URL and see what's there and see if there's a way we can embed it. We also need to check the site policy and see if should be filtered or re-written. While this process should in theory be consistent, there's so much processing behind the scenes and several network fetches that it's pretty easy for something to go wrong.

**Comment by Flashwalker** [comment]
Ok, thnaks

**Comment by Flashwalker** [comment]
I found what breaks the url - is the same issue as: https://github.com/redmatrix/hubzilla/issues/755  
Perhaps the line endings issue...  
So, for workaround: oembed won't smash plain url if add trailing **space** right after url.

For those, who interesting in markdown workaround, i'm using this perl script for markdown to bbcode converting: https://gist.github.com/Flashwalker/360e8615bff1b9b322e0096fe92680ab  
and  
for posting to Hubzilla in markdown via API: https://github.com/Flashwalker/hzclish
