### ISSUE TITLE
type server?

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/hubzilla#823]
Url 
Site/admin/site
[![imagebin](http://upimage.mamalibre.com.ar/up/7ec72947697e9bf843195a8c5801bdd4.png)](http://upimage.mamalibre.com.ar/#7ec72947697e9bf843195a8c5801bdd4.png)

**Comment by zotlabs** [comment]
Just select 'standard'. That is going away in the next release.

**Comment by mama21mama** [comment]
Ok. Gracias camarada....otro problema mi servidor por que no puede participar en foros?
