### ISSUE TITLE
Seguridad y privacidad

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/hubzilla#824]
Por defecto no es %100 federado.
Hay que activar la federacion completa.

Ejemplo de comentarios federados:

http://hubzilla.mamalibre.com.ar/channel/mama21mama/?f=&mid=cc2a34f8fd0369971566e85724603b33958e2d1cca1eb34b23b31bf924bedb41@hubzilla.mamalibre.com.ar&zid=mama21mama%40hubzilla.mamalibre.com.ar

**Comment by git-marijus** [comment]
Sorry, i don't understand. Mind to translate?
