### ISSUE TITLE
like-button for images

### ISSUE THREAD

**Issue by lazyadmin111** [redmatrix/hubzilla#826]
Hey there,

I just upgraded to version 2.4 of hubzilla, I used before hubzilla 2.2 and before 2.0. In all versions of hubzilla the "like" button worked great for posts but when I go to an album and want to like an individual image, then the like buttons most of the time doesn't work. Sometimes however it works. 

When I press the button, the image is redrawn, but no like-"marker" appears, its just as before. However at least a couple of time the pressing of the button had some effect: the corresponding image was "unhided", it appeared in my network stream, however, even there no likes were included. 

As updating hubzilla didn't solve this problem, but just caused me more troubles, I would like to dig down this annoying bug, maybe someone can give me some hints where to start looking and I will try to to find it on my own.

I run debian jessie...

**Comment by git-marijus** [comment]
I can not duplicate this.
Please take in account that the like button is a toogle. Clicking it a second time will undo the like.

**Comment by lazyadmin111** [comment]
Hey git-marijus,

Thanks for your reply. Yes you are right, this makes the things complicated to test. However, I am sure that it doesn't work as it should, it failed so often.
Maybe if you can give me a more private contact address (--no google/MS/... please), then I can let you know my server-URL, and you can see it on your own... :-)

Does anyone know where to look at in the code, to debug this?

greets,

**Comment by lazyadmin111** [comment]
btw, if checked the debug logs of hubzilla, and when I hit the like-button of an image, the following output is generated:
```
2017-07-17 16:03:48:LOG_INFO:vufrv9obbks4hedpvicq0atsr3:items.php:1621:item_store: revision: 0
2017-07-17 16:03:48:LOG_INFO:vufrv9obbks4hedpvicq0atsr3:items.php:1774:item_store: item_store: item parent was not found - ignoring item
2017-07-17 16:03:54:LOG_INFO:vufrv9obbks4hedpvicq0atsr3:items.php:1621:item_store: revision: 0
2017-07-17 16:03:54:LOG_INFO:vufrv9obbks4hedpvicq0atsr3:items.php:1774:item_store: item_store: item parent was not found - ignoring item
```

Does anyone know if this helps to find the bug, or if this is normal?

**Comment by git-marijus** [comment]
Do you have this issue with one (old) photo or with all photos?

**Comment by lazyadmin111** [comment]
this is a longstanding bug, I have since hubzilla 2.0 with ALL photos

**Comment by git-marijus** [comment]
Can you upload a new photo and like it and provide the logs?

**Comment by lazyadmin111** [comment]
**What kind of log level do you need? -- I tested it again, and just got those 4 lines in there... I suspect you want more or? :)**

Btw, it seems to work in my case, if I upload a new photo and then like it, however I can't like photos of a friend of mine on the same hub...

**Comment by zotlabs** [comment]
Was able to duplicate this reliably. To reproduce, you need to like somebody else's photo in their own photo library (in this case I'm testing with two identities on the same system). In item_store() the search for a parent is using your own uid, and if the item wasn't shared you may not have a copy of the parent item, hence item_store() fails.

**Comment by bastlwasti** [comment]
I updated from version 2.8 to hubzilla version 3.0 now, and I can verify that this bug indeed disappeared.
It had persisted at least from version 1.8

**Comment by bastlwasti** [comment]
I updated from version 2.8 to hubzilla version 3.0 now, and I can verify that this bug indeed disappeared.
It had persisted at least from version 1.8 and I am very happy to finally be able to like the photos of my friends! :-)) Thank you very much!
