### ISSUE TITLE
Privacy groups not syncing across clones properly

### ISSUE THREAD

**Issue by pkillnine** [redmatrix/hubzilla#832]
What doesn't sync:

 - Changing name of privacy group
 - Deleting privacy group

What does sync:

 - Creating new privacy group
 - Adding/removing members to/from privacy group

_Other observation_: If I delete a privacy group on one hub, then add a connection to that privacy group on the second hub (on this other hub the privacy group hasn't been deleted), that privacy group doesn't reappear on the first hub.

**Comment by zotlabs** [comment]
Fixed in my personal repository. This should land on hubzilla in a day or two with the next batch of updates.
