### ISSUE TITLE
How to reliable find profile_uid if App::$profile['profile_uid'] is empty?

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#833]
We make use of App::$profile['profile_uid'] in include/nav.php to determine if we are the channel owner. This is not populated on every page though.

**Comment by zotlabs** [comment]
Can you provide an example of where it's missing? We intentionally only include that on "channel pages" (where you are typically shown a profile on the sidebar).  Most others are system pages and don't have an owner per se. Just thinking ahead, the 'cal' module might be lacking this.

**Comment by git-marijus** [comment]
I was thinking about the /network page by example. But i did not consider that a "system" page.

I was basically trying to make decisions in the app bin based on if we own the page or not in regard to viewing another (not ours) local channel.
I think it would make sense to make it look like looking at a remote channel (without our own channel apps like Activity, Mood, etc.  and Add Apps and Arrange Apps links). While i succeeded hiding the Add Apps and Arrange Apps links i could not manage to hide our own apps. I figured i would need to create another app requirement besides local_channel for that - something like owner (which would be local_channel() and local_channel = profile_uid) but failed with that because we don't have an profile_uid in Apps.

**Comment by zotlabs** [comment]
Actually mod_network does set App::$profile_uid, but it doesn't load the profile, which also sets App::$profile (and by extension App::$profile['profile_uid']).

So you could probably just change the check in nav.php to look at the former.

**Comment by git-marijus** [comment]
Ok... I guess what i am looking for would be something like:
`$is_owner = (((local_channel()) && ((App::$profile_uid == local_channel()) || (App::$profile_uid == 0))) ? true : false);`

That would claim ownership of system pages and our own pages which is correct actually...

**Comment by git-marijus** [comment]
Do you think it would make sense to introduce another app requirement matching the above clause for the apps we "own" so they would not be displayed in the app bin under system apps if we view another local channel?

Basically it would be the experience of looking at a remote channel except that we would keep the notifications.

I think that would streamline the userexperience a bit more. It would have the downside of one more click to get back home though...

**Comment by git-marijus** [comment]
> Do you think it would make sense to introduce another app requirement matching the above clause for the apps we "own" so they would not be displayed in the app bin under system apps if we view another local channel?

This probably does not make sense since it is only relevant for the nav. I will deal with it in include/nav.php
