### ISSUE TITLE
w2w posts not removed in contact_remove()

### ISSUE THREAD

**Issue by pkillnine** [redmatrix/hubzilla#837]

**Comment by git-marijus** [comment]
This actually works for me. Mind to provide the rss source you have issues with?

**Comment by pkillnine** [comment]
it did it for quite a few different ones, one of them is `www.reddit.com/r/latestagecapitalism` (adding that url automatically adds RSS feed).

On second thought, the hub I'm using may be out of date, how do I find out the version a hub is on?

**Comment by git-marijus** [comment]
> On second thought, the hub I'm using may be out of date, how do I find out the version a hub is on?

https://yourhub.tld/siteinfo

**Comment by pkillnine** [comment]
thanks, it's running version 2.4.2 on 'Standard'.

**Comment by git-marijus** [comment]
`www.reddit.com/r/latestagecapitalism` does not seem to be an rss feed

**Comment by pkillnine** [comment]
oh I think Hubzila automatically finds teh rss feed if you add a subreddit as a URL, regardless the feed version URL is https://www.reddit.com/r/LateStageCapitalism.rss

**Comment by git-marijus** [comment]
I see... This happens because the author of the posts is not the the channel but they are so called wall-to-wall posts from other authors.

@zotlabs would it have any unwanted consequences if we look for both author- and owner- xchan in contact_remove() for finding items?

**Comment by zotlabs** [comment]
That should be OK.
