### ISSUE TITLE
feature request: display # of notifications in browser window/tab title (main.js?)

### ISSUE THREAD

**Issue by rmonret** [redmatrix/hubzilla#843]
https://github.com/redmatrix/hubzilla/blob/47d55694a4c84b6c12c0db61a69bcac8b671b20e/view/js/main.js#L396

I see that we could insert in this region above a snippet to update the title of the browser window/tab to reflect the number of active notifications. This would allow one to know if there is anything new just by looking at the name of the tab, instead of going back and forth from tab to tab to see if there is no news (in case one is browsing other sites in other tabs).

Examples:
- no notifications: browser tab title = "Hub name"
- 5 active notifications: browser tab title = "(5) Hub name"

**Comment by zotlabs** [comment]
[master 4addde7] put unseen network count in page title; hubzilla issue #843

**Comment by rmonret** [comment]
Thanks a lot for the quick action. Data.notify seems more adequate to me as it concerns direct replies/actions only on topics I have showed interest into, network notifications being very frequent and broad. 

I lost my hub in the update to 2.6 and the backup restore failed so I can't ask the community what their preference would be right now. I'll load my private key into another hub until my own is back up and running (blessed be nomadic identity).

Thanks again.

**Comment by zotlabs** [comment]
Ouch. Sorry to hear that. Anyway I was torn between what to display; and network notifications is the important one to me, but I imagine others may have different preferences; or have it change based on what page/tab is currently loaded. Now that there is a mechanism, feel free to extend it to your needs. 

Anyway back to the restore briefly - did you also update addons? That would be critical in a major upgrade like this.

**Comment by rmonret** [comment]
Just did a git pull but couldn't yet get my hands on the command to update the plugins. I just had access to the server for a short time. I'll look into it, thanks!

**Comment by zotlabs** [comment]
util/safemode on 

will allow you to start without plugins by disabling them all. It stores the names of the disabled plugins in a file in the top level directory so that 'safemode off' can re-enable them.

util/udall will git pull everything - core, addons, themes, and any other third-party resources you're using.

**Comment by rmonret** [comment]
It worked. Thanks again !
