### ISSUE TITLE
delivery problem?

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#845]
Today I have experienced delivery issues, maybe it's just a false alarm, a problem inside the hub, but I've noticed a grid (timeline) overly calm in the last few hours, in 2/3 different channels, maybe someone else might have the same problems (after the upgrade).

In any case, the delivery reports of those posts always give me "no result"...
and _redeliver_ does not work , always "no result".

**Comment by elvecio** [comment]
news: 
now I can see  the posts (from yesterday) in my main channel ( network-grid) ;)
..but if I enter in that channel I got again "no result" in delivery report for those posts.
strange behavior.

**Comment by elvecio** [comment]
Doing little experiments:
I've created a post just for some people, and it works fine ;-) .

The problem is when I make a public post. Someone or something blocks the delivery.

  I do not use gnusocial protocol, but i have a gnusocial follower , so i deleted the follower, but the problem continues ..

Now I have noticed followers with serious 'certification issues' or similar things in their hubs, maybe I try to get rid of them and see what's happening.
I start to be convinced that some of these are blocking delivery, if so then we all could have serious problems.

**Comment by elvecio** [comment]
Another strange thing:
after the cloning I got one more contact ( in the main channel  I had x contacts and in the clone x+1)..
is rex@manhut.us  the +1 connection (rex@manhut has a strange configuration comparing with others hubzilla channels)
So I deleted this contact from my connections in the clone,  and now  I have the same connections.

After the upgrade of the hub the problem continues ( bad delivery report and a giant delay for public posts), just with this channel, and just with public posts ( not public works well ;) ) , and the other channels in the hub  work well too..and also the clone  with  same connections works well (so now  I don't know what's the real cause of the problem in the main :-( ).

**Comment by zotlabs** [comment]
Any chance you have the nofed plugin enabled on one site and not the other? Otherwise unless you get lucky and discover something to go on it's very difficult to fix this without logs.

**Comment by elvecio** [comment]
'Any chance you have the nofed plugin enabled on one site and not the other?'
the other channels in that hub ( hub with  problematic channel) work well. (ps: also the channels in the other hub  work well).

Maybe in the main channel the connection rex@manhut.us is still there (this explains why after the cloning he appeared in the list of connections of the clone), but I can not see him, is like a ghost channel, and maybe this causes the delivery problem.(and the bad report).
I've already talked to the admin, but he said he did not see anything strange in the logs. Maybe  he can look again.
Of course the problem is relative, because the clone works well, and I use the clone ;-) , in any case is a new problem, and it would be nice to find out the cause.

**Comment by elvecio** [comment]
the constant continues to be : 'no result'  in delivery report.

I just found that the channel with the problem is in a hub with MariaDB.

**Comment by zotlabs** [comment]
Just in case this matters - I discovered my channel was not delivering for several weeks; it turned out to be that the phppath in .htconfig.php was set to a 5.5 version of PHP; and we're now using a lot of 5.6 features in the code. At first this didn't prevent delivery but eventually enough of these changes went in that the delivery daemons started failing. 

Execute the version of php in config['system']['phppath'] from the command line with the -v flag and make sure it's running *at least* 5.6 and preferably 7.0 or greater.

**Comment by elvecio** [comment]
but it affects all the channels in the hub? because the other channels do not have this 'delivery problem', it seems that just ONE channel has this problem in the hub.

**Comment by elvecio** [comment]
I don't know what happened in  the _parlementum_ hub  but it seems that now that channel works well, no more delivery problem (testing today).
