### ISSUE TITLE
Webdav access broken with 2.6

### ISSUE THREAD

**Issue by solstag** [redmatrix/hubzilla#846]
After upgrading when I try to mount a webdav space through Gnome's Nautilus my credentials get refused and the following gets logged:

```2017-08-18 04:19:04:LOG_INFO:f75ab4abb33bcfd2a4853f45b6a5cf05:BasicAuth.php:114:validateUserPass: module not enabled for testchannel```

Looking at the code it seems that the function `check_module_access` will only return `true` if the module is `cdav` and not `dav`. Adding `dav` made it work again...

**Comment by zotlabs** [comment]
Must be a regression from the cdav integration. I used DAV several days ago without issue. We may not require this function any more, but the correct fix if it is to remain is:

````
   protected function check_module_access($channel_id) {
        if($channel_id && in_array(\App::$module,[ 'dav', 'cdav', 'snap'] )) {
            return true;
        }
        $this->module_disabled = true;
        return false;
    }
````

**Comment by solstag** [comment]
Works for me now! Thanks, as always =]
