### ISSUE TITLE
The selected theme is not displayed in the Settings->Display->Display Theme Select

### ISSUE THREAD

**Issue by subrealist** [redmatrix/hubzilla#855]
## The selected theme is not displayed in the Settings->Display->Display Theme Select
If several themes are available and selected theme isn't in top select option and selected scheme isn't scheme by default then selected theme isn't displayed in the Settings->Display->Display Theme Select after Settings->Display loading.

### Steps to reproduce

1. Open Settings->Display from Profile menu
2. Make sure that several themes are available in Display Theme select options (eg 'bookish', 'mytheme','redbasic' in this order from top to bottom)
3. Select the theme which isn't in the top option list and has several Select scheme options (eg 'mytheme')
4. Select scheme in the Select scheme select which isn't default scheme (eg 'BS-Default')
5. Click 'Submit' button

### Expected result
The theme 'mytheme' is selected in Display Theme Select after page reload

### Actual result
The theme 'bookish' is selected in Display Theme Select after page reload

### My invistigation

I found that when you select a different scheme from the default scheme then in the file 'Zotlabs/Module/Display.php' Line 161 (master and dev)  the  $theme_selected variable gets the value 'mytheme:BS-Default' which can't  be the same as any option values in the file ' hubzilla/view/tpl/field_themeselect.tpl' Line 7 and selected theme can't be displayed as selected.

### My workaround
```
'Zotlabs/Module/Display.php'
161     $theme_selected = ((array_key_exists('theme',$_SESSION) && $_SESSION['theme']) ? $_SESSION['theme'] : $theme);
162
163+    if (strpos($theme_selected, ':')) {
164+       $theme_selected = explode(':', $theme_selected)[0];
165+    }
166+
167     $mobile_theme_selected = (!x($_SESSION,'mobile_theme')? $default_mobile_theme : $_SESSION['mobile_theme']);
```

**Comment by jeroenpraat** [comment]
What Hubzilla version are you using? 

I think I had the same issue, but that was fixed a while ago: https://github.com/redmatrix/hubzilla/issues/624

**Comment by subrealist** [comment]
Yes, issue #624 is very similar, but that has fix version 2.2 on March 2 2016.
I am using latest Repository Hubzilla version (master)   2.6.2. Last commit:
commit 1305584d77e1b7ecedb545b92b037a89dd631361
Author: zotlabs <mike@macgirvin.com>
Date:   Tue Sep 5 17:12:31 2017 -0700

**Comment by git-marijus** [comment]
IIRC we don't actually support schemes for derived themes (the schema select should say something like "no schemes available").

I wonder why you have any schemes to select at all with a derived theme selected.

**Comment by subrealist** [comment]
'mytheme' isn't derived themes. This is full copied and slightly modified (I learned about Habzilla and began to study it a few days ago) theme Redbasic.
Вut I do not think that the issue is side effect of 'mytheme'.
Issue is actual after select 'Redbasic' with scheme 'BS-Default' (or any except 'Focus') if there are present any themes above it in the theme list. Even in that case if 'mytheme' is disabled in the admin panel (and is absent in the theme list respectively).

**Comment by git-marijus** [comment]
Ah... I see...
Would you mind to create a pullrequest with your fix?

**Comment by subrealist** [comment]
#856

**Comment by git-marijus** [comment]
Thank you!
