### ISSUE TITLE
how much time does util/importdoc take?

### ISSUE THREAD

**Issue by slobinger** [redmatrix/hubzilla#864]
just installing hubzilla on my own little server and waiting for util/importdoc pass for 25 minutes and it hangs still on output
```
root@<HOST>:/var/www/hubzilla# util/importdoc
doc/AdvancedSearch.md

```
Should I be more patiant or is there something I miss.

## What I did

1. create new dir /var/www/hubzilla
2. git clone this repo
3. `chown www-data:www-data -R /var/www/hubzilla`
4. `util/add_addon_repo https://github.com/redmatrix/hubzilla-addons.git hzaddons`
5. `util/importdoc`

## my system
Ubuntu 16.04.3 LTS
PHP Version => 7.0.22-0ubuntu0.16.04.1

**Comment by git-marijus** [comment]
You should install the app before executing util/importdoc

**Comment by slobinger** [comment]
Ah so this is just a hint for maintenance. THX!
