### ISSUE TITLE
Deleting images in /cloud does not delete them from /photos

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#87]
It works the other way around.

**Comment by git-marijus** [comment]
your fix just removed the linked item... i added a query to delete the photo from /photos aswell in 44b542814a0723ecd738ca02fad2e71d878197be

**Comment by redmatrix** [comment]
I (mistakenly) thought we did this with the lowlevel drop_item stuff. Now I remember that we didn't. So yes it needs to be removed separately.
