### ISSUE TITLE
Installation page not accessible if behind (ssl-)proxy?

### ISSUE THREAD

**Issue by fwolfst** [redmatrix/hubzilla#873]
I try to run hubzilla in an http-only apache, which is proxied with a nginx (who serves the ssl and "connects the dots" to the actual domain name).

From within the local "net" (its all VMs, really) I can access the installation-check page via the machines IP adress. The script itself complains about .htaccess rewrite rules which have to do with ssl I think.

From "outside" however I can only access some static files and fail to find any helpful log message anywhere. I suspect it has to do with my setup. Anybody can give me pointers to whether this should work?

Base is a vanilla ubuntu16.04 VM. The actual proxy is using dokku and its nginx-templating. I am happy to provide any configuration details if that helps. thanks.

**Edit** I manage to see the default Apache accessed from outside via https and the domain name (if I reset the apache config). But the installation page is only accessible from within, without domain name.

**Comment by fwolfst** [comment]
Okay, small progress:
`sudo hostname myhost.mydomain`,
edit `/etc/hostname` and `/etc/hosts` accordingly. But now the installation check does not understand that no .htaccess ssl-redirection is necessary anymore (and resolves to localhost i guess):

`Url rewrite in .htaccess is not working. Check your server configuration.Test: array ( 'return_code' => 0, 'success' => false, 'header' => '', 'body' => '', 'error' => 'Failed to connect to myhost.mydomain port 443: Connection refused', 'debug' => array ( 'url' => 'https://myhost.mydomain/setup/testrewrite', 'content_type' => NULL, 'http_code' => 0, 'header_size' => 0, 'request_size' => 0, 'filetime' => -1, 'ssl_verify_result' => 0, 'redirect_count' => 0, 'total_time' => 0.0042620000000000002, 'namelookup_time' => 0.004215, 'connect_time' => 0.0, 'pretransfer_time' => 0.0, 'size_upload' => 0.0, 'size_download' => 0.0, 'speed_download' => 0.0, 'speed_upload' => 0.0, 'download_content_length' => -1.0, 'upload_content_length' => -1.0, 'starttransfer_time' => 0.0, 'redirect_time' => 0.0, 'redirect_url' => '', 'primary_ip' => '', 'certinfo' => array ( ), 'primary_port' => 0, 'local_ip' => '', 'local_port' => 0, ), )`

Have to fake or uncomment that somehow.

**Comment by zotlabs** [comment]
This is the relevant issue:

````
Failed to connect to myhost.mydomain port 443: Connection refused
````

**Comment by fwolfst** [comment]
Yes. But when in production will the hubzilla instance have to speak with itself via 443? Afaiu this check is for making sure that htaccess redirection works and ssl is set up.

**Comment by zotlabs** [comment]
Not often, but yes - it will. Some message deliveries are done locally, but for channel discovery and "friending" we don't distinguish whether it is a remote or local channel and connect via the web in both cases.

**Comment by fwolfst** [comment]
Oh damn. Okay, thanks for the info! I will keep this issue open until I resolved my case (or gave up :) ).
And I guess the certificate used has to be "browser-valid" also where hubzilla talks to itself?

**Comment by fwolfst** [comment]
So, doing a local port forward of 443 to the proxy changes the situation, but the rewrite test (`Zotlabs/Module/Setup.php`) fails. I am not an `.htaccess` pro, but which is the rewrite rule that should make this work (path is setup/testrewrite)? I do not see it in the distributed .htaccess file.

**Comment by fwolfst** [comment]
So, the basic setup seems to work fine. There was confusion because the address typed in into the web-installer does not end up as base-url (I believe, at least), so that I had to manually change it to https.
I believe my aim is kind of achieved (way more complicated than I'd wish to). Only thing I'd like to make sure is that self-messages arrive. @zotlabs Any way to test that? Which messages are delivered to the same hub via https://<adress>? Channel discovery? That would mean to test I add two channels, two accounts and try to find the other?

**Comment by zotlabs** [comment]
Simplest thing would be to visit /probe (a channel discovery tool) and enter the nickname of a local channel. If a bunch of information is reported, everything is fine. It also reports on the first line or two if it had to fallback from https to http in order to discover something.

**Comment by fwolfst** [comment]
Seems to work
