### ISSUE TITLE
Name of guest visitors in comments isn't visible

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#878]
I comment the post  [Test for commentar feature for not logged-in visitor](https://hub.libranet.de/display/7468b7173974cf7c8b1bbe82147b3d04846dcb3ebc20518671967c3977119685@hub.libranet.de) with guesttoken login. But the name of guesttoken in guesttoken post comment isn't visible.  

![screenshot-2017-10-15wallzilla-guesttoken-visit](https://user-images.githubusercontent.com/3226308/31581121-24431eae-b163-11e7-914d-619a338b71e0.png)

Version of https://hub.libranet.de is 2.6.3

**Comment by zotlabs** [comment]
Was not able to duplicate using current dev branch so I believe this may be resolved.

**Comment by git-marijus** [comment]
I can't reproduce either in current dev... Closing.
