### ISSUE TITLE
not logged visitor can see categories for not public posts 

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#885]
Not logged visitor can see categories for not public posts. For example https://hub.libranet.de/channel/wallzilla?f=&cat=Sternwarte

Version hub.libranet.de 2.8RC #28RC

**Comment by HappyPony** [comment]
You can retest this bug for wallzilla-channel

**public post at wallzilla-channel**
1. visit https://hub.libranet.de/channel/wallzilla/
2. you see "Wernadski" category in the left column
3. Click "Wernadski" category https://hub.libranet.de/channel/wallzilla/?f=&cat=Wernadski
4. you see public post marked with "Wernadski" category

**_not_ public post at wallzilla-channel**
1. visit https://hub.libranet.de/channel/wallzilla/
2. you see "Sternwarte" category in the left column
3. Click "Sternwarte" category https://hub.libranet.de/channel/wallzilla/?f=&cat=Sternwarte
4. you see empty page, because the post "Sternwarte" category is marked as "not public"

**Comment by git-marijus** [comment]
Not we. You should retest because we believe the issue is fixed now :)
You have to of course update your hub first...

**Comment by HappyPony** [comment]
fixed
