### ISSUE TITLE
searchfield in the menubar missed for windowsize smaller than 1180 px

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#886]
searchfield in the menubar missed for windowsize smaller than 1180 px. Tested with Firefox version 56.0.1 (64-Bit)

![2 8rctest](https://user-images.githubusercontent.com/3226308/31933337-1ce3d598-b8a9-11e7-9d9c-3338a2c2454b.png)

**Comment by git-marijus** [comment]
We change the navbar to mobile view earlier now. Basically at the point where right-aside disappears. There is no search field in mobile view navbar...

**Comment by HappyPony** [comment]
> There is no search field in mobile view navbar...

Provide hubzilla for mobile devices user no ersatz for search field?

**Comment by git-marijus** [comment]
fixed in 3efe144fa0c455529a3f6244557d1253885134cf
the breakpoint will be 992px now.
