### ISSUE TITLE
Public stream problem...

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#887]
Is there a way to separate the **public stream** by following the networks?
For example, I just want to see the public stream coming from Zot, or see that from gnusocial and just ...
Separate streams based on networks/protocols.
I mean at  user level ( not admin).

It seems to me the only way to not be suffocated, "murdered" by **diaspora users**. it's almost impossible to see what's happening in the Zot network using the public stream unfortunately.

**Comment by zotlabs** [comment]
Should be available in dev in a few days. Will require the Netselect widget from hubzilla-widgets to be added to your page layout for mod_pubstream . The widget is available now, but it will require core changes in dev to be merged from red before it will function.
