### ISSUE TITLE
layout for generic-content-wrapper element

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#889]
The for generic-content-wrapper element in version 2.8RC1 is destroyed . See for example 

1. http://hub2.sprechrun.de/page/hucope/hubzilla_pitch_lvee-2017_theses_de - one webpage instance under old Hubzilla version 2.4RC
2. https://hub.libranet.de/page/hucope/hubzilla_pitch_lvee-2017_theses_de -  one webpage instance under version 2.8RC1

I see, that the border and box-shadow styles here in generic-content-wrapper element:
```
.generic-content-wrapper {
border: 1px solid #ccc;
box-shadow: 0px 0px 5px 1px 
}
```
are void. Under version 2.6.3 was the layout for this webpage - s. 2. above - still korrekt.

//EDIT 27.10.2017 - http://hub2.sprechrun.de/page/hucope/hubzilla_pitch_lvee-2017_theses_de - one webpage instance under **old Hubzilla version 2.4RC**

**Comment by git-marijus** [comment]
The problem is that the section content is outside of the generic-content-wrapper block. Might be an issue in the layout. I could not reproduce this...
