### ISSUE TITLE
Diaspora likes

### ISSUE THREAD

**Issue by hfroese** [redmatrix/hubzilla#895]
After a couple of years [?] I'm back on Hubzilla and first off all: Great job guys!

Hubzilla is my central control for contacts on all networks like GNU-Social, Mastodon, Friendica, Quitter, Diaspora and of course Hubzilla now. So I added all my contacts to Hubzilla an will leave all other networks.

But there's an issue with diaspora likes:

Likes don't arrive to Diaspora. 

This is not only important to me but of course to photographers and autors on diaspora also 😊

**Comment by elvecio** [comment]
maybe you can report here https://github.com/redmatrix/hubzilla-addons/issues .

**Comment by git-marijus** [comment]
Fixed in 32ceecaf086a2bd0350a1340813453b269652c45
