### ISSUE TITLE
search app has no function

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#898]
[baseurl]/search app has no function 

Hubzilla-Version 2.8

**Comment by git-marijus** [comment]
You don's see an input field there?

**Comment by HappyPony** [comment]
Now works [baseurl]/search . Have you changed something?

**Comment by zotlabs** [comment]
The navbar search isn't present on tiny screens - when the sitesearch widget was commented out you just get a search page with no way to search for anything. For large screens the widget isn't necessary, but we don't have comanche directives for responding to screen size (yet).

**Comment by git-marijus** [comment]
> when the sitesearch widget was commented out you just get a search page with no way to search for anything

But for me there is a big input field on the search page. There is no actual need for the widget, thats why it was commented out probably... I wonder why you don't have the input field on the search page...

**Comment by zotlabs** [comment]
Looks like this is to blame in the main get() section:

````
if((! local_channel()) || (! feature_enabled(local_channel(),'savedsearch')))
            $o .= search($search,'search-box','/search',((local_channel()) ? true : false));
````

Conditions: a small screen but I'm logged in and have savedsearch enabled. Hence no input box.

**Comment by zotlabs** [comment]
So if I take out the conditionals, it will always show an input box. The only issue here seems to be that the saved searches aren't displayed if you have that feature enabled. I'll check this in at any rate but I may have to defer looking at why saved searches aren't listed (and note that if they were, they could end up using a lot of vertical space).

**Comment by HappyPony** [comment]
> The only issue here seems to be that the saved searches aren't displayed if you have that feature enabled.

Odd, https://hub.libranet.de/search?search= request displayed one input search field for https://hub.libranet.de/profile/wallzilla Profil notwithstanding the above saved searches aren't enabled. And  https://hub.libranet.de/search?search=  for https://hub.libranet.de/profile/nmoplus request aren't displayed input search field notwithstanding the above saved searches aren't enabled. Both channels wallzilla and nmoplus are hosted on libranet.de with version 2.8.

**Comment by HappyPony** [comment]
I have three locations for the **_nmoplus_ profile**, _hub.libranet.de_ and _gerzilla.de_ locations has the hubzilla **version 2.8**, freecommunication.org has version 2.06. But only on _hub.libranet.de_ displayed https://hub.libranet.de/search?search= request _none_ input search field. What can I do for investigate of cause for this behavior on _hub.libranet.de_?

**Comment by zotlabs** [comment]
In 2.8 you should get a search box at the top of the content if you are logged out. You may not get it if you are logged in.

**Comment by HappyPony** [comment]
Whre can I enable saved searches for version 2.8?

**Comment by git-marijus** [comment]
Additional Features > Network and Stream Filtering > Saved Searches
