### ISSUE TITLE
After update to 2.8: sending private mails sometimes doesnt work

### ISSUE THREAD

**Issue by lazyadmin111** [redmatrix/hubzilla#903]
I updated on my debian oldstable (jessie) server from 2.6.3 to 2.8. There is one user of hubzilla who now can't send me private mails using hubzilla any. He can write the mail, but when he presses the send button, nothing happens. The user is using some ipad (~ 4 years old).

I don't know yet how I shall debug it, if it is related to some browser stuff, the ipad or not. **My main question so far therefore is the following:** 

Does **anyone else have problems sending private mails** with hubzilla after the update? -- with which devices?

**Comment by git-marijus** [comment]
Nobody else reported such issue. Closing for now...
