### ISSUE TITLE
visual notifications for "unseen grid activity" and "unseen channel activity" in version 2.8 

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#904]
On my _nmoplus_ location on hub with version 2.0.6 receive I the visual notification how on screenshot - and without delay. On my several locations (for example _gerzilla.de_ or _hub.libranet.de_) with the version 2.8 receive I none visual notifications. Primary hub for _nmoplus_ is _libranet.de_. Details. [visual notifications for Unseen grid activity and Unseen channel activity in version 2.8](https://hub.libranet.de/search?tag=visualNotifications&zid=nmoplus%40hub.libranet.de)

![screensh](https://user-images.githubusercontent.com/3226308/32411628-85516be6-c1e0-11e7-8788-a81795295cb6.png)

**Comment by zotlabs** [comment]
In 2.8, notifications are now displayed on the right side of the content. On small displays which do not have space for the right side, you will need to click the ! (inside a triangle) to display the notifications and right side region.
