### ISSUE TITLE
Photos sync to Files but are unavailable as Album

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#905]
I am trying to implement an auto-update gallery workflow for artists. 

The idea is for an artist to snap a picture of their work with their phone, the app FolderSync automatically syncs the picture of the work to a pre-set public folder on Hubzilla, this folder should be available as an album for the new Portfolio widget, and the widget is included in the artist's gallery web page. Hey presto, the gallery web page shows a new work by the artist.

Photos sync to the correct public folder in Files, the public folder is visible under Photos, but no photos are visible there.

What is missing to make this work?

**Comment by git-marijus** [comment]
fixed in 988028577b19d2cf2825eec65e398d447d8d4056
