### ISSUE TITLE
notifications in the version 2.8

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#906]
Click and no harm done - s. screenshot
![sifura](https://user-images.githubusercontent.com/3226308/32658288-8da51526-c619-11e7-9fb0-ef635cd52c5f.png)

Hubzilla version 2.8

**Comment by jeroenpraat** [comment]
Please submit a complete bug report.

**Comment by HappyPony** [comment]
wich infos are missing?

**Comment by jeroenpraat** [comment]
Everything, except an image without context.

**Comment by HappyPony** [comment]
Can you please preciser designate, what you missed? I communicated Hubzilla Version - s. Startpost, Bugscenario with screenshot "I clicked on notification-Icon -> no harm done". I expected, that I see one notification, but "no harm done"

**Comment by jeroenpraat** [comment]
So you click on the notification and you see the text 'no harm done'? Where do you see that text? I don't see it in the screenshot. Please describe step by step what you were doing and what goes wrong?

**Comment by HappyPony** [comment]
I clicked, but I see none notifications, I see nothing. Nothing happens after click.

**Comment by jeroenpraat** [comment]
That is better, thank you. I guess the expected result is that it shows the actual notifications after it scrolls down?

**Comment by HappyPony** [comment]
Yes. Now I have understand: the cover image overlaid the actual notifications. Is this overlaid a bug or a feature? I mean it is a bug, specially for hubzilla beginners.

**Comment by HappyPony** [comment]
I suggest, that notifications triangle be not to show in the cover photo view. So 

![1](https://user-images.githubusercontent.com/3226308/32670710-ef9a4816-c644-11e7-82d7-f8482e998010.png)

**Comment by git-marijus** [comment]
fixed in 0d512dffc33c37ac187cff03d17102ecfe543883
