### ISSUE TITLE
I have none access to announcement for change in Hubzilla UI

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#908]
I have have none access to this allegedly [announcement for change in Hubzilla UI](https://hub.somaton.com/display/a768d19683121fddf45bf6cf06c2acc5302936ae1c084d14970f5133453cb8bd@hub.somaton.com?zid=nmoplus%40hub.libranet.de). I receive permission denied for this page. Is it a bug or a feature?

**Comment by zotlabs** [comment]
Feature.
