### ISSUE TITLE
Token for channel A make accesible not public webpage from channel B

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#909]
1. I created webpage WPB http://dummy.org/page/wpb on channel B with [observer=1/0] protected content
2. I created Token TCA for channel A zat=tca
3. I open webpage WPB  with token for channel A
4. I see protected content in webpage WPB

I mean, that is one bug, that Hubzilla display protected content in webpage WPB for visitor with **Token TCA, that is legal for channel A**. Because I created one token for access to channel A, not for channel B. 
Hubzilla version 2.8.1

**Comment by zotlabs** [comment]
Not a bug. [observer=1] is matched if the viewer is authenticated. It does not matter how they are authenticated or who creates the token.
