### ISSUE TITLE
importing an .ics file into the event calendar causes a post to be made in that channel for every event in the imported calendar.

### ISSUE THREAD

**Issue by spukkin** [redmatrix/hubzilla#91]
importing an .ics file into the event calendar causes a post to be made in that channel for every event in the imported calendar.

for example, if the .ics you're importing is a calendar that has events for every day of the week, you'll get 30 posts created on your channel. there should probably be an option to not create any posts.

**Comment by redmatrix** [comment]
... or create the posts with the "hidden" attribute set. These posts *should* be created with restricted visibility to only the event owner. One member mentioned that they were being propagated as empty events to others in the address book and I've seen this, but could never reproduce it. By default the imported events *should* only be visible in your own view of your stream (private items) and cannot be seen by anybody else. There is still the mentioned issue but I'm trying to provide clarity to the intended behaviour in case you're seeing something different.

**Comment by kenrestivo** [comment]
@git-marijus I guess this might get fixed as part of the work you're doing on events?

**Comment by kenrestivo** [comment]
To clarify, I'll consider this a UX issue since it confuses people. The posts are *not* getting published for other people following their stream, but there's no way for users to know that, so they think they're spamming everyone with this. Plus it also spams their home stream, which is annoying.

It'd be nice to either not create event posts in people's stream when they add an event unless they explicitly share it, since it surprises and alarms at least two users who've reported this, or have some setting (default off) where people could turn this behavior on.

**Comment by git-marijus** [comment]
The question comes up if we should create wall items at all for not shared events.

I can understand that it is annoying if you import a calendar with many events and get a wall item for every event. OTOH if you are used to get a wall item if you add an event for yourself (which is useful imho) it will be confusing if you dont get one if you ie import a calendar with a single event...

**Comment by git-marijus** [comment]
>The posts are not getting published for other people following their stream, but there's no way for users to know that, so they think they're spamming everyone with this.

This is not exactly true... Hubzilla members know (or should know) that if they click the padlock (if there is any) they can see exactly who is allowed to see the post.

**Comment by spukkin** [comment]
could there simply be a toggle that asks if the user would like to create post(s) for imported events?

**Comment by zotlabs** [comment]
This now mirrors the way photos work - the default is not to create a post and you are given an option of creating a post.
