### ISSUE TITLE
background problems...mandatory white

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#910]
I have problems in different channels  and different hubs with background color and background image. Despite the color or the picture there are always pages with a **white** background. I have already cleaned the cache, and tried other browsers, but the problem continues.

**Comment by git-marijus** [comment]
You can have custom settings only for pages which belong to you aka channel apps. You, for example, can't set a custom bg-image for directory because it's a system page...

**Comment by elvecio** [comment]
I have  white ( despite green is the color) in  /network and /channel/nameuser for ex. 
But  I saw that  it happens just in hubs with the latest versions.
In my channels in hubs with older versions it's all ok.
So the problem is just in the latest versions.
ps: I have a lot of channels  in different hubs.

**Comment by git-marijus** [comment]
I see...

It seems on every page where there is no profile photo it works... Where we have a profile it does not...
