### ISSUE TITLE
Notification text is truncated and leaves the important part out

### ISSUE THREAD

**Issue by mrjive** [redmatrix/hubzilla#911]
While I like the notification box in the right column, I think it needs a bit of adjustment
![schermata del 2017-11-16 11-55-47](https://user-images.githubusercontent.com/5329200/32887735-446809c6-cac5-11e7-8296-4e4a6c0940ad.png)

To me there are some info that are not so relevant while important bits are left out:

- In the case above the name of the person who has commented the post il repeted twice
- The name of the person notified is superfluous since it's me! :)
- I cannot see the important part, that is what he has commented.

I know the whole text appears as tooltip...

(Actually it is the same behavior as before if I recall it correctly)

Perhaps we could eliminate some extra stuff and make the text completely visible, simply not truncating it.

I think I can try to modify this, if you think it could be useful.

**Comment by git-marijus** [comment]
fixed in dev branch

**Comment by mrjive** [comment]
Thanks Mario!
Cannot test because I have ho DEV anywhere.
