### ISSUE TITLE
redbasic, schema, dark 

### ISSUE THREAD

**Issue by albigro** [redmatrix/hubzilla#915]
Just some cosmetics:
changed in view/theme/redbasic/schema/dark.css line 142
.nav-link.active {
	color:#FFF !important;
color to 000
and added later ( for the new dropdown list)
.text-dark {
	color: #aaa !important;
}
a.text-dark:focus, a.text-dark:hover {
	color: #ddd !important;
}
not sure if it's the right way doing this, it worked, ...

**Comment by git-marijus** [comment]
The dark schema is not actively maintained atm. It would be great if you could to this :)
Please open a pullrequest for the propsed changes...

**Comment by albigro** [comment]
Pullrequest opened,... (hope so)
I'm happy to help with what i can, but i'm definitely not a web developer even new to an active user with git.
Took me ages to find the fix in the css,...
So sorry, but me as a maintainer won't work.
