### ISSUE TITLE
menu vanished for window width less as 985 px, Version 2.9.4

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#926]
menu vanished for window width less as 985 px

![2017-12-14_08-07](https://user-images.githubusercontent.com/3226308/33980042-69eb47b0-e0a7-11e7-9a95-85e135a8aee1.png)

**Comment by git-marijus** [comment]
That is by design. You get an icon with an arrow to the right in the panel at that point to bring it in.
