### ISSUE TITLE
input text vanished after click on "attach file" button

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#928]
After click on "attach file" button vanished  input text 

> Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum 

for browser window width less as 985 px. Hubzilla Version 2.9.4. Browser Firefox, Version 57.0.2, 64-Bit:

![2017-12-14_15-27](https://user-images.githubusercontent.com/3226308/33997248-0dea5bb2-e0e4-11e7-8eb3-e0e335d7a17c.png)

**Comment by zotlabs** [comment]
I was able to reproduce. This is on the mail page. At small screen widths (no sidebars visible), clicking attach loads a different (default?) page. At larger widths attach works correctly.

**Comment by zotlabs** [comment]
fixed in red
[master 8691262] hubzilla issue #928
