### ISSUE TITLE
autoname($len) returns sometimes $len-1

### ISSUE THREAD

**Issue by dawnbreak** [redmatrix/hubzilla#935]
The function **autoname($len)** is randomly failing in unit tests. The reason is that under certain conditions the result is $len-1. Is this desired behaviour and should I change the tests and add documentation or should we change the behaviour of the function?

**Comment by zotlabs** [comment]
This is known behaviour and should probably be documented. Some characters or combinations of characters don't work well at the end of a "pronounceable" string, so we chop it off. For instance the letter 'q' (even though it works in 'Iraq') doesn't make a very good word ending, also the consonant pairs 
'bl', 'br', 'cl','cr','dr','fl','fr','gl','gr','kh', 'kl','kr','mn','pl','pr','rh','tr','qu','wh'

which may be OK in the beginning or middle of a string but usually don't work very well at the end. The $len parameter should probably be documented as a maximum length. It should also probably be recommended that $len >= 3 and checked for an empty string if specified as less than that.
