### ISSUE TITLE
Channel import version compatibility

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#941]
My hub is down atm and i tried to revive my channel with an cca 4MB big channel export from about half year ago. I succeded to import it at another hub (current dev). I did not make it primary.
I got a Warning: Database versions differ by 5 updates. The channel does not seem to be functional. Magic auth (or remote auth) does not work, connecting with new channels does not work and comunication with existing channels also seems broken.

My question is if old exports are compatible with newer versions at all or are we having issues with cloning since the switch to owa?

**Comment by git-marijus** [comment]
I suspect this is due to servers timing out...

**Comment by zotlabs** [comment]
The DB version warning is only a warning which we do not act on.  There are no incompatibilities that I'm currently aware of, however something clearly went wrong with the import. OWA should not be an issue as it does not depend on any database changes.

**Comment by zotlabs** [comment]
Just some data points. I've looked back 5+ updates and found nothing that should cause a problem with the current importer. I've visually checked each of these for import conflicts. I'm not able to generate an older import file currently, but import works from a current dev site (so the import code itself probably isn't buggered). Given the things you mentioned as broken, the probability is highest that the channel store failed, with xchan/hubloc less likely and abook at an even lower probability.
