### ISSUE TITLE
Keywords at directory and DIRECTORY_MODE_STANDALONE

### ISSUE THREAD

**Issue by chris1315** [redmatrix/hubzilla#945]
When a hub has DIRECTORY_MODE_STANDALONE
App::$config['system']['directory_mode']  = DIRECTORY_MODE_STANDALONE;

Keywords should comes only from the hub not from the whole network. But apparently keywords come from others sites.

**Comment by zotlabs** [comment]
Fixed upstream 
[master 5a8efc1] hubzilla issue #945 - directory keywords returned from twkn in standalone mode

**Comment by chris1315** [comment]
With DIRECTORY_MODE_STANDALONE;

When you have only this web site  only  Yes  : No key words

This website only : Non : Key words from this website are displayed and only this website.

That works. But this is not logical. Why the keywords are display only when 'this website only' is No and disappear when this website only is Yes
