### ISSUE TITLE
Link "In Vollbildansicht anschauen" doens't work propper

### ISSUE THREAD

**Issue by hfroese** [redmatrix/hubzilla#947]
Link "In Vollbildansicht anschauen" directs to hubzilla main page instead to image
Found on this post of a diaspora user for example:

![20180101-0955](https://user-images.githubusercontent.com/1968490/34466610-09bbee12-eeda-11e7-82b4-90979df223e3.jpg)

**Comment by zotlabs** [comment]
Fixed upstream and will hopefully be merged when Mario returns.

**Comment by hfroese** [comment]
Thanks for this fast and good job.

**Comment by hfroese** [comment]
Perfect!
