### ISSUE TITLE
SECURITY: Update SabreDAV to a supported version

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#95]
According to http://sabre.io/dav/upgrading/ SabreDAV 1.8 is not supported anymore. I suggest to update to version 3.0

**Comment by dawnbreak** [comment]
There is a redmatrix branch with SabreDAV 2.1 which requires PHP5.4 and also adds several other improvements (https://github.com/dawnbreak/redmatrix/commits/RedDAV for an overview). My use cases I have tested and seems to be working, but it changed a lot and more in depth testing was needed, but then I got bit short of free time. Bringing it to SabreDAV 3.0 requires a re-factoring of the the auth plugin again. Would also like to finish principals and ACLs which will be needed for full CalDAV and CardDAV. Upcoming SabreDAV 3.1 will require PHP5.5. Is hubzilla ready for raising this requirement yet?

**Comment by git-marijus** [comment]
IMHO now is the best time to make the transition. Were still in beta and most critical bugs have been ironed out. I can do some of the work but will surely need help with things like rewriting auth plugin etc.
What does @redmatrix think?

**Comment by mestaritonttu** [comment]
PHP 5.4 is already EOL, so 5.5 minimum would be great: http://php.net/eol.php

**Comment by redmatrix** [comment]
I'm ok with a 5.5 requirement. The auth plugin probably wouldn't be too bad - we've now split of /cloud and /dav and the most painful bits of the auth plugin were making them work together.

**Comment by redmatrix** [comment]
Noting that we're now at 3.1 and there's a dev effort for moving it to 3.2
