### ISSUE TITLE
Saving posts into folder fails, possible JQ error

### ISSUE THREAD

**Issue by tluther** [redmatrix/hubzilla#950]
Saving a post into a folder does not work on the current RC3.0 branch.

Systen: Linux workstation, Debian 9.3
Browser: Firefox 97.03
Also experienced on FF and FF Beta for Android, 

Last (known) working HZ version: 2.8.1 - 1196
Currently tested HZ version: 3.0RC - 1198

1. click "Save to folder"
2. entering folder name or choosing an existing folder name
3. hit "Save"

Expected result: Post is saved to folder
Experienced result: 
- On Debian: busy cursor appears, nothing else happens
- On FF Android: Nothing visible happens

Also tested on: 
Android: Chrome, Chromium
Debian: Chromium

Possible hint in FF Debug console on Debian:
`ReferenceError: NavUpdate is not defined
network:488:6
itemFiler/</<
https://hubzilla.rocks/network:488:6
dispatch
https://hubzilla.rocks/view/js/jquery.js:3:10264
add/q.handle
https://hubzilla.rocks/view/js/jquery.js:3:8326`

**Comment by git-marijus** [comment]
Thanks for the detailed bug report :) This issue should be fixed now.

**Comment by tluther** [comment]
Tested, #isfixed
