### ISSUE TITLE
Call to undefined function Zotlabs\\Web\\session_start()

### ISSUE THREAD

**Issue by streaps** [redmatrix/hubzilla#955]
I'm getting this error with a fresh installation on Alpine Linux 3.7, PHP 7.1.2, Apache 2.4.29. I tried Hubzilla 3.0 and 3.0.1. Any idea what causes this error?

```
[Sun Jan 14 16:20:10.566967 2018] [php7:error] [pid 1000] [client 10.0.3.191:48276] PHP Fatal error:  Uncaught Error: Call to undefined function Zotlabs\\Web\\session_start() in /srv/www/hubzilla/Zotlabs/Web/WebServer.php:38
Stack trace:
#0 /srv/www/hubzilla/index.php(14): Zotlabs\\Web\\WebServer->run()
#1 {main}
  thrown in /srv/www/hubzilla/Zotlabs/Web/WebServer.php on line 38
```

**Comment by streaps** [comment]
Thanks, I already installed php7-sessions (it's an extra package on Alpine Linux), but forgot that I have to to restart Apache.

Is the Session module the only one, which is not checked for on install?

**Comment by streaps** [comment]
The json module was missing, too.

**Comment by zotlabs** [comment]
Session support has traditionally been included in the PHP core installation by default. So in answer to the question, if sessions was removed from php core in Alpine, any number of other PHP utilities could have also been removed from core; and there is no easy or clean way (currently) to enumerate them all to determine if any additional functions might be missing. Internally we use hundreds of PHP core functions.

**Comment by streaps** [comment]
Okay, I'm closing this issue. Thanks for the help.

**Comment by streaps** [comment]
Just for the record, these are the packages I had to install for hubzilla on Alpine Linux (I don't know if it covers everything):

php7
php7-apache2
php7-common
php7-ctype
php7-curl
php7-dom
php7-gd
php7-json
php7-mbstring
php7-mcrypt
php7-mysqlnd
php7-openssl
php7-pdo
php7-pdo_mysql
php7-session
php7-xml
php7-zip
