### ISSUE TITLE
Channel expansion inside code tags

### ISSUE THREAD

**Issue by fadelkon** [redmatrix/hubzilla#964]
In a [post to hubzilla support](https://gravizot.de/display/a16b0149089319fd797a3f825a3d864a3badfbfc7b0855b72dbc2cd09a76cea4@gravizot.de?zid=fadelkon%40libellula.criptica.org) I noticed that `https://libellula.criptica.org/channel/fadelkon` is expanding with a channel card `hz_card` using an `iframe` inside a `span` tag.

Well, I didn't expect this behavious inside `[code]` tags, so is there a way to block it? I am used to "code" content escaping any formatting.

What do you think?

-----

Actual behaviour
![actual](https://user-images.githubusercontent.com/20354477/35404993-1a51fe36-0205-11e8-8d1a-ff0356c50f27.png)
Expected behaviour
![expected](https://user-images.githubusercontent.com/20354477/35404994-1a9a9434-0205-11e8-8f80-7aef6a149f06.png)

**Comment by fadelkon** [comment]
This is affecting also quoted text.
Actual behavior
![actual](https://user-images.githubusercontent.com/20354477/35405892-b3f8a308-0207-11e8-96a7-133641d137f3.png)
Expected behavior
![expected](https://user-images.githubusercontent.com/20354477/35405894-b445e83e-0207-11e8-88ef-942bfeeeb392.png)

Please, in order to reproduce it exactly, visualize the entries [on gravizot.de](https://gravizot.de/display/a16b0149089319fd797a3f825a3d864a3badfbfc7b0855b72dbc2cd09a76cea4@gravizot.de?zid=fadelkon%40libellula.criptica.org) instead of libellula.criptica.org , as the latter one doesn't allow iframes.

**Comment by git-marijus** [comment]
Fixed in e3c7200b6f75e169b516c78b1f6ae383fd886ae0
