### ISSUE TITLE
...and if I do not want to appear in a channel's contacts list?

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#965]
For ex.:
Mister X  is a nazi-fascist, and I'm not, I blocked him, but

he try to add me  and I appear in the connections list of Mister X ( in this list there are 10 nazi-fascists + ME :-O ).
We need to find a solution for this problem, lately we have had these problems.

**Comment by git-marijus** [comment]
We now mark unidirectional connections with an no entry sign.
Reopen if you think this is not sufficient.
