### ISSUE TITLE
Disallow anonymous comment or content ? 

### ISSUE THREAD

**Issue by chris1315** [redmatrix/hubzilla#972]
Some comment or content can be open to not registered people.

Allow the admin to disable the not registered people comment for all the hub.

**Comment by elvecio** [comment]
The person (channel) can decide the permissions.
The options are:

- Nobody except yourself.
- Only those you specifically allow.
- Anybody in your address book.
- Anybody on this website.
- Anybody in this network.
- Anybody authenticated.
- Anybody on the Internet.


Maybe I did not understand: do you want the administrator to decide whether or not to have "external" comments?

**Comment by zotlabs** [comment]
The setting (system.anonymous_comments) is documented in help/hidden_configs
