### ISSUE TITLE
[dev] When editing content, textarea#profile-jot-text clears entire text field

### ISSUE THREAD

**Issue by DeadSuperHero** [redmatrix/hubzilla#974]
This is a problem that only seems to touch the `dev` branch. When I go to edit content, I can see it preserved in the textfield area. Upon clicking textarea, however, all of the content disappears.

**Features that this affects:**

* Statuses
* Cards
* Articles
* Pages
* Blocks
* Layouts
* Any other feature that uses the jot form

**Comment by zotlabs** [comment]
I'm not seeing this personally - perhaps you could describe in a bit more detail exactly what you are doing "When I go to edit content" and perhaps what browser/platform you're seeing it on - just in case that matters.

**Comment by DeadSuperHero** [comment]
Sure thing. This seems to happen on Firefox 57.0.4 (Quantum). Specifically, this occurs when I click the "Edit" link and navigate to the edit page. I can confirm that this happens in Ubuntu-based Linux distributions as well as macOS. I've managed to recreate the problem in Google Chrome and Safari on macOS.

I'm on the latest commit on `hubzilla/dev`, but this problem seems to have been introduced shortly after enabling the Articles feature. However, the problem persists even after disabling Articles, so I'm not sure it's directly related.

Notably, this problem does not seem to be happening on `stable`. I also double-checked that it wasn't my custom theme causing the problem; happens in unaltered redbasic as well as suckerberg.

One last bit is that it only seems to happen to my personal channel...other channels on my hub do not seem to be affected by it. :(

**Comment by DeadSuperHero** [comment]
Content when visiting editing page: 
![deadsuperhero](https://user-images.githubusercontent.com/401560/35883354-d9aef43e-0b3b-11e8-95b0-93e8eb254ed7.png)

Content when textarea is clicked:
![deadsuperhero](https://user-images.githubusercontent.com/401560/35883392-f6c65de6-0b3b-11e8-8515-f6dbf26538b4.png)


I'm going to try to disable all of my plugins to see if there's a culprit somewhere.

**Comment by DeadSuperHero** [comment]
Found the culprit. Looks like it was probably either Visage or the XMPP plugin causing problems. Everything works now!
