### ISSUE TITLE
Selecting last image out of 87 

### ISSUE THREAD

**Issue by hfroese** [redmatrix/hubzilla#979]
Selecting the last uploaded image out of more than 20 is very uncomfortable. 

![index2](https://user-images.githubusercontent.com/1968490/36323323-d2b85626-1350-11e8-8ab2-c03a58af401d.png)

The last uploaded image is on top but the OK button at the bottom of the popup window.

It would be nice to have an additional button on top of this window too.

**Comment by zotlabs** [comment]
Clarification for anybody looking at this issue: I believe this is referring to the 'embed photos from albums' jot widget

**Comment by hfroese** [comment]
Correct. Sorry for my bad explanation.

**Comment by git-marijus** [comment]
I think we should probably add a button to each selected image to go on.

Another ok button at the top would still be a lot of scrolling back if you selected an image in the middle.

**Comment by hfroese** [comment]
What's about a nice double click - if feasible?

**Comment by hfroese** [comment]
Double click works great - thanks

**Comment by git-marijus** [comment]
It's a single click actually...

**Comment by hfroese** [comment]
Okay... I doens't noticed that 😊
