### ISSUE TITLE
Wrong hostname / port for CSS stylesheets

### ISSUE THREAD

**Issue by StefanKrauth** [redmatrix/hubzilla#98]
Hello,
I have a hubzilla instance running. Unfortunately the stylesheet cannot be loaded. Hubzilla somehow uses the server internal hostname and port (which is both wrong in my setup).

The instance is running on an SSL enabled vhost running lighttpd.
The port 444 is internal, but 443 external.

I think the basename  from the configuration should be used.
The "if IE" section is doing it right...

![cssissue](https://cloud.githubusercontent.com/assets/663776/10716818/1fdaa90a-7b45-11e5-9dbb-fad1f6a5573a.jpg)

Best Regards,
Stefan

**Comment by StefanKrauth** [comment]
Hi,

I tried to figure out what the problem here is. I ran a php script to figure out how the different server variables are set.

If you access it via HTTP, it works as expected:
```
$_SERVER[SERVER_NAME]: www.skrauth.de
$_SERVER[SERVER_PORT]: 80
$_SERVER[PHP_SELF]: /tools/test.php
$_SERVER[REQUEST_URI]: /tools/test.php
$_SERVER[HTTPS]: 
$_SERVER[HTTP_HOST]: www.skrauth.de
$_SERVER[REMOTE_ADDR]: 78.42.128.130
```

If you access it using HTTPS, things are looking very different:
```
$_SERVER[SERVER_NAME]: stefan-krauth.de
$_SERVER[SERVER_PORT]: 444
$_SERVER[PHP_SELF]: /tools/test.php
$_SERVER[REQUEST_URI]: /tools/test.php
$_SERVER[HTTPS]: on
$_SERVER[HTTP_HOST]: www.skrauth.de
$_SERVER[REMOTE_ADDR]: 127.0.0.1
```

Script: https://www.skrauth.de/tools/test.php

I have a lot of software running with this setup and everything works also in the SSL environment (wordpress, friendica, diaspora, seafile uvm...)

Therefore I think you could rely on HTTP_HOST without any port information or give a configuration option to explicitly set the hostname and the port.

Best Regards,
Stefan

**Comment by StefanKrauth** [comment]
Hi again,

I fixed it now temporarily by changing include/plugin.php to:

```
function script_path() {
  if(x($_SERVER,'HTTPS') && $_SERVER['HTTPS'])
    $scheme = 'https';
  elseif(x($_SERVER,'SERVER_PORT') && (intval($_SERVER['SERVER_PORT']) == 443))
    $scheme = 'https';
  elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on')
    $scheme = 'https';
  else
    $scheme = 'http';

  if(x($_SERVER,'HTTP_HOST')) {
    $hostname = $_SERVER['HTTP_HOST'];
  }
  else {
    return z_root();
  }

  if(x($_SERVER,'SERVER_PORT') && $_SERVER['SERVER_PORT'] != 80 && $_SERVER['SERVER_PORT'] != 443 && $_SERVER['SERVER_PORT'] != 444) {
    $hostname .= ':' . $_SERVER['SERVER_PORT'];
  }

  return $scheme . '://' . $hostname;
}
```

I changed SERVER_NAME to HTTP_HOST and added my special port to the if statement.
I think the solution is okay besides the hard coded port 444.

I read that HTTP_HOST would contain the port also if other than 80 for HTTP and other than 443 for HTTPS that would also simplify the logic in this function.

Best Regards,
Stefan

**Comment by StefanKrauth** [comment]
Hi again,

I just verified, that HTTP_HOST also contains the hostname in case it's non standard.

![bildschirmfoto 2015-10-25 um 19 37 19](https://cloud.githubusercontent.com/assets/663776/10717163/db29f5d0-7b4f-11e5-85a2-b698cc275614.jpg)

I'll prepare a patch for the said function...

Best Regards,
Stefan

**Comment by StefanKrauth** [comment]
Keeping it open for discussion...

**Comment by redmatrix** [comment]
There is a lot of conflicting information out there. 

http://stackoverflow.com/questions/2297403/http-host-vs-server-name

We generally want the name assigned at the server rather than a name that was generated or used by the client, because in a decentralised communications system you could have an infinite number of hostnames used to access a webpage and you would need a location record for every channel in the network on every server name they might show up at. It simply doesn't scale. But in this case you've limited the fix to the script path. I'm mostly worried about destabilising the entire communications grid if this makes a difference for somebody. We have a lot of different servers and configurations represented. 

Ergo - I believe the prudent solution is to continue using what we have been using (server_name), but allow a configuration to use http_host in case that doesn't work for your specific server.  So I'm going to merge this and then add a configuration variable (you can set this in .htconfig.php)

$a->config['system']['script_path_use_http_host'] = 1;

but not set it by default.

**Comment by StefanKrauth** [comment]
Is there some documentation around the grid communication? I can't really comment on this.

From my side, when it comes to host names, I prefer to hard coded hostnames in the config file. Especially in a vhost / reverse proxy / load balancer environment you might end up with different server host names and ports that are valid for the IP, but not for the request from outside to access the instance. But as admin I know the URL and the port the users should connect to my hub. However, I could imagine scenarions where I want to do the server-to-server communication with a different host name.

So, optimally I would like to configure everything hardcoded. Maybe like this:
```
# server to server communication (the grid):
# Values: "SERVER_NAME", "HTTP_HOST" or full qualified host:port
$a->config['system']['S2S_HOST'] = "server.myhub.com:5000";

# server to client communication (users)
# Values: "SERVER_NAME", "HTTP_HOST" or full qualified host:port
$a->config['system']['S2C_HOST'] = "www.myhub.com";
```

This would give the admin full control over the environment. This is just an idea and it might not be applicaple to the hubzilla architecture.

**Comment by redmatrix** [comment]
I don't believe that will work within our current architecture. In our authentication exchanges we go back and forth between the two domains (using both forms) before ending up with a client on server A being authenticated as client on server B. Could be done, but that's not how it works today.

**Comment by StefanKrauth** [comment]
I've updated my instance and retested the configuration option. Works! Therefore I'm closing the ticket.

Thanks again!
