### ISSUE TITLE
Communication issues in dev branch

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#982]
It seems there are still communication issues. I can succesfully send posts and comments between two of my test servers. Mail does not work atm. 

Messages and mails between mario@hub.somaton and mike@macgirvin.com don't federate though...

Can't debug or provide more infos atm.

**Comment by git-marijus** [comment]
In fact i am seeing a "sender not valid" response from macgirvin.com in zot_process_response()

**Comment by zotlabs** [comment]
[master ae8623e] encrypt/decrypt function not found

**Comment by git-marijus** [comment]
Thanks. That possibly fixed the issue with posts (depending on if you got my message). Mail still returns "sender not valid"

**Comment by git-marijus** [comment]
It turns out that now also dev to master branch communication does not work...
