### ISSUE TITLE
Wiki: inline code redered as block code

### ISSUE THREAD

**Issue by Reylak** [redmatrix/hubzilla#992]
Title says it all: inline code using single back-quotes is rendered as blocks, as though written with triple back-quotes.

I'd guess Hubzilla uses an external Markdown renderer, is switching to another one the solution?

**Comment by git-marijus** [comment]
This issue is supposed to be fixed in current release candidate. 

https://github.com/redmatrix/hubzilla/commit/c444e40c016c0faaec604335093b19661b3585b7

**Comment by Reylak** [comment]
I pulled the latest master revision, but I still get code blocks for inline code (both on old pages and a new page). What am I missing? Can the theme have an effect on this?

**Comment by git-marijus** [comment]
Sorry. The alternative schemas don't have a maintainer atm. We are keeping the dark schema on life support. The simple_* schemas will probably be abandoned if nibody steps up to maintain them.

Please open a seperate issue for the dark schema issue.
