### ISSUE TITLE
mod channel permissions disregarded

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#998]
We have as of now two reported channels where permissions in the /channel stream are disregarded.
I could not reproduce this in my testings but can confirm the two situations.

**Comment by phellmes** [comment]
I can only post here for now since my channel is affected and I took down my hub completely. Let's try to find similarities between the affected channels.
I use expert settings on global channel permissions, not one of the predefined profiles. Maybe that's the case for the other channels too. Nothing else seems to be special here.

**Comment by einervonvielen** [comment]
Example https://digitalesparadies.de/channel/einervonvielen/?f=&mid=d086ce298a5e93840f67a0f647ff7a392337a0ee4e5a950a97bf3cca3949fefe@digitalesparadies.de

I wrote and posted it with permissions "Family". I uploaded pictures while writing the posts. "Family" contains two members. Both members of "Family" have only this account on the same hub as I have.

The standard permission for my post is "Family". I used it in this case as usual.

Result:

- Some others can see the posts (text)
- Those other users can not see the pictures (instead the see a denied sign)

**Comment by einervonvielen** [comment]
I am the admin of the hub and posted it from this account. I use the admin setting "I can write computer code".

**Comment by phellmes** [comment]
@einervonvielen 
I think I can see all posts on your channel when authenticated. Just without the photos. Since permissions are hidden I don't know if only a specific privacy group is affected. But there are a lot of posts I shouldn't see.
Unfortunately I can't tell since when this is happening because I didn't visit your channel directly for a while before today.

**Comment by phellmes** [comment]
@einervonvielen 
You could write one test post for the "family" group and another on for a different privacy group. Then I could check if I can see both of them on your channel or just the one for the "family" group.

**Comment by einervonvielen** [comment]
@phellmes Following your idea I created three post all with the same topic "Issue 998 - This is posted on my "Activtiy" stream "

The permissions are...

Old existing group "Family"
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=71ad354202527d3aad619881a4ec66b5d3680c110fa4948511018b5e41e392b6@digitalesparadies.de

New group "GroupIssue998"
Members = the two members of (old) group "Family"
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=069c0b1f9abee2ee18001ef351315109da50017efdb44e1b568e68a120ee4ba1@digitalesparadies.de

New group "GroupIssue998NotFamily"
Members = Andrew Manning and Marshal Sutherland
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=0374715c9ed31c5e8d29c6a6c6015724b921982f803a5e01be1f7b846eef0773@digitalesparadies.de

**Comment by einervonvielen** [comment]
@phellmes  I am not connected to you in Hubzilla (from my account to your account)

**Comment by einervonvielen** [comment]
@phellmes ok, next try...

this time I post from my channel page instead from the activities stream.

Issue 998 - This is posted on my "Channel Home" for "GroupIssue998NotFamily"
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=a141d72cc48205b51ce5ac9c2e3a1d28bf5078b04e7e0cc8e36e28e9b8b28f6a@digitalesparadies.de

Issue 998 - This is posted on my "Channel Home" for "GroupIssue998"
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=4ba2c3466c596b48a4ffe7c00fbfffbe84f58d1bfba7f5e476b333acc0306a43@digitalesparadies.de

Issue 998 - This is posted on my "Channel Home" for "Family
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=48712aee50e738ea6ed4f53d9dbf2da0099a374961c4519ad4c2a5f49a952338@digitalesparadies.de

@phellmes I will connect later on in order to not change the "test conditions". Maybe I removed you from my connections. My hub was slow quite a long time ago. So I removed unused accounts on my hub as well as connections of my account.

**Comment by einervonvielen** [comment]
The following post was send from my MOBILE PHONE. Permission is "Family". I uploaded a picture in the post. "Family" is the old existing group.

https://digitalesparadies.de/channel/einervonvielen/?f=&mid=104c71d87af2e75dd290037d1f56e8c2621ab8407c8893a3d7f1890a2cf68ef9@digitalesparadies.de

**Comment by phellmes** [comment]
So far all new posts are protected correctly while the old ones up to 03.03.2018 are visible on the channel page. It might help narrowing down the cause of the issue.

**Comment by einervonvielen** [comment]
The update to v3.2 might have fixed the issue? My hub was updated at 10nd of march at  05:32:52 CET 2018.

**Comment by einervonvielen** [comment]
This was the first post (11th of march) after the update to v3.2
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=d8431549638bdbd1416a037c3d06559a4cc89d64969a303dd7f99500bd3dc7f2@digitalesparadies.de

And this one was the last post before the update
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=d086ce298a5e93840f67a0f647ff7a392337a0ee4e5a950a97bf3cca3949fefe@digitalesparadies.de

No posts in between the two posts.

**Comment by phellmes** [comment]
Yep, cannot see the first, but the second one. Update fixed it - seems to be something about permissions stored with the posts before the update since they're still visible, not something related to the display.

**Comment by einervonvielen** [comment]
There IS a setting that I changed. between the two post. It was the default visibility of my channel post. I changed it from "Only authenticated" to "Everybody in the Internet". I will change this back an try again. Hold on a second....

**Comment by einervonvielen** [comment]
https://digitalesparadies.de/channel/einervonvielen/?f=&mid=f7da71f67b4861a96048eecece3b40216225f2ce55454e334fb4ff13b6f2b1a3@digitalesparadies.de

Before I posted this I changed the settings for "can see my channel stream and post" from
"anybody in the Internet" to "Any authenticated" (This is my translation from German to English.)

**Comment by phellmes** [comment]
I can see this post via link and on your channel page.

**Comment by phellmes** [comment]
This is odd - global channel permissions should not affect individual permissions on items when they are created and stored...

**Comment by einervonvielen** [comment]
> I can see this post via link and on your channel page.

Then we found it.... (Again using my translation from German to English)

It's the "Setting" > "Channel Settings" > "Security Settings" > "Limits for Channel Permissions" (Kanalberechtiungs-Limits) > "Can view my channel stream ans posts"

If I changes this one from "Anybody in the Internet" to "Any authenticated" you will see a post that has the permission "Family" (you are not in this group @phellmes ;-) )

**Comment by einervonvielen** [comment]
To verify this I changed back the default visibility of my channel and posts from  "Any authenticated"  to  "Anybody in the Internet".
The permission of the post iself is group "Family".
My "Standard Group" is left untouched. It is and was "Family" all the time.

You should not see the post now...

https://digitalesparadies.de/channel/einervonvielen/?f=&mid=c125480ca5615499c47cf25ff1d4262d968d598f883f142f57d70c5d5309cd56@digitalesparadies.de

**Comment by einervonvielen** [comment]
Alex confirmed the expected result. So it seems that we could reproduce the error.

**Comment by git-marijus** [comment]
I could reproduce the issue now. All posts posted with "Can view my channel stream and posts" setting set to "anybody authenticated" or "anybody in this network" are affected.
Those posts are visible to any authenticated channel (there must not be a connection between channels) and it does not matter what privacy group you posted to.

**Comment by thorsten23** [comment]
Is this limited to the "Can view my channel stream and posts" settings or are the other settings in the expert security mode also affected?

**Comment by git-marijus** [comment]
I have so far just tested with the "Can view my channel stream and posts" setting.

**Comment by zotlabs** [comment]
https://gitlab.com/macgirvin/red/commit/34399b8b47d9a85eb3c4095392ab994792257d88

**Comment by git-marijus** [comment]
I have pushed the fix to master. I would like somebody to test it before i announce the bugfix release 3.2.1 which also fixes some other little things.

**Comment by phellmes** [comment]
I just updated and created a test scenario like yesterday with 2 posts (settings changed and then changed back). This time both post are not visible on the channel page when viewed by another connection.
Seems to be working.

**Comment by git-marijus** [comment]
If you are affected by this bug the admin needs to run this SQL query to fix existing posts:

`UPDATE item SET public_policy = '' WHERE public_policy != '' AND ( allow_cid != '' OR allow_gid != '' OR deny_cid != '' OR deny_gid != '')`

This query might take several minutes to run. If there is no expiration policy in place and your database is huge, it could take significantly longer.

**Comment by git-marijus** [comment]
This issue is fixed in version 3.2.1
